//! C3 (#356) — forge-level trash: filesystem layer.
//!
//! Deleted entries move into `<forge>/.trash/<bucket>/`, where `<bucket>`
//! is a millisecond timestamp (suffixed `-n` on collision). Each bucket
//! holds exactly one trashed entry at its original relative path plus a
//! `meta.json` sidecar recording where it came from, so restore is
//! unambiguous even for directories:
//!
//! ```text
//! .trash/
//! └── 1780456123456/
//!     ├── meta.json          { "original_path": "notes/a.md", … }
//!     └── notes/a.md
//! ```
//!
//! `.trash` is excluded from the watcher, reconcile scans, and root
//! `list_dir` (same treatment as `.forge`), so trashed content never
//! reappears in search or the file tree. This module owns only the
//! filesystem mechanics; index bookkeeping (soft-delete + resurrect)
//! lives with the other SQL in `lib.rs`.

use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};

use crate::error::StorageError;

/// Forge-root directory name holding trashed entries.
pub const TRASH_DIR: &str = ".trash";
const META_FILE: &str = "meta.json";

/// Sidecar metadata written next to every trashed entry.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrashMeta {
    /// Forge-relative path the entry lived at before deletion.
    pub original_path: String,
    /// Unix epoch milliseconds at deletion time.
    pub deleted_at_ms: i64,
    /// Whether the entry is a directory.
    pub is_dir: bool,
}

/// A listed trash bucket: id + metadata + recursive byte size.
#[derive(Debug, Clone)]
pub struct TrashBucket {
    pub trash_id: String,
    pub meta: TrashMeta,
    pub size_bytes: u64,
}

fn now_ms() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| i64::try_from(d.as_millis()).unwrap_or(i64::MAX))
        .unwrap_or(0)
}

fn bucket_dir(forge_root: &Path, trash_id: &str) -> Result<PathBuf, StorageError> {
    // Bucket ids are generated by `move_to_trash` (digits + `-`); reject
    // anything path-shaped so a hostile id can't escape `.trash/`.
    if trash_id.is_empty()
        || !trash_id
            .chars()
            .all(|c| c.is_ascii_digit() || c == '-')
    {
        return Err(StorageError::PermissionDenied(format!(
            "invalid trash id '{trash_id}'"
        )));
    }
    Ok(forge_root.join(TRASH_DIR).join(trash_id))
}

/// Move the already-resolved entry at `abs` (forge-relative `relpath`)
/// into a fresh trash bucket. Returns the bucket id.
pub fn move_to_trash(
    forge_root: &Path,
    relpath: &str,
    abs: &Path,
) -> Result<String, StorageError> {
    let is_dir = abs.is_dir();
    let trash_root = forge_root.join(TRASH_DIR);
    let stamp = now_ms();
    let mut trash_id = stamp.to_string();
    let mut n = 0u32;
    while trash_root.join(&trash_id).exists() {
        n += 1;
        trash_id = format!("{stamp}-{n}");
    }
    let bucket = trash_root.join(&trash_id);
    let dest = bucket.join(relpath);
    let parent = dest.parent().unwrap_or(&bucket);
    fs::create_dir_all(parent)?;
    fs::rename(abs, &dest)?;
    let meta = TrashMeta {
        original_path: relpath.to_string(),
        deleted_at_ms: stamp,
        is_dir,
    };
    let meta_json = serde_json::to_vec_pretty(&meta).map_err(|e| StorageError::WriteFailed {
        path: format!("{TRASH_DIR}/{trash_id}/{META_FILE}"),
        reason: e.to_string(),
    })?;
    fs::write(bucket.join(META_FILE), meta_json)?;
    Ok(trash_id)
}

fn read_meta(bucket: &Path) -> Result<TrashMeta, StorageError> {
    let raw = fs::read(bucket.join(META_FILE))?;
    serde_json::from_slice(&raw).map_err(|e| StorageError::CorruptFile {
        path: bucket.join(META_FILE).display().to_string(),
        reason: e.to_string(),
    })
}

fn dir_size(path: &Path) -> u64 {
    let Ok(meta) = fs::symlink_metadata(path) else {
        return 0;
    };
    if meta.is_file() {
        return meta.len();
    }
    if !meta.is_dir() {
        return 0;
    }
    let Ok(entries) = fs::read_dir(path) else {
        return 0;
    };
    entries
        .flatten()
        .map(|e| dir_size(&e.path()))
        .sum()
}

/// Enumerate trash buckets, newest first. Buckets with unreadable
/// metadata are skipped (a half-written bucket from a crash mid-move
/// should not brick the listing).
pub fn list(forge_root: &Path) -> Result<Vec<TrashBucket>, StorageError> {
    let trash_root = forge_root.join(TRASH_DIR);
    let mut out: Vec<TrashBucket> = Vec::new();
    let entries = match fs::read_dir(&trash_root) {
        Ok(it) => it,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(out),
        Err(e) => return Err(e.into()),
    };
    for entry in entries.flatten() {
        let Some(trash_id) = entry.file_name().to_str().map(str::to_string) else {
            continue;
        };
        let bucket = entry.path();
        let Ok(meta) = read_meta(&bucket) else {
            continue;
        };
        let size_bytes = dir_size(&bucket.join(&meta.original_path));
        out.push(TrashBucket {
            trash_id,
            meta,
            size_bytes,
        });
    }
    out.sort_by(|a, b| b.meta.deleted_at_ms.cmp(&a.meta.deleted_at_ms));
    Ok(out)
}

/// Move a trashed entry back to its original path and remove the
/// bucket. Fails without touching anything when the original path is
/// occupied again.
pub fn restore(forge_root: &Path, trash_id: &str) -> Result<TrashMeta, StorageError> {
    let bucket = bucket_dir(forge_root, trash_id)?;
    if !bucket.exists() {
        return Err(StorageError::FileNotFound(format!(
            "{TRASH_DIR}/{trash_id}"
        )));
    }
    let meta = read_meta(&bucket)?;
    let dest = forge_root.join(&meta.original_path);
    if dest.exists() {
        return Err(StorageError::WriteFailed {
            path: meta.original_path.clone(),
            reason: "already exists — restore would overwrite".to_string(),
        });
    }
    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::rename(bucket.join(&meta.original_path), &dest)?;
    fs::remove_dir_all(&bucket)?;
    Ok(meta)
}

/// Permanently delete trash buckets. With `older_than_ms`, only
/// buckets deleted before that epoch-ms cutoff are removed. Returns
/// the number of buckets removed.
pub fn empty(forge_root: &Path, older_than_ms: Option<i64>) -> Result<usize, StorageError> {
    let mut removed = 0usize;
    for bucket in list(forge_root)? {
        if let Some(cutoff) = older_than_ms {
            if bucket.meta.deleted_at_ms >= cutoff {
                continue;
            }
        }
        let dir = bucket_dir(forge_root, &bucket.trash_id)?;
        fs::remove_dir_all(&dir)?;
        removed += 1;
    }
    Ok(removed)
}

/// Forge-relative paths of every file under `abs_root` (which sits at
/// forge-relative `rel_root`). Single files yield themselves. Used by
/// restore to reindex what came back.
pub fn walk_restored_files(abs_root: &Path, rel_root: &str) -> Vec<String> {
    let mut out = Vec::new();
    let Ok(meta) = fs::symlink_metadata(abs_root) else {
        return out;
    };
    if meta.is_file() {
        out.push(rel_root.to_string());
        return out;
    }
    if !meta.is_dir() {
        return out;
    }
    let Ok(entries) = fs::read_dir(abs_root) else {
        return out;
    };
    for entry in entries.flatten() {
        let Some(name) = entry.file_name().to_str().map(str::to_string) else {
            continue;
        };
        let child_rel = format!("{rel_root}/{name}");
        out.extend(walk_restored_files(&entry.path(), &child_rel));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn move_list_restore_roundtrip() {
        let dir = tempfile::tempdir().expect("tempdir");
        let root = dir.path();
        fs::create_dir_all(root.join("notes")).unwrap();
        fs::write(root.join("notes/a.md"), b"hello").unwrap();

        let id = move_to_trash(root, "notes/a.md", &root.join("notes/a.md")).unwrap();
        assert!(!root.join("notes/a.md").exists());

        let buckets = list(root).unwrap();
        assert_eq!(buckets.len(), 1);
        assert_eq!(buckets[0].trash_id, id);
        assert_eq!(buckets[0].meta.original_path, "notes/a.md");
        assert!(!buckets[0].meta.is_dir);
        assert_eq!(buckets[0].size_bytes, 5);

        let meta = restore(root, &id).unwrap();
        assert_eq!(meta.original_path, "notes/a.md");
        assert_eq!(fs::read(root.join("notes/a.md")).unwrap(), b"hello");
        assert!(list(root).unwrap().is_empty());
    }

    #[test]
    fn restore_refuses_to_overwrite() {
        let dir = tempfile::tempdir().expect("tempdir");
        let root = dir.path();
        fs::write(root.join("a.md"), b"one").unwrap();
        let id = move_to_trash(root, "a.md", &root.join("a.md")).unwrap();
        fs::write(root.join("a.md"), b"two").unwrap();
        assert!(restore(root, &id).is_err());
        // Bucket must survive the failed restore.
        assert_eq!(list(root).unwrap().len(), 1);
    }

    #[test]
    fn restore_rejects_path_shaped_ids() {
        let dir = tempfile::tempdir().expect("tempdir");
        assert!(restore(dir.path(), "../escape").is_err());
        assert!(restore(dir.path(), "").is_err());
    }

    #[test]
    fn empty_honours_age_cutoff() {
        let dir = tempfile::tempdir().expect("tempdir");
        let root = dir.path();
        fs::write(root.join("a.md"), b"x").unwrap();
        let id = move_to_trash(root, "a.md", &root.join("a.md")).unwrap();
        // Cutoff in the past → nothing old enough to remove.
        assert_eq!(empty(root, Some(0)).unwrap(), 0);
        assert_eq!(list(root).unwrap().len(), 1);
        // No cutoff → everything goes.
        assert_eq!(empty(root, None).unwrap(), 1);
        assert!(list(root).unwrap().is_empty());
        assert!(!root.join(TRASH_DIR).join(id).exists());
    }

    #[test]
    fn directory_roundtrip_preserves_children() {
        let dir = tempfile::tempdir().expect("tempdir");
        let root = dir.path();
        fs::create_dir_all(root.join("proj/sub")).unwrap();
        fs::write(root.join("proj/a.md"), b"a").unwrap();
        fs::write(root.join("proj/sub/b.md"), b"b").unwrap();

        let id = move_to_trash(root, "proj", &root.join("proj")).unwrap();
        assert!(!root.join("proj").exists());
        let buckets = list(root).unwrap();
        assert!(buckets[0].meta.is_dir);
        assert_eq!(buckets[0].size_bytes, 2);

        restore(root, &id).unwrap();
        let mut files = walk_restored_files(&root.join("proj"), "proj");
        files.sort();
        assert_eq!(files, vec!["proj/a.md".to_string(), "proj/sub/b.md".to_string()]);
    }
}
