//! Stable IPC arg/return types for the Phase 4 WI-36 pilot handler.
//!
//! This module hosts the authoritative contract for
//! `com.nexus.ai::stream_ask` (handler id `7`):
//!
//! - [`AiStreamAskArgs`]  — input
//! - [`AiStreamAskResult`] — final response on stream completion
//!
//! The streaming chunks themselves are published as `com.nexus.ai.stream_*`
//! bus events; only the final aggregated result crosses the IPC return value.
//!
//! Under the `ts-export` feature each type emits a TypeScript binding into
//! `packages/nexus-extension-api/src/generated/ipc/` and (via the
//! `nexus-bootstrap` harness) a JSON Schema into
//! `crates/nexus-bootstrap/schemas/ipc/`.
//!
//! See `docs/archive/planning/PHASE-4-IMPLEMENTATION-PLAN.md` §3.1 and
//! `docs/architecture/ipc-schemas.md` for the generator design.

use serde::{Deserialize, Serialize};

#[cfg(feature = "ts-export")]
use schemars::JsonSchema;
#[cfg(feature = "ts-export")]
use ts_rs::TS;

/// Role of a participant in a chat conversation. Mirror of
/// [`crate::provider::Role`] for schema emission.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(rename_all = "lowercase")]
pub enum AiStreamAskRole {
    /// System-level instructions.
    System,
    /// User input.
    User,
    /// Assistant response.
    Assistant,
}

/// One message in a chat conversation. Mirror of
/// [`crate::provider::ChatMessage`].
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct AiStreamAskMessage {
    /// The role of the message sender.
    pub role: AiStreamAskRole,
    /// Text content of the message.
    pub content: String,
}

/// Args for `com.nexus.ai::stream_ask` (handler id `7`).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct AiStreamAskArgs {
    /// Conversation history. The handler extracts the last `user` message as
    /// the retrieval question; system and assistant turns are forwarded to
    /// the chat provider verbatim.
    pub messages: Vec<AiStreamAskMessage>,
    /// Optional caller-provided session identifier. When `None` the handler
    /// generates a UUID v4. The id is echoed back in every
    /// `com.nexus.ai.stream_*` bus event so callers can demux concurrent
    /// streams.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    /// Maximum number of RAG source chunks to retrieve. Omit for the default
    /// of 5.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<u32>,
}

/// One retrieved source chunk used to ground the answer. Mirror of
/// [`crate::vectorstore::ChunkMatch`].
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct AiStreamAskSource {
    /// Path of the source file.
    pub file_path: String,
    /// Identifier of the originating block.
    pub block_id: u64,
    /// Textual content of the chunk.
    pub chunk_text: String,
    /// Cosine similarity score (higher is more relevant).
    pub score: f32,
}

/// Return type for `com.nexus.ai::stream_ask`. Mirrors the final
/// `stream_done` event payload and is what the IPC call resolves to when
/// the stream completes.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct AiStreamAskResult {
    /// Session id — matches the `session_id` on every `stream_chunk`
    /// event. Generated by the handler when the caller omitted it.
    pub session_id: String,
    /// Full aggregated assistant response.
    pub text: String,
    /// RAG sources that grounded the answer, in retrieval order.
    pub sources: Vec<AiStreamAskSource>,
}

/// Engine mode for `com.nexus.ai::stream_chat` (handler id `6`).
///
/// `Chat` (the default) runs the tool-aware dispatch loop; `Complete`
/// bypasses it for a single provider round-trip with no tools, suitable
/// for ghost completions and headless `complete` CLI consumers
/// (BL-010, BL-011, BL-034).
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(rename_all = "lowercase")]
pub enum AiStreamChatMode {
    /// Tool-aware multi-round dispatch loop (back-compat default).
    #[default]
    Chat,
    /// Single provider round-trip, no tools, post-processed.
    Complete,
}

/// Tool-advertisement policy for `stream_chat`.
///
/// `Auto` (default) hands the registry's full schema list to the
/// provider so the model can call tools. `None` advertises an empty
/// list — used by `mode=complete` and by ghost-completion callers that
/// must never trigger side effects.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(rename_all = "lowercase")]
pub enum AiToolPolicy {
    /// Advertise the full registry to the model — including
    /// mutating tools (`write_file`). Per ADR 0022 Phase 2 this
    /// requires the caller to hold `ai.tools.write` in addition to
    /// `ai.chat`.
    #[default]
    Auto,
    /// Advertise no tools — the model cannot issue tool calls.
    None,
    /// `Auto` plus tools dynamically discovered from
    /// `com.nexus.mcp.host::list_servers` / `list_tools`. Each MCP
    /// tool is exposed as `mcp__<server>__<tool>` and proxied to
    /// `call_tool`. Discovery runs once per `stream_chat` call (no
    /// cache); a server that fails to enumerate is skipped with a
    /// warning so the chat call still proceeds. Per ADR 0022
    /// Phase 2 this requires `ai.tools.write` and `ai.tools.mcp`.
    #[serde(rename = "auto_with_mcp")]
    AutoWithMcp,
    /// `Auto`, restricted to read-only built-ins (`read_file`,
    /// `search_forge`, `list_backlinks`, `git_log`). Surfaces a
    /// productive subset of the registry to callers that hold
    /// `ai.chat` but not `ai.tools.write`. Per ADR 0022 Phase 2.
    #[serde(rename = "auto_readonly")]
    AutoReadOnly,
}

/// Map a parsed [`AiToolPolicy`] to the additional caller caps
/// required for the call to land. Shared by the bootstrap-side
/// `add_cap_requirement_fn` registrations for `stream_chat` and
/// `propose_tool_calls` (ADR 0022 Phase 2). The unconditional
/// `Capability::AiChat` requirement is registered separately via
/// `add_cap_requirement` (Phase 1) — this function returns only the
/// args-aware deltas.
#[must_use]
pub fn extra_caps_for_policy(policy: AiToolPolicy) -> Vec<nexus_kernel::Capability> {
    use nexus_kernel::Capability;
    match policy {
        AiToolPolicy::None | AiToolPolicy::AutoReadOnly => Vec::new(),
        AiToolPolicy::Auto => vec![Capability::AiToolsWrite],
        AiToolPolicy::AutoWithMcp => {
            vec![Capability::AiToolsWrite, Capability::AiToolsMcp]
        }
    }
}

/// Args for `com.nexus.ai::stream_chat` (handler id `6`).
///
/// Mirrors the ad-hoc shape the handler decoded historically. The
/// engine continues to accept the legacy raw `{ messages, system,
/// session_id }` JSON object so existing chat callers don't break;
/// new optional fields (`mode`, `tools`, `max_tokens`, `stop`, `trim`)
/// drive the BL-010/011/034 surfaces.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct AiStreamChatArgs {
    /// Conversation history. Same shape as `stream_ask` so callers can
    /// share message-builder code across the two handlers.
    pub messages: Vec<AiStreamAskMessage>,
    /// Optional system prompt forwarded to the provider.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub system: Option<String>,
    /// Optional caller-provided session identifier. When `None` the
    /// handler generates a UUID v4 and echoes it on every
    /// `com.nexus.ai.stream_*` bus event.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    /// Engine mode. Omit for the default `chat` (back-compat).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mode: Option<AiStreamChatMode>,
    /// Tool-advertisement policy. Omit for the default `auto`.
    /// `mode=complete` forces this to `none` regardless of the
    /// caller's value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tools: Option<AiToolPolicy>,
    /// Optional generation cap, passed through to providers that
    /// honour it (Anthropic + `OpenAI`). Currently advisory: the
    /// engine does not enforce a hard truncation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<u32>,
    /// Stop sequences. After the provider returns, the engine
    /// truncates the text at the earliest occurrence of any of these
    /// strings (post-processing only — not a wire-level provider
    /// extension).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stop: Option<Vec<String>>,
    /// When `true` and `mode=complete`, post-process the suggested
    /// text: strip a leading copy of the prompt's tail (prompt-echo)
    /// and clip at the last natural break (newline or sentence
    /// boundary). Ignored for `mode=chat`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trim: Option<bool>,
    /// BL-037 — surface tag recorded in the activity timeline
    /// (`chat`, `cmdi`, `ghost`, `complete`, `enrich`, `other`). Omit
    /// for the default heuristic (`complete` if `mode=complete`,
    /// otherwise `chat`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub surface: Option<String>,
}

// ─── G7 — propose_tool_calls (no-execute single-turn) ─────────────────────

/// One tool call inside an [`AiChatTurn::Assistant`] turn — the rich,
/// linkage-preserving form used by the Phase 5.5 (2c) multi-turn
/// `propose_tool_calls` path. Mirrors the model's native `tool_use`
/// block: `id` is the provider-issued handle the matching
/// [`AiChatTurn::ToolResult`] echoes back so the model can correlate a
/// result with the call that produced it.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct AiTurnToolCall {
    /// Provider-issued tool-use id (e.g. `toolu_…`). The matching
    /// `tool_result` turn echoes this back.
    pub id: String,
    /// Tool name as advertised in the registry.
    pub name: String,
    /// Decoded tool arguments the model emitted.
    #[cfg_attr(feature = "ts-export", ts(type = "unknown"))]
    pub input: serde_json::Value,
}

/// One conversation turn on the `propose_tool_calls` wire that
/// preserves the assistant `tool_use` ↔ `tool_result` linkage a plain
/// text-only [`AiStreamAskMessage`] cannot. Phase 5.5 (2c): the agent
/// loop sends the whole conversation as `turns` so the provider sees a
/// real multi-turn exchange instead of a restated-goal blob. Mirrors
/// [`crate::provider::ChatTurn`] across the IPC boundary.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum AiChatTurn {
    /// A user message — plain text.
    User {
        /// The user's text.
        content: String,
    },
    /// An assistant message that may carry text and/or tool calls.
    Assistant {
        /// Assistant narration; empty when the model emitted only
        /// tool-use blocks.
        #[serde(default)]
        content: String,
        /// Tool calls the model issued, in order. Empty for a
        /// text-only assistant turn.
        #[serde(default)]
        tool_calls: Vec<AiTurnToolCall>,
    },
    /// The dispatcher's reply to one assistant tool call.
    ToolResult {
        /// The [`AiTurnToolCall::id`] this answers.
        tool_use_id: String,
        /// Stringified tool result (or the error message when
        /// `is_error`).
        content: String,
        /// `true` when the tool returned an error; providers surface
        /// this distinctly from a successful result.
        #[serde(default)]
        is_error: bool,
    },
}

/// Args for `com.nexus.ai::propose_tool_calls`.
///
/// Single-turn entry point that runs the provider once with the
/// registry advertised, returns the model's `tool_use` blocks
/// **without executing any of them**, and exits. Unlike
/// `stream_chat` there is no dispatch loop: the caller is
/// responsible for invoking the returned tool calls (or not).
///
/// Used by `nexus-agent` (ADR 0023) to derive a [`Plan`] from
/// provider tool-use blocks instead of free-form JSON; preserves
/// the agent's pre-execution approval flow.
///
/// [`Plan`]: nexus_agent::Plan
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct AiProposeArgs {
    /// Conversation messages — same shape as `stream_chat`. Most
    /// callers pass a single user turn carrying the goal. Legacy,
    /// text-only path: superseded by `turns` when that is non-empty.
    pub messages: Vec<AiStreamAskMessage>,
    /// Phase 5.5 (2c) — rich, linkage-preserving conversation turns.
    /// When present and non-empty this **supersedes** `messages`: the
    /// handler builds provider-native [`crate::provider::ChatTurn`]s
    /// directly from it, so assistant `tool_use` blocks and their
    /// `tool_result` replies reach the model intact. Absent / empty
    /// keeps the legacy text-only `messages` path.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub turns: Vec<AiChatTurn>,
    /// Optional system prompt forwarded to the provider verbatim.
    /// Unlike `stream_chat`, this handler does NOT prepend the host
    /// system-prompt floor — agent planning prompts are caller-owned.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub system: Option<String>,
    /// Tool-advertisement policy. Omit for the default `auto`. The
    /// policy controls which schemas the model sees; the handler
    /// returns whatever tool calls the model requests.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tools: Option<AiToolPolicy>,
}

/// One element of [`AiProposeReply::tool_calls`] — a model
/// tool-use block whose name was successfully resolved to an IPC
/// dispatch triple via `crate::tools::dispatch_target`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct AiProposedToolCall {
    /// Provider-issued id (e.g. `toolu_…` for Anthropic).
    pub id: String,
    /// Tool name as advertised in the registry.
    pub name: String,
    /// Reverse-DNS plugin id resolved by `dispatch_target`.
    pub target_plugin_id: String,
    /// Command id within the target plugin.
    pub command_id: String,
    /// Args ready to hand to `ipc_call`. May differ from the model's
    /// raw input when the tool requires reshape (e.g. `write_file`'s
    /// `content` → `bytes`).
    #[cfg_attr(feature = "ts-export", ts(type = "unknown"))]
    pub args: serde_json::Value,
}

/// One element of [`AiProposeReply::unmapped_tool_calls`] — a tool
/// call the model issued under a name `dispatch_target` didn't
/// recognise. Surfaced to callers for diagnostics rather than
/// silently dropped.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct AiUnmappedToolCall {
    /// Provider-issued id.
    pub id: String,
    /// Name the model used.
    pub name: String,
    /// Raw input the model emitted.
    #[cfg_attr(feature = "ts-export", ts(type = "unknown"))]
    pub input: serde_json::Value,
    /// Why mapping failed (unknown tool, malformed mcp name, etc.).
    pub error: String,
}

/// Reply for `com.nexus.ai::propose_tool_calls`.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct AiProposeReply {
    /// Aggregated text the model produced this turn — narration the
    /// model emitted alongside (or instead of) tool calls.
    pub text: String,
    /// Tool calls that mapped cleanly to an IPC dispatch triple.
    pub tool_calls: Vec<AiProposedToolCall>,
    /// Tool calls the mapper rejected. Empty in the happy path.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub unmapped_tool_calls: Vec<AiUnmappedToolCall>,
}

// ─── BL-037 — activity timeline IPC ────────────────────────────────────────

/// Args for `com.nexus.ai::activity_list`. Currently a unit shape;
/// kept as a struct so future cursor / pagination fields can land
/// without an IPC drift event.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct AiActivityListArgs {
    /// Maximum number of entries to return, newest first. Omit for
    /// "all entries" (currently capped by the on-disk log itself).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<u32>,
}

/// Result for `com.nexus.ai::activity_list`. Order is
/// newest-first so the shell can render without re-sorting.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct AiActivityListResult {
    /// Recorded entries (newest first).
    pub entries: Vec<nexus_types::activity::ActivityEntry>,
}

// ── BL-116 — generate_docs ─────────────────────────────────────────────────

/// Args for `com.nexus.ai::generate_docs` (handler id `22`).
///
/// Either `symbol_id` (preferred when available — addresses a row in
/// the BL-114 `code_symbols` table directly) or the `path` + `name`
/// pair. When both are supplied `symbol_id` wins. Returning an
/// unresolved-symbol error rather than guessing keeps the contract
/// predictable for agent-driven callers.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct AiGenerateDocsArgs {
    /// Row id in the `code_symbols` table. Preferred when known.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub symbol_id: Option<i64>,
    /// Forge-relative path to the source file. Used with `name` when
    /// `symbol_id` is absent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    /// Identifier as it appears in source. Case-sensitive.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Doc-comment style hint (`"rustdoc"` / `"jsdoc"` / `"godoc"` /
    /// `"docstring"`). When `None` the handler picks a default per
    /// the symbol's language (rustdoc for Rust, JSDoc for TS/JS,
    /// godoc for Go, Python docstrings for Python).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub style: Option<String>,
}

/// Reply for `com.nexus.ai::generate_docs`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct AiGenerateDocsReply {
    /// Generated docblock — already wrapped in the chosen comment
    /// syntax (rustdoc `///` lines, JSDoc block comments, godoc `//`,
    /// Python `"""…"""`). Caller can splice this directly above the
    /// symbol's source range.
    pub docblock: String,
    /// Resolved symbol's row id, echoed so the caller can apply the
    /// docblock without re-resolving.
    pub symbol_id: i64,
    /// Resolved language label (matches `StorageSymbolRow.language`).
    pub language: String,
    /// Resolved kind (`"function"` / `"struct"` / …).
    pub kind: String,
    /// Resolved symbol name.
    pub name: String,
    /// Resolved forge-relative path.
    pub path: String,
    /// 1-based starting line where the docblock should be inserted
    /// (the symbol's `line_start`). Caller writes the docblock
    /// immediately before this line.
    pub insert_line: u32,
    /// `true` when the BL-114 index can't supply a full 1-hop call
    /// graph; the prompt used parent + sibling symbols as a proxy.
    /// Mirrors BL-115's `degraded` flag — agents can downweight
    /// confidence.
    pub degraded: bool,
    /// Human-readable note about what's missing.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub degraded_reason: Option<String>,
}

// ── BL-128 close — entity_recall (FAISS-backed) ──────────────────────────────

/// Args for `com.nexus.ai::entity_recall` (handler 23).
///
/// Embeds the `query` through the configured provider, queries the
/// shared chunk vectorstore, filters hits to files under
/// `entities/`, and resolves each surviving stem back through
/// `com.nexus.storage::entity_get`. When no embedder is configured
/// the call returns an error and the agent / CLI is expected to
/// fall back to the substring-ranking `com.nexus.storage::entity_search`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct EntityRecallArgs {
    /// Free-text query. The embedding pass treats this verbatim — the
    /// agent typically sends the session goal here.
    pub query: String,
    /// Maximum entity hits to return. Defaults to 5 when absent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<u32>,
}

/// One hit returned by `entity_recall`. Mirrors
/// `nexus_storage::ipc::EntitySearchHitRow` so callers can union the
/// substring and semantic paths under a single rendering pass — the
/// `score` units differ (cosine similarity vs. the substring
/// 0..100 band), but agent / CLI consumers only need an ordering.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct EntityRecallHitRow {
    /// Canonical entity id (file stem).
    pub id: String,
    /// `entity_type` declared in frontmatter.
    pub entity_type: String,
    /// One-line description (frontmatter `description:` or fallback
    /// first body paragraph, capped at 240 chars).
    pub description: String,
    /// Forge-relative path of the entity markdown file.
    pub relpath: String,
    /// Cosine similarity of the best-matching chunk within the entity.
    pub score: f32,
}

/// Return type for `com.nexus.ai::entity_recall`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct EntityRecallResult {
    /// Entity hits ordered by descending score.
    pub results: Vec<EntityRecallHitRow>,
}

// ── BL-129 close — enrich_entity / infer_entity_relations ────────────────────

/// Args for `com.nexus.ai::enrich_entity` (handler 24).
///
/// Reads the entity through `com.nexus.storage::entity_get`, gathers
/// existing-relation context, optionally runs RAG over the rest of
/// the forge for supporting snippets, asks the AI provider for an
/// expanded description, and (unless `dry_run`) atomically rewrites
/// the entity through `com.nexus.storage::entity_upsert`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct EnrichEntityArgs {
    /// Canonical entity id or alias.
    pub entity_id: String,
    /// Minimum description length below which enrichment runs. When
    /// the existing description is at or above this many characters
    /// the handler short-circuits and reports `skipped: true`.
    /// Defaults to `80` when absent — matches the Dream-Cycle spec.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub min_description_chars: Option<u32>,
    /// When `true`, the handler computes the proposed description
    /// but does not write it back. The proposed text is still
    /// included in the response so callers can preview.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dry_run: Option<bool>,
}

/// Reply for `com.nexus.ai::enrich_entity`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct EnrichEntityResult {
    /// Canonical entity id (after alias resolution).
    pub entity_id: String,
    /// Description present before the call (empty when the entity had
    /// none).
    pub original_description: String,
    /// AI-generated description. Empty when `skipped: true`.
    pub new_description: String,
    /// `true` when the original description already met the length
    /// threshold and the AI was not invoked.
    pub skipped: bool,
    /// `true` when the new description was written to disk; `false`
    /// when `dry_run` or `skipped`.
    pub applied: bool,
}

/// Args for `com.nexus.ai::infer_entity_relations` (handler 25).
///
/// Looks up the entity, gathers similar entities via `entity_recall`,
/// asks the AI provider for proposed new relations, writes the
/// surviving proposals back through `com.nexus.storage::entity_upsert`
/// at a fixed `confidence: 0.5` so a future cycle's decay treats them
/// as low-trust.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct InferEntityRelationsArgs {
    /// Canonical entity id or alias to propose new relations for.
    pub entity_id: String,
    /// Maximum number of candidate relations to keep from the model's
    /// response. Defaults to `3`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_proposals: Option<u32>,
    /// When `true`, the handler computes the proposals but does not
    /// write them back. The proposals are still included in the reply.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dry_run: Option<bool>,
}

/// One proposed relation in [`InferEntityRelationsResult::proposals`].
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct InferredRelationRow {
    /// Target entity canonical id (after resolution).
    pub target: String,
    /// Relation kind, normalised against the canonical vocabulary.
    #[serde(rename = "type")]
    pub kind: String,
    /// Confidence assigned to the proposal. Always `0.5` for the
    /// thin close-out; future iterations may vary per proposal.
    pub confidence: f32,
}

/// Reply for `com.nexus.ai::infer_entity_relations`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct InferEntityRelationsResult {
    /// Canonical entity id (after alias resolution).
    pub entity_id: String,
    /// Proposals that survived target-existence + duplicate-filter
    /// checks. Empty when the model returned nothing usable.
    pub proposals: Vec<InferredRelationRow>,
    /// `true` when the proposals were written back; `false` when
    /// `dry_run` was set or no proposals survived filtering.
    pub applied: bool,
}

// ─── com.nexus.ai::predict (BL-139) ─────────────────────────────────────────
//
// Per-keystroke edit prediction. Caller supplies the cursor split
// (`prefix` / `suffix`), the file's language, and the on-disk path
// for the audit trail. The handler routes to the configured AI
// provider — Ollama in fill-in-middle mode by default, OpenAI /
// Anthropic via a chat-shaped FIM prompt as a fallback.
//
// The returned `completion` is plain text ready to insert at the
// cursor. The handler trims leading whitespace at the seam; the
// editor is responsible for any further normalisation (e.g. ignoring
// a completion that exactly matches the next characters of the
// suffix).

/// Args for `com.nexus.ai::predict` (handler id `26`).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct AiPredictArgs {
    /// Text BEFORE the cursor. Trimmed to a per-call budget upstream
    /// (the BL-139 editor extension caps at ~200 tokens worth).
    pub prefix: String,
    /// Text AFTER the cursor. Smaller than the prefix budget — most
    /// models weight prefix more heavily in FIM mode.
    pub suffix: String,
    /// Source language hint (`rust`, `typescript`, `python`, `markdown`,
    /// …). The Ollama FIM path ignores this (the model uses the
    /// surrounding tokens); the chat-fallback path includes it in the
    /// system prompt so the model frames the completion correctly.
    pub language: String,
    /// Forge-relative path the prediction is happening in. Logged but
    /// not otherwise used today — included so the handler can emit
    /// per-file activity entries if a future revision wants them.
    pub file_path: String,
    /// Maximum tokens the model may generate. Defaults to 64 when
    /// unset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<u32>,
}

/// Reply for `com.nexus.ai::predict`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct AiPredictReply {
    /// The suggested continuation. Empty string when no useful
    /// completion was produced (rather than `None` — callers branch
    /// on length, not nullity).
    pub completion: String,
}

#[cfg(test)]
mod stream_chat_serde_tests {
    use super::*;

    #[test]
    fn chat_default_round_trip() {
        // Default chat shape — only the legacy fields are populated.
        let args = AiStreamChatArgs {
            messages: vec![AiStreamAskMessage {
                role: AiStreamAskRole::User,
                content: "hi".to_string(),
            }],
            system: Some("be terse".to_string()),
            session_id: None,
            mode: None,
            tools: None,
            max_tokens: None,
            stop: None,
            trim: None,
            surface: None,
        };
        let json = serde_json::to_value(&args).expect("ser");
        // Optional fields with `None` must not bloat the wire.
        let obj = json.as_object().expect("object");
        assert!(obj.contains_key("messages"));
        assert!(obj.contains_key("system"));
        assert!(!obj.contains_key("session_id"));
        assert!(!obj.contains_key("mode"));
        assert!(!obj.contains_key("tools"));
        assert!(!obj.contains_key("max_tokens"));
        assert!(!obj.contains_key("stop"));
        assert!(!obj.contains_key("trim"));
        assert!(!obj.contains_key("surface"));

        let back: AiStreamChatArgs = serde_json::from_value(json).expect("de");
        assert_eq!(back.messages.len(), 1);
        assert_eq!(back.system.as_deref(), Some("be terse"));
        assert!(back.mode.is_none());
        assert!(back.tools.is_none());
    }

    #[test]
    fn complete_with_stop_and_trim_round_trip() {
        let args = AiStreamChatArgs {
            messages: vec![AiStreamAskMessage {
                role: AiStreamAskRole::User,
                content: "complete this: The quick".to_string(),
            }],
            system: None,
            session_id: Some("sess-1".to_string()),
            mode: Some(AiStreamChatMode::Complete),
            tools: Some(AiToolPolicy::None),
            max_tokens: Some(64),
            stop: Some(vec!["\n\n".to_string(), "END".to_string()]),
            trim: Some(true),
            surface: Some("ghost".to_string()),
        };
        let json = serde_json::to_value(&args).expect("ser");
        // Snake-case mode + tool policy on the wire.
        assert_eq!(json["mode"], "complete");
        assert_eq!(json["tools"], "none");
        assert_eq!(json["max_tokens"], 64);
        assert_eq!(json["session_id"], "sess-1");

        let back: AiStreamChatArgs = serde_json::from_value(json).expect("de");
        assert_eq!(back.mode, Some(AiStreamChatMode::Complete));
        assert_eq!(back.tools, Some(AiToolPolicy::None));
        assert_eq!(back.max_tokens, Some(64));
        assert_eq!(
            back.stop.as_deref(),
            Some(&["\n\n".to_string(), "END".to_string()][..])
        );
        assert_eq!(back.trim, Some(true));
    }

    #[test]
    fn unknown_mode_string_errors() {
        let raw = serde_json::json!({
            "messages": [],
            "mode": "freestyle"
        });
        let res: Result<AiStreamChatArgs, _> = serde_json::from_value(raw);
        assert!(res.is_err(), "unknown mode must fail to deserialize");
    }
}
