//! Stable IPC arg/return types for the Phase 4 WI-36 pilot handler.
//!
//! This module hosts the authoritative contract for
//! `com.nexus.ai::stream_ask` (handler id `7`):
//!
//! - [`AiStreamAskArgs`]  — input
//! - [`AiStreamAskResult`] — final response on stream completion
//!
//! The streaming chunks themselves are published as `com.nexus.ai.stream_*`
//! bus events; only the final aggregated result crosses the IPC return value.
//!
//! Under the `ts-export` feature each type emits a TypeScript binding into
//! `packages/nexus-extension-api/src/generated/ipc/` and (via the
//! `nexus-bootstrap` harness) a JSON Schema into
//! `crates/nexus-bootstrap/schemas/ipc/`.
//!
//! See `docs/planning/PHASE-4-IMPLEMENTATION-PLAN.md` §3.1 and
//! `docs/ipc-schemas.md` for the generator design.

use serde::{Deserialize, Serialize};

#[cfg(feature = "ts-export")]
use schemars::JsonSchema;
#[cfg(feature = "ts-export")]
use ts_rs::TS;

/// Role of a participant in a chat conversation. Mirror of
/// [`crate::provider::Role`] for schema emission.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(export, export_to = "../../../packages/nexus-extension-api/src/generated/ipc/")
)]
#[serde(rename_all = "lowercase")]
pub enum AiStreamAskRole {
    /// System-level instructions.
    System,
    /// User input.
    User,
    /// Assistant response.
    Assistant,
}

/// One message in a chat conversation. Mirror of
/// [`crate::provider::ChatMessage`].
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(export, export_to = "../../../packages/nexus-extension-api/src/generated/ipc/")
)]
pub struct AiStreamAskMessage {
    /// The role of the message sender.
    pub role: AiStreamAskRole,
    /// Text content of the message.
    pub content: String,
}

/// Args for `com.nexus.ai::stream_ask` (handler id `7`).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(export, export_to = "../../../packages/nexus-extension-api/src/generated/ipc/")
)]
pub struct AiStreamAskArgs {
    /// Conversation history. The handler extracts the last `user` message as
    /// the retrieval question; system and assistant turns are forwarded to
    /// the chat provider verbatim.
    pub messages: Vec<AiStreamAskMessage>,
    /// Optional caller-provided session identifier. When `None` the handler
    /// generates a UUID v4. The id is echoed back in every
    /// `com.nexus.ai.stream_*` bus event so callers can demux concurrent
    /// streams.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    /// Maximum number of RAG source chunks to retrieve. Omit for the default
    /// of 5.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<u32>,
}

/// One retrieved source chunk used to ground the answer. Mirror of
/// [`crate::vectorstore::ChunkMatch`].
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(export, export_to = "../../../packages/nexus-extension-api/src/generated/ipc/")
)]
pub struct AiStreamAskSource {
    /// Path of the source file.
    pub file_path: String,
    /// Identifier of the originating block.
    pub block_id: u64,
    /// Textual content of the chunk.
    pub chunk_text: String,
    /// Cosine similarity score (higher is more relevant).
    pub score: f32,
}

/// Return type for `com.nexus.ai::stream_ask`. Mirrors the final
/// `stream_done` event payload and is what the IPC call resolves to when
/// the stream completes.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(export, export_to = "../../../packages/nexus-extension-api/src/generated/ipc/")
)]
pub struct AiStreamAskResult {
    /// Session id — matches the `session_id` on every `stream_chunk`
    /// event. Generated by the handler when the caller omitted it.
    pub session_id: String,
    /// Full aggregated assistant response.
    pub text: String,
    /// RAG sources that grounded the answer, in retrieval order.
    pub sources: Vec<AiStreamAskSource>,
}
