import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useThemeStore, THEME_PLUGIN_ID } from '../../../stores/themeStore'
import { useThemePickerStore } from './themePickerStore'
import { getPickerApi } from './pickerRuntime'

// ── Variable group manifest ───────────────────────────────────────────────────

interface VarEntry {
  key: string
  label: string
  hint?: string
}

interface VarGroup {
  label: string
  vars: VarEntry[]
}

const BUILDER_GROUPS: VarGroup[] = [
  {
    label: 'Surfaces',
    vars: [
      { key: '--nx-bg-primary',   label: 'Content background', hint: 'Editor, active tab' },
      { key: '--nx-bg-secondary', label: 'Chrome / sidebar',   hint: 'Sidebar, tab bar, panels' },
      { key: '--nx-bg-tertiary',  label: 'Hover surface',      hint: 'Row hover, inactive items' },
      { key: '--nx-bg-elevated',  label: 'Elevated surface',   hint: 'Menus, dropdowns, dialogs' },
    ],
  },
  {
    label: 'Accent',
    vars: [
      { key: '--nx-color-primary',       label: 'Primary accent' },
      { key: '--nx-color-primary-light', label: 'Accent — light', hint: 'Hover state' },
      { key: '--nx-color-primary-dark',  label: 'Accent — dark',  hint: 'Active / pressed state' },
      { key: '--nx-color-secondary',     label: 'Secondary accent' },
    ],
  },
  {
    label: 'Text',
    vars: [
      { key: '--nx-text-primary',   label: 'Primary text' },
      { key: '--nx-text-secondary', label: 'Secondary text' },
      { key: '--nx-text-tertiary',  label: 'Tertiary text' },
      { key: '--nx-text-muted',     label: 'Muted text' },
    ],
  },
  {
    label: 'Editor',
    vars: [
      { key: '--nx-editor-bg',           label: 'Canvas background' },
      { key: '--nx-editor-font-family',  label: 'Canvas font',     hint: 'CSS font-family stack' },
      { key: '--nx-prose-heading-color', label: 'Heading colour' },
      { key: '--nx-prose-link-color',    label: 'Link colour' },
      { key: '--nx-callout-bg',          label: 'Callout background' },
      { key: '--nx-callout-border',      label: 'Callout border' },
    ],
  },
  {
    label: 'Syntax',
    vars: [
      { key: '--nx-syntax-keyword',  label: 'Keyword' },
      { key: '--nx-syntax-string',   label: 'String' },
      { key: '--nx-syntax-comment',  label: 'Comment' },
      { key: '--nx-syntax-function', label: 'Function / method' },
      { key: '--nx-syntax-number',   label: 'Number' },
      { key: '--nx-syntax-type',     label: 'Type' },
    ],
  },
]

// ── Utilities ─────────────────────────────────────────────────────────────────

function isHexColor(v: string): boolean {
  return /^#[0-9a-fA-F]{3,8}$/.test(v.trim())
}

function toSixDigitHex(hex: string): string {
  const h = hex.trim()
  return /^#[0-9a-fA-F]{3}$/.test(h)
    ? '#' + h[1] + h[1] + h[2] + h[2] + h[3] + h[3]
    : h
}

function generateToml(
  name: string,
  author: string,
  baseId: string,
  overrides: Record<string, string>,
): string {
  const n = name.trim() || 'my-theme'
  const a = author.trim() || 'Unknown'
  const varLines =
    Object.entries(overrides)
      .sort(([ka], [kb]) => ka.localeCompare(kb))
      .map(([k, v]) => `"${k}" = "${v.replace(/"/g, '\\"')}"`)
      .join('\n') || '# No overrides yet — adjust variables above.'

  return `# Generated by Nexus Theme Builder — base: ${baseId}
# Save as  ~/.nexus/themes/${n.toLowerCase().replace(/\s+/g, '-')}/NEXUS.toml  to install.

[theme]
name             = "${n}"
version          = "0.1.0"
author           = "${a}"
description      = "Custom theme based on ${baseId}"
license          = "MIT"
category         = "custom"
supports         = ["light", "dark"]

[variables]
${varLines}
`
}

function useDebounce<T>(value: T, delay: number): T {
  const [debounced, setDebounced] = useState<T>(value)
  useEffect(() => {
    const t = setTimeout(() => setDebounced(value), delay)
    return () => clearTimeout(t)
  }, [value, delay])
  return debounced
}

// ── ThemeBuilderPanel ─────────────────────────────────────────────────────────

export function ThemeBuilderPanel() {
  const availableThemes    = useThemeStore((s) => s.availableThemes)
  const activeThemeId      = useThemeStore((s) => s.activeThemeId)
  const builderBaseThemeId = useThemePickerStore((s) => s.builderBaseThemeId)
  const setBuilderBaseId   = useThemePickerStore((s) => s.setBuilderBaseThemeId)
  const builderOverrides   = useThemePickerStore((s) => s.builderOverrides)
  const themeName          = useThemePickerStore((s) => s.builderThemeName)
  const themeAuthor        = useThemePickerStore((s) => s.builderThemeAuthor)
  const setOverride        = useThemePickerStore((s) => s.setBuilderOverride)
  const clearOverride      = useThemePickerStore((s) => s.clearBuilderOverride)
  const resetOverrides     = useThemePickerStore((s) => s.resetBuilderOverrides)
  const setThemeName       = useThemePickerStore((s) => s.setBuilderThemeName)
  const setThemeAuthor     = useThemePickerStore((s) => s.setBuilderThemeAuthor)

  // Effective base: explicit selection or fall back to currently active theme.
  const effectiveBaseId = builderBaseThemeId ?? activeThemeId ?? ''

  // Clean base-theme variables (no overrides, no snippets) used as
  // reference values and row placeholders.
  const [baseVars, setBaseVars]       = useState<Record<string, string>>({})
  const [loadingBase, setLoadingBase] = useState(false)

  // Fetch clean base variables whenever the effective base changes.
  useEffect(() => {
    if (!effectiveBaseId) return
    let cancelled = false
    setLoadingBase(true)
    void getPickerApi()
      .kernel.invoke<Record<string, string>>(THEME_PLUGIN_ID, 'compute_variables', {
        theme_id: effectiveBaseId,
        enabled_snippets: [],
      })
      .then((vars) => { if (!cancelled) { setBaseVars(vars); setLoadingBase(false) } })
      .catch(() => { if (!cancelled) setLoadingBase(false) })
    return () => { cancelled = true }
  }, [effectiveBaseId])

  // When the user selects a different base theme: apply it so the whole shell
  // repaints to that theme, then fetch its clean variables for row placeholders.
  const handleBaseChange = useCallback(
    async (id: string) => {
      setBuilderBaseId(id)
      setLoadingBase(true)
      const api = getPickerApi()
      // Apply theme + fetch its clean vars in parallel.
      const [, vars] = await Promise.all([
        api.kernel.invoke(THEME_PLUGIN_ID, 'apply_theme', { id }),
        api.kernel.invoke<Record<string, string>>(THEME_PLUGIN_ID, 'compute_variables', {
          theme_id: id,
          enabled_snippets: [],
        }),
      ])
      setBaseVars(vars)
      setLoadingBase(false)
      // Re-apply existing overrides on top of the new base so the preview
      // doesn't lose the user's in-progress work.
      const current = useThemePickerStore.getState().builderOverrides
      if (Object.keys(current).length > 0) {
        await api.kernel.invoke(THEME_PLUGIN_ID, 'set_plugin_overrides', {
          overrides: current,
        })
      }
    },
    [setBuilderBaseId],
  )

  // Debounce overrides → kernel (500 ms).
  const debouncedOverrides = useDebounce(builderOverrides, 500)
  useEffect(() => {
    void getPickerApi().kernel.invoke(THEME_PLUGIN_ID, 'set_plugin_overrides', {
      overrides: debouncedOverrides,
    })
  }, [debouncedOverrides])

  const [applied, setApplied] = useState(false)
  const [copied, setCopied]   = useState(false)
  const [saved, setSaved]     = useState(false)

  const handleApplyNow = useCallback(async () => {
    await getPickerApi().kernel.invoke(THEME_PLUGIN_ID, 'set_plugin_overrides', {
      overrides: builderOverrides,
    })
    setApplied(true)
    setTimeout(() => setApplied(false), 2000)
  }, [builderOverrides])

  const handleReset = useCallback(async () => {
    resetOverrides()
    await getPickerApi().kernel.invoke(THEME_PLUGIN_ID, 'set_plugin_overrides', {
      overrides: {},
    })
  }, [resetOverrides])

  const tomlOutput = useMemo(
    () => generateToml(themeName, themeAuthor, effectiveBaseId, builderOverrides),
    [themeName, themeAuthor, effectiveBaseId, builderOverrides],
  )

  const handleCopyToml = useCallback(() => {
    void navigator.clipboard.writeText(tomlOutput).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }, [tomlOutput])

  const handleSaveToDisk = useCallback(async () => {
    const api = getPickerApi()
    const path = await api.platform.dialog.saveFile({
      title: 'Save Theme Manifest',
      defaultPath: 'NEXUS.toml',
      filters: [{ name: 'Nexus Theme Manifest', extensions: ['toml'] }],
    })
    if (!path) return
    // Create the parent directory in case the user navigated to a new
    // folder (e.g. ~/.nexus/themes/<id>/ which doesn't exist yet).
    const sep = path.includes('/') ? '/' : '\\'
    const dir = path.substring(0, path.lastIndexOf(sep))
    if (dir) await api.platform.fs.mkdir(dir, { recursive: true })
    await api.platform.fs.writeText(path, tomlOutput)
    setSaved(true)
    setTimeout(() => setSaved(false), 3000)
  }, [tomlOutput])

  const hasOverrides = Object.keys(builderOverrides).length > 0

  // Name of the currently selected base theme for display.
  const baseThemeName = useMemo(
    () => availableThemes.find((t) => t.id === effectiveBaseId)?.name as string | undefined,
    [availableThemes, effectiveBaseId],
  )

  return (
    <div style={{ display: 'flex', flexDirection: 'column', flex: 1, overflow: 'hidden' }}>
      {/* ── Scrollable editor ── */}
      <div style={{ flex: 1, overflowY: 'auto', padding: '4px 0' }}>

        {/* Base theme selector */}
        <div
          style={{
            padding: '10px 16px',
            borderBottom: '1px solid var(--background-modifier-border)',
          }}
        >
          <label style={{ ...LABEL_STYLE, flexDirection: 'row', alignItems: 'center', gap: 8 }}>
            <span style={{ flexShrink: 0, width: 80 }}>Base theme</span>
            <select
              value={effectiveBaseId}
              onChange={(e) => void handleBaseChange(e.target.value)}
              disabled={loadingBase || availableThemes.length === 0}
              style={{
                flex: 1,
                background: 'var(--background-primary)',
                border: '1px solid var(--background-modifier-border)',
                borderRadius: 'var(--radius-s)',
                color: 'var(--text-normal)',
                fontFamily: 'var(--font-interface)',
                fontSize: 12,
                padding: '5px 8px',
                outline: 0,
                cursor: loadingBase ? 'wait' : 'pointer',
              }}
            >
              {availableThemes.map((t) => (
                <option key={t.id} value={t.id}>
                  {typeof t.name === 'string' ? t.name : t.id}
                </option>
              ))}
            </select>
            {loadingBase && (
              <span
                style={{
                  fontFamily: 'var(--font-interface)',
                  fontSize: 11,
                  color: 'var(--text-faint)',
                  flexShrink: 0,
                }}
              >
                Loading…
              </span>
            )}
          </label>
          {baseThemeName && (
            <p
              style={{
                fontFamily: 'var(--font-interface)',
                fontSize: 11,
                color: 'var(--text-faint)',
                marginTop: 4,
              }}
            >
              Overrides stack on top of <em>{baseThemeName}</em>. Changing the base applies
              that theme immediately so you can see it as your starting point.
            </p>
          )}
        </div>

        {/* Theme identity inputs */}
        <div
          style={{
            padding: '10px 16px',
            display: 'grid',
            gridTemplateColumns: '1fr 1fr',
            gap: 8,
            borderBottom: '1px solid var(--background-modifier-border)',
          }}
        >
          <label style={LABEL_STYLE}>
            Theme name
            <input
              type="text"
              value={themeName}
              onChange={(e) => setThemeName(e.target.value)}
              placeholder="my-theme"
              style={TEXT_INPUT_STYLE}
            />
          </label>
          <label style={LABEL_STYLE}>
            Author
            <input
              type="text"
              value={themeAuthor}
              onChange={(e) => setThemeAuthor(e.target.value)}
              placeholder="Your name"
              style={TEXT_INPUT_STYLE}
            />
          </label>
        </div>

        {/* Variable groups */}
        {BUILDER_GROUPS.map((group) => (
          <VariableGroup
            key={group.label}
            group={group}
            baseVars={baseVars}
            loadingBase={loadingBase}
            overrides={builderOverrides}
            onSet={setOverride}
            onClear={clearOverride}
          />
        ))}

        {/* TOML export */}
        <section style={{ borderTop: '1px solid var(--background-modifier-border)', padding: '10px 16px' }}>
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              marginBottom: 6,
            }}
          >
            <span
              style={{
                fontFamily: 'var(--font-interface)',
                fontSize: 11,
                fontWeight: 600,
                color: 'var(--text-muted)',
                textTransform: 'uppercase',
                letterSpacing: '0.06em',
              }}
            >
              Export TOML
            </span>
            <div style={{ display: 'flex', gap: 6 }}>
              <button
                onClick={handleCopyToml}
                style={{
                  ...GHOST_BTN_STYLE,
                  color: copied ? 'var(--interactive-accent)' : 'var(--text-muted)',
                }}
              >
                {copied ? 'Copied ✓' : 'Copy'}
              </button>
              <button
                onClick={() => void handleSaveToDisk()}
                style={{
                  ...GHOST_BTN_STYLE,
                  color: saved ? 'var(--interactive-accent)' : 'var(--text-muted)',
                }}
              >
                {saved ? 'Saved ✓' : 'Save to disk'}
              </button>
            </div>
          </div>
          <textarea
            readOnly
            value={tomlOutput}
            spellCheck={false}
            style={{
              width: '100%',
              height: 140,
              resize: 'none',
              background: 'var(--background-primary)',
              border: '1px solid var(--background-modifier-border)',
              borderRadius: 'var(--radius-s)',
              color: 'var(--text-muted)',
              fontFamily: 'var(--font-monospace)',
              fontSize: 11,
              lineHeight: 1.55,
              padding: '8px 10px',
              outline: 0,
              boxSizing: 'border-box',
            }}
          />
          <p
            style={{
              fontFamily: 'var(--font-interface)',
              fontSize: 11,
              color: 'var(--text-faint)',
              marginTop: 4,
            }}
          >
            Save as{' '}
            <code style={{ fontFamily: 'var(--font-monospace)' }}>
              ~/.nexus/themes/&lt;id&gt;/NEXUS.toml
            </code>{' '}
            — Nexus hot-reloads themes automatically.
          </p>
        </section>
      </div>

      {/* ── Footer ── */}
      <div
        style={{
          borderTop: '1px solid var(--background-modifier-border)',
          padding: '10px 16px',
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          flexShrink: 0,
        }}
      >
        <span
          style={{
            fontFamily: 'var(--font-interface)',
            fontSize: 12,
            color: 'var(--text-faint)',
            flex: 1,
          }}
        >
          {hasOverrides
            ? `${Object.keys(builderOverrides).length} variable${Object.keys(builderOverrides).length === 1 ? '' : 's'} overridden · preview updates in ~500 ms`
            : 'No overrides — edit variables above to customise the base theme.'}
        </span>
        <button
          onClick={() => void handleReset()}
          disabled={!hasOverrides}
          style={{
            ...GHOST_BTN_STYLE,
            opacity: hasOverrides ? 1 : 0.4,
            cursor: hasOverrides ? 'pointer' : 'default',
          }}
        >
          Reset all
        </button>
        <button
          onClick={() => void handleApplyNow()}
          disabled={!hasOverrides}
          style={{
            background: hasOverrides ? 'var(--interactive-accent)' : 'var(--background-modifier-border)',
            color: hasOverrides ? 'var(--text-on-accent)' : 'var(--text-muted)',
            border: 0,
            borderRadius: 'var(--radius-s)',
            padding: '6px 14px',
            fontFamily: 'var(--font-interface)',
            fontSize: 12,
            fontWeight: 600,
            cursor: hasOverrides ? 'pointer' : 'default',
            transition: 'background 100ms',
          }}
        >
          {applied ? 'Applied ✓' : 'Apply now'}
        </button>
      </div>
    </div>
  )
}

// ── VariableGroup ─────────────────────────────────────────────────────────────

interface VariableGroupProps {
  group: VarGroup
  baseVars: Record<string, string>
  loadingBase: boolean
  overrides: Record<string, string>
  onSet(key: string, value: string): void
  onClear(key: string): void
}

function VariableGroup({
  group,
  baseVars,
  loadingBase,
  overrides,
  onSet,
  onClear,
}: VariableGroupProps) {
  const [open, setOpen] = useState(true)
  const overriddenCount = group.vars.filter((v) => overrides[v.key] !== undefined).length

  return (
    <section>
      <button
        onClick={() => setOpen((o) => !o)}
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          width: '100%',
          background: 'transparent',
          border: 0,
          borderBottom: '1px solid var(--background-modifier-border)',
          padding: '7px 16px',
          cursor: 'pointer',
          textAlign: 'left',
        }}
      >
        <span style={{ fontFamily: 'var(--font-interface)', fontSize: 11, color: 'var(--text-faint)', width: 10, flexShrink: 0 }}>
          {open ? '▾' : '▸'}
        </span>
        <span
          style={{
            fontFamily: 'var(--font-interface)',
            fontSize: 11,
            fontWeight: 600,
            color: 'var(--text-muted)',
            textTransform: 'uppercase',
            letterSpacing: '0.06em',
            flex: 1,
          }}
        >
          {group.label}
        </span>
        {overriddenCount > 0 && (
          <span
            style={{
              fontFamily: 'var(--font-interface)',
              fontSize: 10,
              color: 'var(--interactive-accent)',
              background: 'var(--background-modifier-active-hover, var(--interactive-accent-soft))',
              borderRadius: 'var(--radius-full, 9999px)',
              padding: '1px 6px',
            }}
          >
            {overriddenCount}
          </span>
        )}
      </button>

      {open && group.vars.map((entry) => (
        <VarRow
          key={entry.key}
          entry={entry}
          baseValue={baseVars[entry.key] ?? ''}
          loadingBase={loadingBase}
          override={overrides[entry.key]}
          onSet={onSet}
          onClear={onClear}
        />
      ))}
    </section>
  )
}

// ── VarRow ────────────────────────────────────────────────────────────────────

interface VarRowProps {
  entry: VarEntry
  /** Clean value from the selected base theme (no overrides, no snippets). */
  baseValue: string
  loadingBase: boolean
  override: string | undefined
  onSet(key: string, value: string): void
  onClear(key: string): void
}

function VarRow({ entry, baseValue, loadingBase, override, onSet, onClear }: VarRowProps) {
  const effectiveValue = override ?? baseValue
  const isHex = isHexColor(effectiveValue)
  const colorInputRef = useRef<HTMLInputElement | null>(null)
  const [hovered, setHovered] = useState(false)

  const handleTextChange = (raw: string) => {
    raw === '' ? onClear(entry.key) : onSet(entry.key, raw)
  }

  return (
    <div
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      style={{
        display: 'flex',
        alignItems: 'center',
        gap: 10,
        padding: '6px 16px',
        background: hovered ? 'var(--background-modifier-hover)' : 'transparent',
        transition: 'background 80ms',
      }}
    >
      {/* Colour swatch / picker trigger */}
      <div style={{ flexShrink: 0, position: 'relative' }}>
        <div
          title={isHex ? 'Click to open colour picker' : effectiveValue || '—'}
          onClick={() => isHex && colorInputRef.current?.click()}
          style={{
            width: 24,
            height: 24,
            borderRadius: 'var(--radius-s)',
            background: effectiveValue || 'var(--background-modifier-border)',
            border: '1px solid var(--background-modifier-border)',
            cursor: isHex ? 'pointer' : 'default',
            opacity: loadingBase && !override ? 0.4 : 1,
            transition: 'opacity 150ms',
          }}
        />
        {isHex && (
          <input
            ref={colorInputRef}
            type="color"
            value={toSixDigitHex(effectiveValue)}
            onChange={(e) => onSet(entry.key, e.target.value)}
            tabIndex={-1}
            style={{ position: 'absolute', opacity: 0, width: 0, height: 0, pointerEvents: 'none' }}
          />
        )}
      </div>

      {/* Label + hint */}
      <div style={{ width: 160, flexShrink: 0 }}>
        <div
          style={{
            fontFamily: 'var(--font-interface)',
            fontSize: 12,
            color: override !== undefined ? 'var(--text-normal)' : 'var(--text-muted)',
            fontWeight: override !== undefined ? 500 : 400,
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            whiteSpace: 'nowrap',
          }}
        >
          {entry.label}
        </div>
        {entry.hint && (
          <div
            style={{
              fontFamily: 'var(--font-interface)',
              fontSize: 10,
              color: 'var(--text-faint)',
              overflow: 'hidden',
              textOverflow: 'ellipsis',
              whiteSpace: 'nowrap',
            }}
          >
            {entry.hint}
          </div>
        )}
      </div>

      {/* Text input */}
      <input
        type="text"
        value={override ?? ''}
        placeholder={loadingBase ? 'loading…' : (baseValue || entry.key)}
        onChange={(e) => handleTextChange(e.target.value)}
        spellCheck={false}
        style={{
          flex: 1,
          minWidth: 0,
          background: 'var(--background-primary)',
          border: override !== undefined
            ? '1px solid var(--interactive-accent)'
            : '1px solid var(--background-modifier-border)',
          borderRadius: 'var(--radius-s)',
          color: 'var(--text-normal)',
          fontFamily: 'var(--font-monospace)',
          fontSize: 11,
          padding: '4px 7px',
          outline: 0,
        }}
      />

      {/* Clear override */}
      <button
        onClick={() => onClear(entry.key)}
        disabled={override === undefined}
        title="Clear override"
        aria-label={`Clear override for ${entry.label}`}
        style={{
          background: 'transparent',
          border: 0,
          color: 'var(--text-muted)',
          cursor: override !== undefined ? 'pointer' : 'default',
          fontSize: 13,
          lineHeight: 1,
          padding: '2px 4px',
          opacity: override !== undefined ? (hovered ? 1 : 0.5) : 0,
          transition: 'opacity 100ms',
          flexShrink: 0,
        }}
      >
        ×
      </button>
    </div>
  )
}

// ── Shared styles ─────────────────────────────────────────────────────────────

const LABEL_STYLE: React.CSSProperties = {
  display: 'flex',
  flexDirection: 'column',
  gap: 4,
  fontFamily: 'var(--font-interface)',
  fontSize: 11,
  color: 'var(--text-muted)',
}

const TEXT_INPUT_STYLE: React.CSSProperties = {
  background: 'var(--background-primary)',
  border: '1px solid var(--background-modifier-border)',
  borderRadius: 'var(--radius-s)',
  color: 'var(--text-normal)',
  fontFamily: 'var(--font-interface)',
  fontSize: 12,
  padding: '5px 8px',
  outline: 0,
}

const GHOST_BTN_STYLE: React.CSSProperties = {
  background: 'transparent',
  border: '1px solid var(--background-modifier-border)',
  borderRadius: 'var(--radius-s)',
  color: 'var(--text-muted)',
  cursor: 'pointer',
  fontFamily: 'var(--font-interface)',
  fontSize: 12,
  padding: '5px 10px',
}
