import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useThemeStore, THEME_PLUGIN_ID } from '../../../stores/themeStore'
import { useThemePickerStore } from './themePickerStore'
import { getPickerApi } from './pickerRuntime'
import { contrastRatio, applyHueSatDelta } from './contrast'

// ── Variable group manifest ───────────────────────────────────────────────────

interface VarEntry {
  key: string
  label: string
  hint?: string
}

interface VarGroup {
  label: string
  vars: VarEntry[]
}

const BUILDER_GROUPS: VarGroup[] = [
  {
    label: 'Surfaces',
    vars: [
      { key: '--nx-bg-primary',   label: 'Content background', hint: 'Editor, active tab' },
      { key: '--nx-bg-secondary', label: 'Chrome / sidebar',   hint: 'Sidebar, tab bar, panels' },
      { key: '--nx-bg-tertiary',  label: 'Hover surface',      hint: 'Row hover, inactive items' },
      { key: '--nx-bg-elevated',  label: 'Elevated surface',   hint: 'Menus, dropdowns, dialogs' },
    ],
  },
  {
    label: 'Accent',
    vars: [
      { key: '--nx-color-primary',       label: 'Primary accent' },
      { key: '--nx-color-primary-light', label: 'Accent — light', hint: 'Hover state' },
      { key: '--nx-color-primary-dark',  label: 'Accent — dark',  hint: 'Active / pressed state' },
      { key: '--nx-color-secondary',     label: 'Secondary accent' },
    ],
  },
  {
    label: 'Text',
    vars: [
      { key: '--nx-text-primary',   label: 'Primary text' },
      { key: '--nx-text-secondary', label: 'Secondary text' },
      { key: '--nx-text-tertiary',  label: 'Tertiary text' },
      { key: '--nx-text-muted',     label: 'Muted text' },
    ],
  },
  {
    label: 'Editor',
    vars: [
      { key: '--nx-editor-bg',           label: 'Canvas background' },
      { key: '--nx-editor-font-family',  label: 'Canvas font',     hint: 'CSS font-family stack' },
      { key: '--nx-prose-heading-color', label: 'Heading colour' },
      { key: '--nx-prose-link-color',    label: 'Link colour' },
      { key: '--nx-callout-bg',          label: 'Callout background' },
      { key: '--nx-callout-border',      label: 'Callout border' },
    ],
  },
  {
    label: 'Syntax',
    vars: [
      { key: '--nx-syntax-keyword',  label: 'Keyword' },
      { key: '--nx-syntax-string',   label: 'String' },
      { key: '--nx-syntax-comment',  label: 'Comment' },
      { key: '--nx-syntax-function', label: 'Function / method' },
      { key: '--nx-syntax-number',   label: 'Number' },
      { key: '--nx-syntax-type',     label: 'Type' },
    ],
  },
]

// Maps a foreground variable key → its likely background key for WCAG checking.
const CONTRAST_PAIRS: Record<string, string> = {
  '--nx-text-primary':        '--nx-bg-primary',
  '--nx-text-secondary':      '--nx-bg-secondary',
  '--nx-text-tertiary':       '--nx-bg-secondary',
  '--nx-text-muted':          '--nx-bg-secondary',
  '--nx-prose-heading-color': '--nx-editor-bg',
  '--nx-prose-link-color':    '--nx-editor-bg',
  '--nx-syntax-keyword':      '--nx-editor-bg',
  '--nx-syntax-string':       '--nx-editor-bg',
  '--nx-syntax-comment':      '--nx-editor-bg',
  '--nx-syntax-function':     '--nx-editor-bg',
  '--nx-syntax-number':       '--nx-editor-bg',
  '--nx-syntax-type':         '--nx-editor-bg',
}

// ── Utilities ─────────────────────────────────────────────────────────────────

function isHexColor(v: string): boolean {
  return /^#[0-9a-fA-F]{3,8}$/.test(v.trim())
}

function toSixDigitHex(hex: string): string {
  const h = hex.trim()
  return /^#[0-9a-fA-F]{3}$/.test(h)
    ? '#' + h[1] + h[1] + h[2] + h[2] + h[3] + h[3]
    : h
}

function tomlVarBlock(overrides: Record<string, string>): string {
  return Object.entries(overrides)
    .sort(([ka], [kb]) => ka.localeCompare(kb))
    .map(([k, v]) => `"${k}" = "${v.replace(/"/g, '\\"')}"`)
    .join('\n') || '# No overrides yet — adjust variables above.'
}

function generateToml(
  name: string,
  author: string,
  baseId: string,
  overrides: Record<string, string>,
): string {
  const n = name.trim() || 'my-theme'
  const a = author.trim() || 'Unknown'
  return `# Generated by Nexus Theme Builder — base: ${baseId}
# Save as  ~/.nexus/themes/${n.toLowerCase().replace(/\s+/g, '-')}/NEXUS.toml  to install.

[theme]
name             = "${n}"
version          = "0.1.0"
author           = "${a}"
description      = "Custom theme based on ${baseId}"
license          = "MIT"
category         = "custom"
supports         = ["light", "dark"]

[variables]
${tomlVarBlock(overrides)}
`
}

function generateDualToml(
  name: string,
  author: string,
  baseId: string,
  lightOverrides: Record<string, string>,
  darkOverrides: Record<string, string>,
): string {
  const n = name.trim() || 'my-theme'
  const a = author.trim() || 'Unknown'
  const slug = n.toLowerCase().replace(/\s+/g, '-')
  const header = (variant: 'light' | 'dark', cat: string) => `\
# ── ${variant === 'light' ? 'Light' : 'Dark'} variant ─────────────────────────────────────────────────────
# Save as  ~/.nexus/themes/${slug}-${variant}/NEXUS.toml  to install.

[theme]
name             = "${n}-${variant}"
version          = "0.1.0"
author           = "${a}"
description      = "Custom ${variant} theme based on ${baseId}"
license          = "MIT"
category         = "${cat}"
supports         = ["${variant}"]

[variables]
${tomlVarBlock(variant === 'light' ? lightOverrides : darkOverrides)}
`
  return header('light', 'light') + '\n' + header('dark', 'dark')
}

function useDebounce<T>(value: T, delay: number): T {
  const [debounced, setDebounced] = useState<T>(value)
  useEffect(() => {
    const t = setTimeout(() => setDebounced(value), delay)
    return () => clearTimeout(t)
  }, [value, delay])
  return debounced
}

// ── ThemeBuilderPanel ─────────────────────────────────────────────────────────

export function ThemeBuilderPanel() {
  const availableThemes    = useThemeStore((s) => s.availableThemes)
  const activeThemeId      = useThemeStore((s) => s.activeThemeId)
  const builderBaseThemeId = useThemePickerStore((s) => s.builderBaseThemeId)
  const setBuilderBaseId   = useThemePickerStore((s) => s.setBuilderBaseThemeId)
  const builderOverrides   = useThemePickerStore((s) => s.builderOverrides)
  const setOverride        = useThemePickerStore((s) => s.setBuilderOverride)
  const clearOverride      = useThemePickerStore((s) => s.clearBuilderOverride)
  const resetOverrides     = useThemePickerStore((s) => s.resetBuilderOverrides)
  const themeName          = useThemePickerStore((s) => s.builderThemeName)
  const themeAuthor        = useThemePickerStore((s) => s.builderThemeAuthor)
  const setThemeName       = useThemePickerStore((s) => s.setBuilderThemeName)
  const setThemeAuthor     = useThemePickerStore((s) => s.setBuilderThemeAuthor)

  // Dual-mode state
  const dualMode        = useThemePickerStore((s) => s.builderDualMode)
  const setDualMode     = useThemePickerStore((s) => s.setBuilderDualMode)
  const lightOverrides  = useThemePickerStore((s) => s.builderLightOverrides)
  const darkOverrides   = useThemePickerStore((s) => s.builderDarkOverrides)
  const setLightOverride  = useThemePickerStore((s) => s.setBuilderLightOverride)
  const clearLightOverride = useThemePickerStore((s) => s.clearBuilderLightOverride)
  const setDarkOverride   = useThemePickerStore((s) => s.setBuilderDarkOverride)
  const clearDarkOverride = useThemePickerStore((s) => s.clearBuilderDarkOverride)
  const hueLock         = useThemePickerStore((s) => s.builderHueLock)
  const setHueLock      = useThemePickerStore((s) => s.setBuilderHueLock)
  const activeColumn    = useThemePickerStore((s) => s.builderActiveColumn)
  const setActiveColumn = useThemePickerStore((s) => s.setBuilderActiveColumn)

  const effectiveBaseId = builderBaseThemeId ?? activeThemeId ?? ''

  const [baseVars, setBaseVars]       = useState<Record<string, string>>({})
  const [loadingBase, setLoadingBase] = useState(false)

  useEffect(() => {
    if (!effectiveBaseId) return
    let cancelled = false
    setLoadingBase(true)
    void getPickerApi()
      .kernel.invoke<Record<string, string>>(THEME_PLUGIN_ID, 'compute_variables', {
        theme_id: effectiveBaseId, enabled_snippets: [],
      })
      .then((vars) => { if (!cancelled) { setBaseVars(vars); setLoadingBase(false) } })
      .catch(() => { if (!cancelled) setLoadingBase(false) })
    return () => { cancelled = true }
  }, [effectiveBaseId])

  const handleBaseChange = useCallback(async (id: string) => {
    setBuilderBaseId(id)
    setLoadingBase(true)
    const api = getPickerApi()
    const [, vars] = await Promise.all([
      api.kernel.invoke(THEME_PLUGIN_ID, 'apply_theme', { id }),
      api.kernel.invoke<Record<string, string>>(THEME_PLUGIN_ID, 'compute_variables', {
        theme_id: id, enabled_snippets: [],
      }),
    ])
    setBaseVars(vars)
    setLoadingBase(false)
    // Re-apply in-progress overrides on top of the new base.
    const s = useThemePickerStore.getState()
    const current = s.builderDualMode
      ? (s.builderActiveColumn === 'light' ? s.builderLightOverrides : s.builderDarkOverrides)
      : s.builderOverrides
    if (Object.keys(current).length > 0) {
      await api.kernel.invoke(THEME_PLUGIN_ID, 'set_plugin_overrides', { overrides: current })
    }
  }, [setBuilderBaseId])

  // Which overrides are currently "live" (sent to kernel).
  const activeOverrides = dualMode
    ? (activeColumn === 'light' ? lightOverrides : darkOverrides)
    : builderOverrides

  // Debounce the live overrides → kernel.
  const debouncedOverrides = useDebounce(activeOverrides, 500)
  useEffect(() => {
    void getPickerApi().kernel.invoke(THEME_PLUGIN_ID, 'set_plugin_overrides', {
      overrides: debouncedOverrides,
    })
  }, [debouncedOverrides])

  // Switch the active column and immediately apply its overrides.
  const handleSetActiveColumn = useCallback(async (col: 'light' | 'dark') => {
    setActiveColumn(col)
    const overrides = col === 'light'
      ? useThemePickerStore.getState().builderLightOverrides
      : useThemePickerStore.getState().builderDarkOverrides
    await getPickerApi().kernel.invoke(THEME_PLUGIN_ID, 'set_plugin_overrides', { overrides })
  }, [setActiveColumn])

  // Set a variable in one column, with optional hue-lock propagation.
  const handleSetInColumn = useCallback((
    col: 'light' | 'dark',
    key: string,
    newValue: string,
  ) => {
    const s = useThemePickerStore.getState()
    const colOverrides = col === 'light' ? s.builderLightOverrides : s.builderDarkOverrides
    const prevValue = colOverrides[key] ?? baseVars[key] ?? ''

    if (col === 'light') setLightOverride(key, newValue)
    else setDarkOverride(key, newValue)

    // Hue-lock: propagate hue + saturation delta to the other column.
    if (s.builderHueLock && isHexColor(prevValue) && isHexColor(newValue)) {
      const otherOverrides = col === 'light' ? s.builderDarkOverrides : s.builderLightOverrides
      const otherValue = otherOverrides[key] ?? baseVars[key] ?? ''
      if (isHexColor(otherValue)) {
        const shifted = applyHueSatDelta(prevValue, newValue, otherValue)
        if (shifted) {
          if (col === 'light') setDarkOverride(key, shifted)
          else setLightOverride(key, shifted)
        }
      }
    }
  }, [baseVars, setLightOverride, setDarkOverride])

  const handleClearInColumn = useCallback((col: 'light' | 'dark', key: string) => {
    if (col === 'light') clearLightOverride(key)
    else clearDarkOverride(key)
  }, [clearLightOverride, clearDarkOverride])

  const [applied, setApplied] = useState(false)
  const [copied, setCopied]   = useState(false)
  const [saved, setSaved]     = useState(false)

  const handleApplyNow = useCallback(async () => {
    await getPickerApi().kernel.invoke(THEME_PLUGIN_ID, 'set_plugin_overrides', {
      overrides: activeOverrides,
    })
    setApplied(true)
    setTimeout(() => setApplied(false), 2000)
  }, [activeOverrides])

  const handleReset = useCallback(async () => {
    resetOverrides()
    await getPickerApi().kernel.invoke(THEME_PLUGIN_ID, 'set_plugin_overrides', {
      overrides: {},
    })
  }, [resetOverrides])

  const tomlOutput = useMemo(
    () => dualMode
      ? generateDualToml(themeName, themeAuthor, effectiveBaseId, lightOverrides, darkOverrides)
      : generateToml(themeName, themeAuthor, effectiveBaseId, builderOverrides),
    [dualMode, themeName, themeAuthor, effectiveBaseId, builderOverrides, lightOverrides, darkOverrides],
  )

  const handleCopyToml = useCallback(() => {
    void navigator.clipboard.writeText(tomlOutput).then(() => {
      setCopied(true); setTimeout(() => setCopied(false), 2000)
    })
  }, [tomlOutput])

  const handleSaveToDisk = useCallback(async () => {
    const api = getPickerApi()
    const path = await api.platform.dialog.saveFile({
      title: 'Save Theme Manifest',
      defaultPath: 'NEXUS.toml',
      filters: [{ name: 'Nexus Theme Manifest', extensions: ['toml'] }],
    })
    if (!path) return
    const sep = path.includes('/') ? '/' : '\\'
    const dir = path.substring(0, path.lastIndexOf(sep))
    if (dir) await api.platform.fs.mkdir(dir, { recursive: true })
    await api.platform.fs.writeText(path, tomlOutput)
    await api.kernel.invoke(THEME_PLUGIN_ID, 'reload', {})
    setSaved(true)
    setTimeout(() => setSaved(false), 3000)
  }, [tomlOutput])

  const hasOverrides = dualMode
    ? Object.keys(lightOverrides).length + Object.keys(darkOverrides).length > 0
    : Object.keys(builderOverrides).length > 0

  const overrideCount = dualMode
    ? Object.keys(lightOverrides).length + Object.keys(darkOverrides).length
    : Object.keys(builderOverrides).length

  const baseThemeName = useMemo(
    () => availableThemes.find((t) => t.id === effectiveBaseId)?.name as string | undefined,
    [availableThemes, effectiveBaseId],
  )

  return (
    <div style={{ display: 'flex', flexDirection: 'column', flex: 1, overflow: 'hidden' }}>
      {/* ── Scrollable editor ── */}
      <div style={{ flex: 1, overflow: dualMode ? 'hidden' : 'auto', display: 'flex', flexDirection: 'column' }}>

        {/* Base theme + controls */}
        <div style={{ padding: '10px 16px', borderBottom: '1px solid var(--background-modifier-border)', flexShrink: 0 }}>
          {/* Base theme selector */}
          <label style={{ ...LABEL_STYLE, flexDirection: 'row', alignItems: 'center', gap: 8 }}>
            <span style={{ flexShrink: 0, width: 80 }}>Base theme</span>
            <select
              value={effectiveBaseId}
              onChange={(e) => void handleBaseChange(e.target.value)}
              disabled={loadingBase || availableThemes.length === 0}
              style={{
                flex: 1,
                background: 'var(--background-primary)',
                border: '1px solid var(--background-modifier-border)',
                borderRadius: 'var(--radius-s)',
                color: 'var(--text-normal)',
                fontFamily: 'var(--font-interface)',
                fontSize: 12,
                padding: '5px 8px',
                outline: 0,
                cursor: loadingBase ? 'wait' : 'pointer',
              }}
            >
              {availableThemes.map((t) => (
                <option key={t.id} value={t.id}>
                  {typeof t.name === 'string' ? t.name : t.id}
                </option>
              ))}
            </select>
            {loadingBase && (
              <span style={{ fontFamily: 'var(--font-interface)', fontSize: 11, color: 'var(--text-faint)', flexShrink: 0 }}>
                Loading…
              </span>
            )}
          </label>

          {/* Dual mode + hue-lock controls */}
          <div style={{ display: 'flex', gap: 12, marginTop: 8, alignItems: 'center' }}>
            <label style={{ display: 'flex', alignItems: 'center', gap: 6, cursor: 'pointer' }}>
              <input
                type="checkbox"
                checked={dualMode}
                onChange={(e) => setDualMode(e.target.checked)}
                style={{ cursor: 'pointer' }}
              />
              <span style={{ fontFamily: 'var(--font-interface)', fontSize: 11, color: 'var(--text-muted)' }}>
                Dual mode (Light + Dark)
              </span>
            </label>
            {dualMode && (
              <label style={{ display: 'flex', alignItems: 'center', gap: 6, cursor: 'pointer' }}>
                <input
                  type="checkbox"
                  checked={hueLock}
                  onChange={(e) => setHueLock(e.target.checked)}
                  style={{ cursor: 'pointer' }}
                />
                <span
                  title="When editing a hex colour, shift the same variable in the other column by the same hue + saturation delta"
                  style={{ fontFamily: 'var(--font-interface)', fontSize: 11, color: 'var(--text-muted)' }}
                >
                  Hue-lock
                </span>
              </label>
            )}
            {baseThemeName && !dualMode && (
              <span style={{ fontFamily: 'var(--font-interface)', fontSize: 11, color: 'var(--text-faint)', marginLeft: 'auto' }}>
                Based on <em>{baseThemeName}</em>
              </span>
            )}
          </div>
        </div>

        {/* Theme identity inputs */}
        <div
          style={{
            padding: '10px 16px',
            display: 'grid',
            gridTemplateColumns: '1fr 1fr',
            gap: 8,
            borderBottom: '1px solid var(--background-modifier-border)',
            flexShrink: 0,
          }}
        >
          <label style={LABEL_STYLE}>
            Theme name
            <input type="text" value={themeName} onChange={(e) => setThemeName(e.target.value)}
              placeholder="my-theme" style={TEXT_INPUT_STYLE} />
          </label>
          <label style={LABEL_STYLE}>
            Author
            <input type="text" value={themeAuthor} onChange={(e) => setThemeAuthor(e.target.value)}
              placeholder="Your name" style={TEXT_INPUT_STYLE} />
          </label>
        </div>

        {/* Variable editor — single or dual column */}
        {dualMode ? (
          <div style={{ flex: 1, display: 'grid', gridTemplateColumns: '1fr 1fr', overflow: 'hidden' }}>
            {/* Light column */}
            <div style={{ overflowY: 'auto', borderRight: '1px solid var(--background-modifier-border)' }}>
              <ColumnHeader
                label="Light" icon="☀"
                active={activeColumn === 'light'}
                overrideCount={Object.keys(lightOverrides).length}
                onActivate={() => void handleSetActiveColumn('light')}
              />
              {BUILDER_GROUPS.map((group) => (
                <VariableGroup
                  key={group.label}
                  group={group}
                  baseVars={baseVars}
                  loadingBase={loadingBase}
                  overrides={lightOverrides}
                  compact
                  onSet={(k, v) => handleSetInColumn('light', k, v)}
                  onClear={(k) => handleClearInColumn('light', k)}
                />
              ))}
            </div>
            {/* Dark column */}
            <div style={{ overflowY: 'auto' }}>
              <ColumnHeader
                label="Dark" icon="🌙"
                active={activeColumn === 'dark'}
                overrideCount={Object.keys(darkOverrides).length}
                onActivate={() => void handleSetActiveColumn('dark')}
              />
              {BUILDER_GROUPS.map((group) => (
                <VariableGroup
                  key={group.label}
                  group={group}
                  baseVars={baseVars}
                  loadingBase={loadingBase}
                  overrides={darkOverrides}
                  compact
                  onSet={(k, v) => handleSetInColumn('dark', k, v)}
                  onClear={(k) => handleClearInColumn('dark', k)}
                />
              ))}
            </div>
          </div>
        ) : (
          /* Single-column layout */
          <div style={{ flex: 1, overflowY: 'auto' }}>
            {BUILDER_GROUPS.map((group) => (
              <VariableGroup
                key={group.label}
                group={group}
                baseVars={baseVars}
                loadingBase={loadingBase}
                overrides={builderOverrides}
                onSet={setOverride}
                onClear={clearOverride}
              />
            ))}
          </div>
        )}

        {/* TOML export */}
        <section style={{ borderTop: '1px solid var(--background-modifier-border)', padding: '10px 16px', flexShrink: 0 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 6 }}>
            <span style={{ fontFamily: 'var(--font-interface)', fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>
              Export TOML{dualMode ? ' (2 files)' : ''}
            </span>
            <div style={{ display: 'flex', gap: 6 }}>
              <button onClick={handleCopyToml} style={{ ...GHOST_BTN_STYLE, color: copied ? 'var(--interactive-accent)' : 'var(--text-muted)' }}>
                {copied ? 'Copied ✓' : 'Copy'}
              </button>
              <button onClick={() => void handleSaveToDisk()} style={{ ...GHOST_BTN_STYLE, color: saved ? 'var(--interactive-accent)' : 'var(--text-muted)' }}>
                {saved ? 'Saved ✓' : 'Save to disk'}
              </button>
            </div>
          </div>
          <textarea
            readOnly value={tomlOutput} spellCheck={false}
            style={{
              width: '100%', height: dualMode ? 180 : 140, resize: 'none',
              background: 'var(--background-primary)', border: '1px solid var(--background-modifier-border)',
              borderRadius: 'var(--radius-s)', color: 'var(--text-muted)',
              fontFamily: 'var(--font-monospace)', fontSize: 11, lineHeight: 1.55,
              padding: '8px 10px', outline: 0, boxSizing: 'border-box',
            }}
          />
          <p style={{ fontFamily: 'var(--font-interface)', fontSize: 11, color: 'var(--text-faint)', marginTop: 4 }}>
            {dualMode
              ? 'Two separate theme files — copy each section and save to its own directory.'
              : <>Save as <code style={{ fontFamily: 'var(--font-monospace)' }}>~/.nexus/themes/&lt;id&gt;/NEXUS.toml</code> — Nexus hot-reloads automatically.</>
            }
          </p>
        </section>
      </div>

      {/* ── Footer ── */}
      <div style={{ borderTop: '1px solid var(--background-modifier-border)', padding: '10px 16px', display: 'flex', alignItems: 'center', gap: 8, flexShrink: 0 }}>
        <span style={{ fontFamily: 'var(--font-interface)', fontSize: 12, color: 'var(--text-faint)', flex: 1 }}>
          {hasOverrides
            ? `${overrideCount} variable${overrideCount === 1 ? '' : 's'} overridden${dualMode ? ` across both columns` : ''} · preview updates in ~500 ms`
            : `No overrides — edit variables above to customise the ${dualMode ? 'base theme' : 'active theme'}.`}
        </span>
        <button onClick={() => void handleReset()} disabled={!hasOverrides}
          style={{ ...GHOST_BTN_STYLE, opacity: hasOverrides ? 1 : 0.4, cursor: hasOverrides ? 'pointer' : 'default' }}>
          Reset all
        </button>
        <button onClick={() => void handleApplyNow()} disabled={!hasOverrides}
          style={{
            background: hasOverrides ? 'var(--interactive-accent)' : 'var(--background-modifier-border)',
            color: hasOverrides ? 'var(--text-on-accent)' : 'var(--text-muted)',
            border: 0, borderRadius: 'var(--radius-s)', padding: '6px 14px',
            fontFamily: 'var(--font-interface)', fontSize: 12, fontWeight: 600,
            cursor: hasOverrides ? 'pointer' : 'default', transition: 'background 100ms',
          }}>
          {applied ? 'Applied ✓' : dualMode ? `Apply ${activeColumn}` : 'Apply now'}
        </button>
      </div>
    </div>
  )
}

// ── ColumnHeader ──────────────────────────────────────────────────────────────

interface ColumnHeaderProps {
  label: string
  icon: string
  active: boolean
  overrideCount: number
  onActivate(): void
}

function ColumnHeader({ label, icon, active, overrideCount, onActivate }: ColumnHeaderProps) {
  return (
    <button
      onClick={onActivate}
      style={{
        display: 'flex',
        alignItems: 'center',
        gap: 6,
        width: '100%',
        background: active ? 'var(--background-modifier-active-hover, var(--interactive-accent-soft))' : 'transparent',
        border: 0,
        borderBottom: active
          ? '2px solid var(--interactive-accent)'
          : '2px solid var(--background-modifier-border)',
        padding: '7px 12px',
        cursor: 'pointer',
        textAlign: 'left',
      }}
    >
      <span style={{ fontSize: 13 }}>{icon}</span>
      <span style={{ fontFamily: 'var(--font-interface)', fontSize: 12, fontWeight: 600, color: active ? 'var(--text-normal)' : 'var(--text-muted)', flex: 1 }}>
        {label}
      </span>
      {active && (
        <span style={{ fontFamily: 'var(--font-interface)', fontSize: 10, color: 'var(--interactive-accent)', flexShrink: 0 }}>
          ● live
        </span>
      )}
      {overrideCount > 0 && (
        <span style={{
          fontFamily: 'var(--font-interface)', fontSize: 10,
          color: 'var(--interactive-accent)',
          background: 'var(--background-modifier-active-hover, var(--interactive-accent-soft))',
          borderRadius: 'var(--radius-full, 9999px)', padding: '1px 5px', flexShrink: 0,
        }}>
          {overrideCount}
        </span>
      )}
    </button>
  )
}

// ── VariableGroup ─────────────────────────────────────────────────────────────

interface VariableGroupProps {
  group: VarGroup
  baseVars: Record<string, string>
  loadingBase: boolean
  overrides: Record<string, string>
  compact?: boolean
  onSet(key: string, value: string): void
  onClear(key: string): void
}

function VariableGroup({ group, baseVars, loadingBase, overrides, compact, onSet, onClear }: VariableGroupProps) {
  const [open, setOpen] = useState(true)
  const overriddenCount = group.vars.filter((v) => overrides[v.key] !== undefined).length

  return (
    <section>
      <button
        onClick={() => setOpen((o) => !o)}
        style={{
          display: 'flex', alignItems: 'center', gap: 8, width: '100%',
          background: 'transparent', border: 0,
          borderBottom: '1px solid var(--background-modifier-border)',
          padding: '7px 16px', cursor: 'pointer', textAlign: 'left',
        }}
      >
        <span style={{ fontFamily: 'var(--font-interface)', fontSize: 11, color: 'var(--text-faint)', width: 10, flexShrink: 0 }}>
          {open ? '▾' : '▸'}
        </span>
        <span style={{ fontFamily: 'var(--font-interface)', fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em', flex: 1 }}>
          {group.label}
        </span>
        {overriddenCount > 0 && (
          <span style={{
            fontFamily: 'var(--font-interface)', fontSize: 10, color: 'var(--interactive-accent)',
            background: 'var(--background-modifier-active-hover, var(--interactive-accent-soft))',
            borderRadius: 'var(--radius-full, 9999px)', padding: '1px 6px',
          }}>
            {overriddenCount}
          </span>
        )}
      </button>

      {open && group.vars.map((entry) => {
        const bgKey = CONTRAST_PAIRS[entry.key]
        const contrastBgValue = bgKey ? (overrides[bgKey] ?? baseVars[bgKey] ?? '') : undefined
        return (
          <VarRow
            key={entry.key}
            entry={entry}
            baseValue={baseVars[entry.key] ?? ''}
            loadingBase={loadingBase}
            override={overrides[entry.key]}
            contrastBgValue={contrastBgValue}
            compact={compact}
            onSet={onSet}
            onClear={onClear}
          />
        )
      })}
    </section>
  )
}

// ── VarRow ────────────────────────────────────────────────────────────────────

interface VarRowProps {
  entry: VarEntry
  baseValue: string
  loadingBase: boolean
  override: string | undefined
  contrastBgValue?: string
  compact?: boolean
  onSet(key: string, value: string): void
  onClear(key: string): void
}

function VarRow({ entry, baseValue, loadingBase, override, contrastBgValue, compact, onSet, onClear }: VarRowProps) {
  const effectiveValue = override ?? baseValue
  const isHex = isHexColor(effectiveValue)
  const colorInputRef = useRef<HTMLInputElement | null>(null)
  const [hovered, setHovered] = useState(false)

  const ratio = contrastBgValue !== undefined
    ? contrastRatio(effectiveValue, contrastBgValue)
    : null

  const handleTextChange = (raw: string) => {
    raw === '' ? onClear(entry.key) : onSet(entry.key, raw)
  }

  const labelWidth = compact ? 90 : 160

  return (
    <div
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      style={{
        display: 'flex', alignItems: 'center', gap: compact ? 6 : 10,
        padding: '6px 16px',
        background: hovered ? 'var(--background-modifier-hover)' : 'transparent',
        transition: 'background 80ms',
      }}
    >
      {/* Colour swatch */}
      <div style={{ flexShrink: 0, position: 'relative' }}>
        <div
          title={isHex ? 'Click to open colour picker' : effectiveValue || '—'}
          onClick={() => isHex && colorInputRef.current?.click()}
          style={{
            width: 20, height: 20, borderRadius: 'var(--radius-s)',
            background: effectiveValue || 'var(--background-modifier-border)',
            border: '1px solid var(--background-modifier-border)',
            cursor: isHex ? 'pointer' : 'default',
            opacity: loadingBase && !override ? 0.4 : 1,
            transition: 'opacity 150ms',
          }}
        />
        {isHex && (
          <input ref={colorInputRef} type="color" value={toSixDigitHex(effectiveValue)}
            onChange={(e) => onSet(entry.key, e.target.value)} tabIndex={-1}
            style={{ position: 'absolute', opacity: 0, width: 0, height: 0, pointerEvents: 'none' }} />
        )}
      </div>

      {/* Label */}
      <div style={{ width: labelWidth, flexShrink: 0 }}>
        <div style={{
          fontFamily: 'var(--font-interface)', fontSize: compact ? 11 : 12,
          color: override !== undefined ? 'var(--text-normal)' : 'var(--text-muted)',
          fontWeight: override !== undefined ? 500 : 400,
          overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
        }}>
          {entry.label}
        </div>
        {!compact && entry.hint && (
          <div style={{ fontFamily: 'var(--font-interface)', fontSize: 10, color: 'var(--text-faint)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
            {entry.hint}
          </div>
        )}
      </div>

      {/* Text input */}
      <input
        type="text" value={override ?? ''}
        placeholder={loadingBase ? 'loading…' : (baseValue || entry.key)}
        onChange={(e) => handleTextChange(e.target.value)}
        spellCheck={false}
        style={{
          flex: 1, minWidth: 0,
          background: 'var(--background-primary)',
          border: override !== undefined ? '1px solid var(--interactive-accent)' : '1px solid var(--background-modifier-border)',
          borderRadius: 'var(--radius-s)', color: 'var(--text-normal)',
          fontFamily: 'var(--font-monospace)', fontSize: 11, padding: '4px 7px', outline: 0,
        }}
      />

      {/* WCAG contrast badge */}
      {ratio !== null && <ContrastBadge ratio={ratio} />}

      {/* Clear override */}
      <button
        onClick={() => onClear(entry.key)} disabled={override === undefined}
        title="Clear override" aria-label={`Clear override for ${entry.label}`}
        style={{
          background: 'transparent', border: 0, color: 'var(--text-muted)',
          cursor: override !== undefined ? 'pointer' : 'default',
          fontSize: 13, lineHeight: 1, padding: '2px 4px',
          opacity: override !== undefined ? (hovered ? 1 : 0.5) : 0,
          transition: 'opacity 100ms', flexShrink: 0,
        }}
      >
        ×
      </button>
    </div>
  )
}

// ── ContrastBadge ─────────────────────────────────────────────────────────────

function ContrastBadge({ ratio }: { ratio: number }) {
  const isAAA = ratio >= 7
  const isAA  = ratio >= 4.5
  const label  = isAAA ? 'AAA' : isAA ? 'AA' : '✗'
  const color  = isAAA ? '#27AE60' : isAA ? 'var(--interactive-accent, #3498DB)' : '#E74C3C'
  const bg     = isAAA ? 'rgba(39,174,96,0.12)'  : isAA ? 'rgba(74,144,226,0.12)'  : 'rgba(231,76,60,0.12)'
  const border = isAAA ? 'rgba(39,174,96,0.3)'   : isAA ? 'rgba(74,144,226,0.3)'   : 'rgba(231,76,60,0.3)'
  const tip = `${ratio.toFixed(1)}:1 — ${isAAA ? 'Passes WCAG AAA (≥7:1)' : isAA ? 'Passes WCAG AA (≥4.5:1)' : 'Fails WCAG AA (need ≥4.5:1)'}`
  return (
    <span title={tip} style={{
      fontFamily: 'var(--font-monospace)', fontSize: 10, fontWeight: 600,
      color, background: bg, border: `1px solid ${border}`,
      borderRadius: 'var(--radius-s)', padding: '2px 5px',
      flexShrink: 0, cursor: 'default', userSelect: 'none',
    }}>
      {label}
    </span>
  )
}

// ── Shared styles ─────────────────────────────────────────────────────────────

const LABEL_STYLE: React.CSSProperties = {
  display: 'flex', flexDirection: 'column', gap: 4,
  fontFamily: 'var(--font-interface)', fontSize: 11, color: 'var(--text-muted)',
}

const TEXT_INPUT_STYLE: React.CSSProperties = {
  background: 'var(--background-primary)',
  border: '1px solid var(--background-modifier-border)',
  borderRadius: 'var(--radius-s)', color: 'var(--text-normal)',
  fontFamily: 'var(--font-interface)', fontSize: 12, padding: '5px 8px', outline: 0,
}

const GHOST_BTN_STYLE: React.CSSProperties = {
  background: 'transparent', border: '1px solid var(--background-modifier-border)',
  borderRadius: 'var(--radius-s)', color: 'var(--text-muted)',
  cursor: 'pointer', fontFamily: 'var(--font-interface)', fontSize: 12, padding: '5px 10px',
}
