/**
 * Public TypeScript surface for Nexus script-plugin authors (UI F-2.1.1).
 *
 * ## Status — pre-1.0, two runtime contracts diverge (#187)
 *
 * The `NexusPluginContext` / `ScriptPlugin` shapes below are the
 * *target* contract this package will eventually freeze at `1.x`. They
 * are **not** what any current runtime supplies:
 *
 * | Runtime | Actual context type | Source |
 * |---|---|---|
 * | In-process shell host | `PluginAPI` | `shell/src/types/plugin.ts` |
 * | Sandboxed community plugins | `SandboxedPluginContext` | `./sandbox/context.ts` |
 *
 * `PluginAPI` and `SandboxedPluginContext` overlap with
 * `NexusPluginContext` on the verbs that matter (commands, events,
 * notifications, settings, ipc / kernel.invoke) but neither satisfies
 * it structurally — the field names and async-versus-sync split differ.
 * See [`CONTRACT_STATUS.md`](../CONTRACT_STATUS.md) for the per-field
 * inventory.
 *
 * Until the contracts are reconciled, treat `NexusPluginContext` and
 * `ScriptPlugin` as forward-looking documentation, not as a substitute
 * for the runtime-specific contracts.
 *
 * ## Versioning
 *
 * The current `1.0.0` package tag predates the runtime audit that
 * surfaced the divergence above; it does not yet imply structural
 * freeze. A future `2.0.0` (or a clean re-cut to `0.x` for the next
 * major) will hold the line once one runtime shape is canonical and
 * the others adopt it.
 *
 * ## Runtime
 *
 * This package is **types-only**. There is nothing to `new` from it.
 *
 * ## What's in scope
 *
 * - Every field on `NexusPluginContext`, including subsurface types
 *   (`Disposable`, `DisposableStore`, `DeclaredCapabilities`).
 * - Every contribution DTO the host consumes
 *   (`EditorBlockType`, `EditorDecorationProvider`, `EditorKeybinding`,
 *   `Snippet`, `MenuItem`, `ContextMenuItem`, `UriHandler`,
 *   `WebviewPanelConfig`, `TreeDataProvider`, `TreeNode`, `PanelNode`).
 * - `ScriptPlugin` — the shape a plugin's default export must satisfy.
 *
 * ## What's out of scope
 *
 * - React components. This package has no `react` dependency so plugins
 *   that ship JSX must depend on React themselves.
 * - CM6 extension types. Plugins that contribute editor decorations
 *   still depend on `@codemirror/*` directly — we re-export only the
 *   host-facing `Extension` opaque reference.
 *
 * ## Deprecating an export (OI-17)
 *
 * Three coordinated edits in one PR:
 *   1. `@deprecated` JSDoc on the symbol below — TypeScript's language
 *      service surfaces the strikethrough + warning at author time.
 *   2. A row in `DEPRECATED.md` (next to this file) describing the
 *      replacement and the target removal version.
 *   3. An `importNames` entry in `shell/eslint.config.js`'s
 *      `no-restricted-imports` block — the CI gate.
 *
 * See `DEPRECATED.md` for the full protocol. Removed surfaces graduate
 * to the historical archive in `/DEPRECATED.md` at the repo root.
 */

// Re-export ts-rs–generated Rust contract types (Capability, IpcError,
// PluginInfo, NexusEvent, …). Generated by `cargo test -p
// nexus-plugin-api --features ts-export`; do not hand-edit the
// `./generated/*.ts` files.
export * from './generated';

/**
 * Versioned plugin ABI marker. Mirrors `PLUGIN_API_VERSION` const in
 * `crates/nexus-plugin-api/src/lib.rs`. Bump in lockstep — ts-rs does
 * not derive consts, so this is hand-authored. WI-20 (later commit)
 * adds a CI check that asserts the values match.
 */
export const PLUGIN_API_VERSION = 1 as const;

export type ToastLevel = "info" | "warn" | "error";

/** Disposal callback — returned from every `register*` API. */
export type Disposable = () => void;

/**
 * Collects disposables and flushes them in LIFO order on plugin stop.
 * The host auto-creates one per plugin and attaches it as
 * `ctx.disposables`; plugins simply call `add(d)` on every register.
 */
export interface DisposableStore {
  add(d: Disposable): Disposable;
  dispose(): void;
  readonly size: number;
}

/** Optional capability-set used by the host to gate context surfaces. */
export type DeclaredCapabilities = ReadonlySet<string> | undefined;

// ─── Editor contributions ────────────────────────────────────────────────────

export interface EditorBlockType {
  id: string;
  label: string;
  icon: string;
  description?: string;
  toMarkdown?: (content: string, attrs?: Record<string, unknown>) => string;
}

/**
 * Opaque CodeMirror 6 extension. Plugins that contribute decorations
 * should import the concrete `Extension` type from `@codemirror/state`
 * for better type inference; this alias exists so the extension-api
 * package stays free of a CM6 peer dependency.
 */
export type EditorExtension = unknown;

export interface EditorDecorationProvider {
  id: string;
  extension: EditorExtension;
}

export interface EditorKeybinding {
  id: string;
  key: string;
  commandId: string;
}

export interface Snippet {
  id: string;
  trigger: string;
  body: string;
  description?: string;
  fileTypes?: string[];
}

// ─── UI contributions ────────────────────────────────────────────────────────

export interface TreeNode {
  id: string;
  label: string;
  icon?: string;
  children?: TreeNode[] | null;
}

export interface TreeDataProvider {
  id: string;
  getChildren(nodeId: string | null): TreeNode[] | Promise<TreeNode[]>;
  onSelect?(nodeId: string, node: TreeNode): void | Promise<void>;
}

export interface WebviewPanelConfig {
  htmlUrl: string;
  allowPopups?: boolean;
}

export interface UriHandler {
  id: string;
  scheme: string;
  handle(url: string): void | Promise<void>;
}

export interface MenuItem {
  id: string;
  label: string;
  commandId: string;
  menu: string;
  separatorBefore?: boolean;
  disabled?: boolean;
  icon?: string;
  order?: number;
  menuOrder?: number;
}

export interface ContextMenuItem {
  id: string;
  label: string;
  commandId: string;
  scopes: string[];
  separatorBefore?: boolean;
  disabled?: boolean;
  icon?: string;
}

// ─── Declarative panel primitives (UI F-5.2.1) ───────────────────────────────

export type PanelNode =
  | { type: "vstack"; gap?: number; children: PanelNode[] }
  | { type: "hstack"; gap?: number; children: PanelNode[] }
  | { type: "text"; value: string; muted?: boolean; strong?: boolean }
  | { type: "heading"; value: string; level?: 1 | 2 | 3 }
  | { type: "button"; label: string; commandId: string; disabled?: boolean }
  | { type: "spacer"; size?: number };

export type PanelRenderFn = () => PanelNode;

// ─── MDX component runtime (PRD-08 §7) ───────────────────────────────────────

/**
 * An MDX component that the editor renders inline when it sees a
 * matching self-closing JSX tag in markdown / MDX files.
 *
 * The host never evaluates plugin-supplied JSX: the attribute list is
 * parsed to a plain object, passed to `render`, and the returned
 * `PanelNode` tree is walked by a host-owned declarative dispatcher.
 * Same trade-off as `registerPanelView` — approved primitives only,
 * no HTML escape hatch.
 *
 * Component names must start with an uppercase letter (JSX tag rule)
 * and match `/^[A-Z][A-Za-z0-9]*$/`.
 */
export interface MdxComponent {
  id: string;
  name: string;
  description?: string;
  render(props: Record<string, unknown>): PanelNode;
}

// ─── Host-provided context ───────────────────────────────────────────────────

/**
 * **Status (#187): aspirational, not yet runtime-backed.** No in-tree
 * runtime exposes a context that satisfies this interface today. The
 * in-process shell host hands plugins a `PluginAPI`
 * (`shell/src/types/plugin.ts`) and the sandbox runtime hands them a
 * `SandboxedPluginContext` (`./sandbox/context.ts`). Both overlap with
 * the verbs declared below but diverge on field names and on the
 * sync-versus-async boundary — see [`CONTRACT_STATUS.md`](../CONTRACT_STATUS.md).
 *
 * Treat this shape as the target contract once one runtime is chosen
 * canonical. Plugin authors targeting today's host should import
 * `PluginAPI` (in-process) or `SandboxedPluginContext` (sandboxed)
 * directly until the divergence is closed.
 */
export interface NexusPluginContext {
  pluginId: string;

  settings: {
    get(): Promise<Record<string, unknown>>;
  };

  events: {
    emit(typeId: string, payload: unknown): Promise<void>;
  };

  ipc: {
    call(
      targetPluginId: string,
      commandId: string,
      args?: unknown,
    ): Promise<unknown>;
  };

  editor: EditorAPI & {
    registerBlockType(type: EditorBlockType): Disposable;
    registerDecorationProvider(provider: EditorDecorationProvider): Disposable;
    registerKeybinding(binding: EditorKeybinding): Disposable;
    registerSnippet(snippet: Snippet): Disposable;
    /**
     * Register an MDX component — the editor scans for matching
     * self-closing JSX tags and renders each as a widget. PRD-08 §7.
     */
    registerMdxComponent(component: MdxComponent): Disposable;
  };

  ui: {
    notify(level: ToastLevel, message: string): void;
    registerTreeDataProvider(
      viewId: string,
      provider: TreeDataProvider,
    ): Disposable;
    registerFileHandler(ext: string, contentTypeId: string): Disposable;
    registerContextMenuItem(item: ContextMenuItem): Disposable;
    registerMenuItem(item: MenuItem): Disposable;
    registerUriHandler(handler: UriHandler): Disposable;
    registerWebviewPanel(viewId: string, config: WebviewPanelConfig): Disposable;
    registerPanelView(viewId: string, render: PanelRenderFn): Disposable;
  };

  workspace: WorkspaceAPI;

  /**
   * AI action registry (BL-035). Plugins contribute named actions
   * (summarize, rewrite, translate, …) bound to one or more surfaces;
   * the shell surfaces matching actions in the editor's right-click
   * selection menu, the block-handle menu, and (once BL-038 lands) the
   * canvas node menu. The runtime impl is supplied by the host —
   * extension-api ships only the contract.
   */
  ai: AiAPI;

  disposables: DisposableStore;
}

// ─── AI action surface (BL-035) ──────────────────────────────────────────────

/**
 * Surfaces an AI action can be bound to. The shell only surfaces the
 * action where its `surfaces` list overlaps the surface that produced
 * the menu — an action with `['block']` does not appear on the editor
 * selection menu, and vice versa.
 */
export type AiActionSurface = 'editor.selection' | 'block' | 'canvas.node';

/** `run(ctx)` payload when the action was invoked from the editor's
 *  selection right-click menu. `selection` is non-empty by construction
 *  — the shell hides the AI submenu when the selection is empty. */
export interface AiActionEditorSelectionContext {
  surface: 'editor.selection';
  /** Forge-relative path of the editor tab the selection came from. */
  relpath: string;
  /** The selected text, exactly as the user has it highlighted. */
  selection: string;
  /** CodeMirror document offsets bracketing the selection. Useful for
   *  actions that want to splice their result back into the buffer. */
  selectionRange: { from: number; to: number };
}

/** `run(ctx)` payload when the action was invoked from the block-handle
 *  menu. `blockText` is the markdown source of the whole block (heading
 *  + body for a section, bullet + nested children for a list item, …). */
export interface AiActionBlockContext {
  surface: 'block';
  /** Forge-relative path of the editor tab the block came from. */
  relpath: string;
  /** Stable id for the block within the document (the same id the
   *  block-handle menu uses when reordering / duplicating). */
  blockId: string;
  /** Full markdown text of the block. */
  blockText: string;
}

/** `run(ctx)` payload when the action was invoked from a canvas node's
 *  context menu. Wired once BL-038 lands; included here so the
 *  registry's surface union is complete at the contract boundary. */
export interface AiActionCanvasNodeContext {
  surface: 'canvas.node';
  nodeId: string;
  text: string;
}

/** Discriminated union of every payload an AI action can receive. The
 *  `surface` discriminator matches the entry in `AiAction.surfaces`. */
export type AiActionContext =
  | AiActionEditorSelectionContext
  | AiActionBlockContext
  | AiActionCanvasNodeContext;

/**
 * A single contributed AI action. Plugins register one per
 * user-visible behaviour (summarize / rewrite / translate / …). The
 * shell labels the menu row from `label`, filters by `surfaces`, and
 * dispatches to `run` with a payload whose `surface` discriminator
 * matches whichever entry triggered the menu.
 *
 * Errors thrown from `run` are caught by the registry and logged —
 * one bad action must not crash the menu.
 */
export interface AiAction {
  /** Stable id, e.g. `nexus.ai.summarize`. Reverse-DNS prefix
   *  recommended; collisions across plugins are first-match-wins
   *  with a console warning. */
  id: string;
  /** Human-readable label rendered as the menu row. Localised by the
   *  contributing plugin — the host does not translate. */
  label: string;
  /** Which surfaces this action should appear on. Order is
   *  insignificant. An empty list registers the action without ever
   *  surfacing it (rare; useful for deferred wire-up). */
  surfaces: AiActionSurface[];
  /** Invoked when the user picks the menu row. Receives the bound
   *  surface payload. May be sync or async; the menu closes
   *  immediately, so long-running work should stream output into the
   *  AI chat overlay or directly into the editor rather than blocking
   *  on the returned promise. */
  run(ctx: AiActionContext): void | Promise<void>;
}

/** Public AI API surface (`api.ai.*`). Today exposes only the action
 *  registry — context contributors and the chat surface graduate to
 *  `api.ai.*` in BL-033 / BL-039. */
export interface AiAPI {
  /** Register an AI action. Returns a disposer; tracked via
   *  `ctx.disposables` so plugin unload sweeps it. */
  registerAction(action: AiAction): Disposable;
}

/**
 * Snapshot of the active editor tab returned by {@link EditorAPI.active}.
 *
 * `revision` is an opaque cache-key — it advances on every edit but its
 * absolute value is meaningless. Compare for equality only.
 */
export interface ActiveEditor {
  relpath: string;
  revision: number;
}

/**
 * Active-editor accessors (OI-14). Lets a plugin read what the user is
 * currently looking at without reaching for `kernel.invoke('com.nexus.editor', ...)`
 * or knowing about the editor plugin's command ids.
 */
export interface EditorAPI {
  /** Snapshot of the active editor tab, or `null` when none is open. */
  active(): ActiveEditor | null;
  /**
   * Subscribe to changes in the active editor. Fires when the user
   * switches tabs, when the active buffer's revision advances, or when
   * the active tab is closed. The returned disposer is idempotent and
   * is auto-swept on plugin unload.
   */
  onChange(handler: (active: ActiveEditor | null) => void): () => void;
  /**
   * Register a renderer for a fenced code block language tag (BL-008).
   * The editor's live-preview decoration walker and the preview-mode
   * markdown pipeline both consult the registry when a fenced block's
   * info string matches `language` and emit the renderer's output
   * inline. The renderer may return synchronously or via Promise; the
   * registry caches per (language, source) pair so cursor motion does
   * not re-render. Returns a disposer; first-match-wins on duplicate
   * languages (a console warning fires and the disposer is a no-op).
   */
  registerFencedCodeRenderer(
    language: string,
    renderer: FencedRenderer,
  ): Disposable;
}

/** Result type for {@link FencedRenderer}. */
export type FencedRenderResult = HTMLElement | Promise<HTMLElement>;

/**
 * Renderer signature for a fenced code block (BL-008). `source` is the
 * raw text inside the fence (no opener/closer); `info` is the full
 * info string (typically equal to the language tag, but a renderer may
 * inspect trailing modifiers like `mermaid theme=dark`).
 */
export type FencedRenderer = (
  source: string,
  info: string,
) => FencedRenderResult;

/**
 * Workspace-level accessors (OI-14). Plugins read forge-relative
 * configuration without reaching for the shell's internal stores.
 */
export interface WorkspaceAPI {
  /**
   * Absolute path of the current forge root, or `null` when no
   * forge is open (between `workspace:closed` and the next
   * `workspace:opened`).
   */
  forgeRoot(): string | null;
}

// ─── Plugin entry point ──────────────────────────────────────────────────────

/**
 * Shape a script plugin's default export must satisfy. The host calls
 * the lifecycle hooks in this order:
 *
 *   loadScriptPlugin → onInit → onStart → (dispatch…) → onStop
 *
 * Failures in any hook are logged to the Running Extensions settings
 * tab but do not propagate to other plugins — the contribution bridge
 * keeps going with the next plugin in the snapshot.
 *
 * **Status (#187): aspirational, not yet runtime-backed.** No
 * `loadScriptPlugin` entry point exists in the current shell or
 * sandbox runtime. The in-process shell loads first-party plugins via
 * a different protocol (see `shell/src/host/extensionHost.ts`); the
 * sandbox runtime calls `SandboxedPlugin.activate` /
 * `SandboxedPlugin.deactivate` (see `./sandbox/plugin.ts`). Plugin
 * authors targeting today's host should implement the runtime-specific
 * shape, not this one. See [`CONTRACT_STATUS.md`](../CONTRACT_STATUS.md).
 */
export interface ScriptPlugin {
  dispatch(
    handlerId: number,
    args: unknown,
    ctx: NexusPluginContext,
  ): unknown | Promise<unknown>;
  onInit?(ctx: NexusPluginContext): void | Promise<void>;
  onStart?(ctx: NexusPluginContext): void | Promise<void>;
  onStop?(ctx: NexusPluginContext): void | Promise<void>;
}

// ─── Contributions (moved from shell/src/types/plugin.ts) ───────────────────
//
// Individual contribution DTOs. `PluginManifest` and the
// `PluginContributions` aggregate intentionally stay shell-side until
// `ViewContribution` (which references `SlotId`) is portable — see
// `shell/src/types/plugin.ts`. WI-24 / Phase 7 will promote slot ids
// into the kernel contract; at that point the manifest aggregate moves
// here and this comment goes away.

export interface CommandContribution {
  id: string;
  title: string;
  category?: string;
  icon?: string;
}

export interface MenuContribution {
  menu: string;
  command: string;
  group?: string;
  order?: number;
  when?: string;
}

export interface KeybindingContribution {
  command: string;
  key: string;
  mac?: string;
  when?: string;
}

export interface StatusBarContribution {
  id: string;
  slot: 'left' | 'right';
  priority: number;
  text: string;
}

export interface ContextKeyContribution {
  key: string;
  description: string;
  type: 'boolean' | 'string' | 'number';
}

/**
 * A plugin-contributed tab in the Settings modal (OI-01).
 *
 * Plugins declare metadata here; the renderer is wired from
 * `activate()` via `api.settings.registerTab(id, Component)`. Tabs
 * without a renderer attached are hidden — a plugin that declares
 * settings tabs must activate on startup (or another trigger that
 * fires before the user opens settings) for the tab to appear.
 *
 * `group` places the tab in one of three rail sections:
 *   - `options` — bundled app surfaces (Appearance, Hotkeys, …).
 *   - `core-plugins` — in-tree nexus plugins with their own settings.
 *   - `community-plugins` — installed community plugins with settings.
 *
 * When `group` is omitted, community plugins default to
 * `community-plugins`, core plugins to `core-plugins`, and everything
 * else to `options`. `priority` orders within a group (lower first).
 */
export interface SettingsTabContribution {
  id: string;
  title: string;
  icon?: string;
  priority?: number;
  group?: 'options' | 'core-plugins' | 'community-plugins';
}

/**
 * Chrome-only slot identifiers (OI-04 — promoted from
 * `shell/src/registry/SlotRegistry.ts`). Slots are fixed-position
 * regions of the shell (title bar, activity bar, status bar, overlay
 * root) that host plugin-contributed components outside the movable
 * pane model. Movable panes use the Leaf / ViewRegistry surface
 * instead (see `docs/architecture/leaf-architecture.md`).
 *
 * This type lives in the extension-api package so native (Rust) and
 * community (JS) plugins see identical slot names at the contract
 * boundary. The shell-side `SlotRegistry` imports from here rather
 * than re-defining the union.
 */
export type SlotId =
  | 'overlay'
  | 'titleBar'
  | 'activityBar'
  | 'statusBarLeft'
  | 'statusBarRight'
  | 'paneMode';

/**
 * Plugin-contributed view registration (OI-04 — promoted from
 * `shell/src/types/plugin.ts`). `slot` picks one of the chrome slot
 * ids; `priority` orders entries within the slot (lower first).
 */
export interface ViewContribution {
  id: string;
  slot: SlotId;
  title: string;
  priority?: number;
}

// ─── Configuration (moved from shell/src/types/plugin.ts) ────────────────────

/**
 * Topical bucket for the Settings → "Core plugins" rail. Each
 * `ConfigSection` declares which bucket it lives in; the rail groups
 * entries under sub-headers in the order defined here. Plugins that
 * omit `category` (or use an unrecognised value) appear under "Other".
 */
export type PluginCategory =
  | 'ai'
  | 'editor'
  | 'navigation'
  | 'files'
  | 'appearance'
  | 'system'
  | 'other';

export interface ConfigSection {
  pluginId: string;
  title: string;
  order: number;
  schema: ConfigSchema[];
  /** Settings-rail bucket. Defaults to `'other'` when omitted. */
  category?: PluginCategory;
}

export interface ConfigSchema {
  key: string;
  title: string;
  description: string;
  type: 'boolean' | 'string' | 'password' | 'number' | 'select' | 'keybinding';
  default: unknown;
  options?: string[];
  when?: string;
}

// ─── Kernel bridge envelope (moved from shell/src/types/plugin.ts) ───────────

export interface KernelEventEnvelope {
  subscriptionId: string;
  topic: string;
  payload: unknown;
}

// ─── Filesystem API surface (moved from shell/src/types/plugin.ts) ───────────

export interface FileEntry {
  name: string;
  path: string;
  isDirectory: boolean;
}

export interface FsEvent {
  kind: 'created' | 'modified' | 'deleted' | 'renamed';
  path: string;
}

// ─── Platform adapter surface (api.platform.*) ───────────────────────────────
//
// Plugins reach OS-level capabilities (filesystem, dialogs, window controls,
// open-in-default-app) through these typed adapters instead of importing
// `@tauri-apps/*` directly. The shell-side implementation in
// `shell/src/host/PluginAPI.ts` is the chokepoint — `shell/src/host/` is
// permitted to import Tauri primitives, while `shell/src/plugins/` is not
// (WI-23 guardrail).
//
// Naming: `platform` (not `shell`) because the term `shell` is overloaded —
// it already names the plugin host. These APIs wrap OS capabilities, which
// is what `platform` conveys; it also future-proofs if Tauri is ever
// swapped for a different native wrapper or a web shell.

export interface PlatformDirEntry {
  name: string;
  /** True when the entry is a directory; false for files. */
  isDirectory: boolean;
}

export interface PlatformOpenFileOptions {
  /** Optional dialog title shown by the OS picker. */
  title?: string;
  /** When true, the user can pick multiple files. */
  multiple?: boolean;
  /** Pre-fill the picker with this absolute path. */
  defaultPath?: string;
  /** Filter list, e.g. `[{ name: 'Markdown', extensions: ['md'] }]`. */
  filters?: ReadonlyArray<{ name: string; extensions: ReadonlyArray<string> }>;
}

export interface PlatformOpenDirectoryOptions {
  title?: string;
  defaultPath?: string;
  /** When true, allow picking multiple directories. */
  multiple?: boolean;
}

export interface PlatformSaveFileOptions {
  title?: string;
  defaultPath?: string;
  filters?: ReadonlyArray<{ name: string; extensions: ReadonlyArray<string> }>;
}

/**
 * Filesystem operations for script (JS) plugins.
 *
 * **Capability model.** Read methods (`readText`, `readDir`, `exists`)
 * gate on `FsRead`; mutating methods (`writeText`, `mkdir`, `remove`,
 * `rename`) gate on `FsWrite`. Both are checked at the sandbox boundary
 * by `capabilityGuard.METHOD_CAPABILITY_MAP`.
 *
 * **Path semantics.** This surface is a thin adapter over Tauri's
 * `@tauri-apps/plugin-fs`; the shell does **not** confine paths to the
 * active forge root. Whatever the Tauri plugin-fs allowlist permits is
 * what an `FsRead`/`FsWrite`-granted plugin can reach — including
 * absolute paths outside the forge, on platforms / configurations
 * where the allowlist is wide. Plugins that intend to operate only
 * inside the forge should resolve every path against
 * `api.workspace.forgeRoot()` themselves. There is no separate
 * `FsReadExternal` / `FsWriteExternal` distinction at the script-
 * plugin layer (those capabilities exist for WASM plugins that go
 * through the kernel `com.nexus.storage::read_file` /
 * `write_file` IPC, which **is** confined to the forge root and
 * audit-logs traversal attempts — see OI-12 / MICROKERNEL-AUDIT
 * F-6.3.1). Absolute paths are taken at face value here; nothing is
 * silently auto-promoted.
 */
export interface PlatformFsAPI {
  /**
   * Read the file at `path` as UTF-8 text. Requires `FsRead`. The path
   * is **not** confined to the forge — see {@link PlatformFsAPI} for
   * the full path-semantics contract.
   */
  readText(path: string): Promise<string>;
  /**
   * Write UTF-8 `content` to the file at `path`, replacing any
   * existing file. Requires `FsWrite`. The path is **not** confined
   * to the forge — see {@link PlatformFsAPI} for the full
   * path-semantics contract.
   */
  writeText(path: string, content: string): Promise<void>;
  /** List the immediate entries (files + directories) inside `path`. Requires `FsRead`. */
  readDir(path: string): Promise<PlatformDirEntry[]>;
  /** Test whether a file or directory exists at `path`. Requires `FsRead`. */
  exists(path: string): Promise<boolean>;
  /** Create a directory; recursive by default. Requires `FsWrite`. */
  mkdir(path: string, options?: { recursive?: boolean }): Promise<void>;
  /** Delete the file or empty directory at `path`. Requires `FsWrite`. */
  remove(path: string): Promise<void>;
  /** Rename or move `from` → `to`. Requires `FsWrite`. */
  rename(from: string, to: string): Promise<void>;
}

export interface PlatformDialogAPI {
  /**
   * Open a single file picker. Returns the selected absolute path, or null
   * if the user cancelled. Pass `{ multiple: true }` to allow multi-select
   * — the return type widens to `string[] | null`.
   */
  openFile(options?: PlatformOpenFileOptions & { multiple?: false }): Promise<string | null>;
  openFile(options: PlatformOpenFileOptions & { multiple: true }): Promise<string[] | null>;
  /** Open a directory picker. */
  openDirectory(options?: PlatformOpenDirectoryOptions & { multiple?: false }): Promise<string | null>;
  openDirectory(options: PlatformOpenDirectoryOptions & { multiple: true }): Promise<string[] | null>;
  /** Save-as picker. Returns the chosen absolute path, or null if cancelled. */
  saveFile(options?: PlatformSaveFileOptions): Promise<string | null>;
}

export interface PlatformWindowAPI {
  minimize(): Promise<void>;
  /** Toggle between maximized and restored. */
  toggleMaximize(): Promise<void>;
  close(): Promise<void>;
  isMaximized(): Promise<boolean>;
  /**
   * Subscribe to OS-level resize events. Returns an unsubscribe function;
   * also tracked via the plugin's subscription registry so deactivation
   * sweeps it.
   */
  onResize(handler: () => void): Promise<() => void>;
}

export interface PlatformShellAPI {
  /** Open a URL or filesystem path in the user's default handler. */
  openExternal(target: string): Promise<void>;
}

export interface PlatformAPI {
  fs: PlatformFsAPI;
  dialog: PlatformDialogAPI;
  window: PlatformWindowAPI;
  shell: PlatformShellAPI;
}

// ─── URI handler surface (api.uri.*) ─────────────────────────────────────────
//
// WI-13 / Phase 2 §5.3 — replaces the legacy `ctx.ui.registerUriHandler`
// (which exposed an `{ id, scheme, handle }` DTO) with a flat
// `register(scheme, handler)` form that matches the rest of the
// `api.*.register` shape and integrates with `PluginRegistry`'s
// auto-cleanup.

export interface UriAPI {
  /**
   * Register a handler for a custom URI scheme. The handler receives a
   * parsed `URL` when the user opens `<scheme>://...` or the OS routes
   * such a URL into the app via the deep-link bridge.
   *
   * Returns an idempotent unsubscribe; `PluginRegistry` sweeps it on
   * plugin deactivate. Two plugins may not register for the same
   * scheme — the second registration is rejected with a console
   * warning and the returned unsub is a no-op (first-match-wins,
   * matching legacy SI-2).
   */
  register(scheme: string, handler: (url: URL) => void | Promise<void>): () => void;
}

// ─── Sandboxed community plugin surface (WI-30) ───────────────────────
//
// Types for community plugins that run inside a null-origin iframe
// sandbox. The protocol types live here (not shell-side) so the host
// orchestrator (WI-30b) and the plugin bootstrap runtime consume the
// same declarations.
//
// WI-30e: `bootstrapSandboxedPlugin` is also re-exported from the
// barrel so plugin authors can write
//   `import { bootstrapSandboxedPlugin } from '@nexus/extension-api'`
// in their source file. The runtime code itself is only *executed*
// inside the iframe (the host side will never call it), but exporting
// the symbol from the public barrel keeps the author DX a single
// import. Tree-shaking removes it from any host bundle that doesn't
// reference it.

export * from './sandbox/context';
export * from './sandbox/plugin';
export * from './sandbox/protocol';
export { bootstrapSandboxedPlugin } from './sandbox/runtime';
