/**
 * Public TypeScript surface for Nexus script-plugin authors (UI F-2.1.1).
 *
 * ## Versioning
 *
 * This package ships with semver discipline. The `0.x` line mirrors
 * whatever the shell happens to expose today; a `1.0.0` tag signals
 * that every exported shape is frozen and future `1.x` releases add
 * surface but never change existing signatures.
 *
 * ## Runtime
 *
 * This package is **types-only**. Plugins import the shapes from here
 * so TypeScript catches accidental contract drift when the shell is
 * updated, but the `NexusPluginContext` instance passed to
 * `dispatch` / `onInit` / `onStart` / `onStop` at runtime is still
 * supplied by the Nexus host. There is nothing to `new` from this
 * package.
 *
 * ## What's in scope
 *
 * - Every field on `NexusPluginContext`, including subsurface types
 *   (`Disposable`, `DisposableStore`, `DeclaredCapabilities`).
 * - Every contribution DTO the host consumes
 *   (`EditorBlockType`, `EditorDecorationProvider`, `EditorKeybinding`,
 *   `Snippet`, `MenuItem`, `ContextMenuItem`, `UriHandler`,
 *   `WebviewPanelConfig`, `TreeDataProvider`, `TreeNode`, `PanelNode`).
 * - `ScriptPlugin` — the shape a plugin's default export must satisfy.
 *
 * ## What's out of scope
 *
 * - React components. This package has no `react` dependency so plugins
 *   that ship JSX must depend on React themselves.
 * - CM6 extension types. Plugins that contribute editor decorations
 *   still depend on `@codemirror/*` directly — we re-export only the
 *   host-facing `Extension` opaque reference.
 */

// Re-export ts-rs–generated Rust contract types (Capability, IpcError,
// PluginInfo, NexusEvent, …). Generated by `cargo test -p
// nexus-plugin-api --features ts-export`; do not hand-edit the
// `./generated/*.ts` files.
export * from './generated';

/**
 * Versioned plugin ABI marker. Mirrors `PLUGIN_API_VERSION` const in
 * `crates/nexus-plugin-api/src/lib.rs`. Bump in lockstep — ts-rs does
 * not derive consts, so this is hand-authored. WI-20 (later commit)
 * adds a CI check that asserts the values match.
 */
export const PLUGIN_API_VERSION = 1 as const;

export type ToastLevel = "info" | "warn" | "error";

/** Disposal callback — returned from every `register*` API. */
export type Disposable = () => void;

/**
 * Collects disposables and flushes them in LIFO order on plugin stop.
 * The host auto-creates one per plugin and attaches it as
 * `ctx.disposables`; plugins simply call `add(d)` on every register.
 */
export interface DisposableStore {
  add(d: Disposable): Disposable;
  dispose(): void;
  readonly size: number;
}

/** Optional capability-set used by the host to gate context surfaces. */
export type DeclaredCapabilities = ReadonlySet<string> | undefined;

// ─── Editor contributions ────────────────────────────────────────────────────

export interface EditorBlockType {
  id: string;
  label: string;
  icon: string;
  description?: string;
  toMarkdown?: (content: string, attrs?: Record<string, unknown>) => string;
}

/**
 * Opaque CodeMirror 6 extension. Plugins that contribute decorations
 * should import the concrete `Extension` type from `@codemirror/state`
 * for better type inference; this alias exists so the extension-api
 * package stays free of a CM6 peer dependency.
 */
export type EditorExtension = unknown;

export interface EditorDecorationProvider {
  id: string;
  extension: EditorExtension;
}

export interface EditorKeybinding {
  id: string;
  key: string;
  commandId: string;
}

export interface Snippet {
  id: string;
  trigger: string;
  body: string;
  description?: string;
  fileTypes?: string[];
}

// ─── UI contributions ────────────────────────────────────────────────────────

export interface TreeNode {
  id: string;
  label: string;
  icon?: string;
  children?: TreeNode[] | null;
}

export interface TreeDataProvider {
  id: string;
  getChildren(nodeId: string | null): TreeNode[] | Promise<TreeNode[]>;
  onSelect?(nodeId: string, node: TreeNode): void | Promise<void>;
}

export interface WebviewPanelConfig {
  htmlUrl: string;
  allowPopups?: boolean;
}

export interface UriHandler {
  id: string;
  scheme: string;
  handle(url: string): void | Promise<void>;
}

export interface MenuItem {
  id: string;
  label: string;
  commandId: string;
  menu: string;
  separatorBefore?: boolean;
  disabled?: boolean;
  icon?: string;
  order?: number;
  menuOrder?: number;
}

export interface ContextMenuItem {
  id: string;
  label: string;
  commandId: string;
  scopes: string[];
  separatorBefore?: boolean;
  disabled?: boolean;
  icon?: string;
}

// ─── Declarative panel primitives (UI F-5.2.1) ───────────────────────────────

export type PanelNode =
  | { type: "vstack"; gap?: number; children: PanelNode[] }
  | { type: "hstack"; gap?: number; children: PanelNode[] }
  | { type: "text"; value: string; muted?: boolean; strong?: boolean }
  | { type: "heading"; value: string; level?: 1 | 2 | 3 }
  | { type: "button"; label: string; commandId: string; disabled?: boolean }
  | { type: "spacer"; size?: number };

export type PanelRenderFn = () => PanelNode;

// ─── MDX component runtime (PRD-08 §7) ───────────────────────────────────────

/**
 * An MDX component that the editor renders inline when it sees a
 * matching self-closing JSX tag in markdown / MDX files.
 *
 * The host never evaluates plugin-supplied JSX: the attribute list is
 * parsed to a plain object, passed to `render`, and the returned
 * `PanelNode` tree is walked by a host-owned declarative dispatcher.
 * Same trade-off as `registerPanelView` — approved primitives only,
 * no HTML escape hatch.
 *
 * Component names must start with an uppercase letter (JSX tag rule)
 * and match `/^[A-Z][A-Za-z0-9]*$/`.
 */
export interface MdxComponent {
  id: string;
  name: string;
  description?: string;
  render(props: Record<string, unknown>): PanelNode;
}

// ─── Host-provided context ───────────────────────────────────────────────────

export interface NexusPluginContext {
  pluginId: string;

  settings: {
    get(): Promise<Record<string, unknown>>;
  };

  events: {
    emit(typeId: string, payload: unknown): Promise<void>;
  };

  ipc: {
    call(
      targetPluginId: string,
      commandId: string,
      args?: unknown,
    ): Promise<unknown>;
  };

  editor: {
    registerBlockType(type: EditorBlockType): Disposable;
    registerDecorationProvider(provider: EditorDecorationProvider): Disposable;
    registerKeybinding(binding: EditorKeybinding): Disposable;
    registerSnippet(snippet: Snippet): Disposable;
    /**
     * Register an MDX component — the editor scans for matching
     * self-closing JSX tags and renders each as a widget. PRD-08 §7.
     */
    registerMdxComponent(component: MdxComponent): Disposable;
  };

  ui: {
    notify(level: ToastLevel, message: string): void;
    registerTreeDataProvider(
      viewId: string,
      provider: TreeDataProvider,
    ): Disposable;
    registerFileHandler(ext: string, contentTypeId: string): Disposable;
    registerContextMenuItem(item: ContextMenuItem): Disposable;
    registerMenuItem(item: MenuItem): Disposable;
    registerUriHandler(handler: UriHandler): Disposable;
    registerWebviewPanel(viewId: string, config: WebviewPanelConfig): Disposable;
    registerPanelView(viewId: string, render: PanelRenderFn): Disposable;
  };

  workspace: {
    root(): string | null;
    name(): string | null;
  };

  editorActive: {
    relpath(): string | null;
    content(): string | null;
    isDirty(): boolean;
    open(relpath: string): Promise<void>;
  };

  disposables: DisposableStore;
}

// ─── Plugin entry point ──────────────────────────────────────────────────────

/**
 * Shape a script plugin's default export must satisfy. The host calls
 * the lifecycle hooks in this order:
 *
 *   loadScriptPlugin → onInit → onStart → (dispatch…) → onStop
 *
 * Failures in any hook are logged to the Running Extensions settings
 * tab but do not propagate to other plugins — the contribution bridge
 * keeps going with the next plugin in the snapshot.
 */
export interface ScriptPlugin {
  dispatch(
    handlerId: number,
    args: unknown,
    ctx: NexusPluginContext,
  ): unknown | Promise<unknown>;
  onInit?(ctx: NexusPluginContext): void | Promise<void>;
  onStart?(ctx: NexusPluginContext): void | Promise<void>;
  onStop?(ctx: NexusPluginContext): void | Promise<void>;
}

// ─── Contributions (moved from shell/src/types/plugin.ts) ───────────────────
//
// Individual contribution DTOs. `PluginManifest` and the
// `PluginContributions` aggregate intentionally stay shell-side until
// `ViewContribution` (which references `SlotId`) is portable — see
// `shell/src/types/plugin.ts`. WI-24 / Phase 7 will promote slot ids
// into the kernel contract; at that point the manifest aggregate moves
// here and this comment goes away.

export interface CommandContribution {
  id: string;
  title: string;
  category?: string;
  icon?: string;
}

export interface MenuContribution {
  menu: string;
  command: string;
  group?: string;
  order?: number;
  when?: string;
}

export interface KeybindingContribution {
  command: string;
  key: string;
  mac?: string;
  when?: string;
}

export interface StatusBarContribution {
  id: string;
  slot: 'left' | 'right';
  priority: number;
  text: string;
}

export interface ContextKeyContribution {
  key: string;
  description: string;
  type: 'boolean' | 'string' | 'number';
}

/**
 * A plugin-contributed tab in the Settings modal (OI-01).
 *
 * Plugins declare metadata here; the renderer is wired from
 * `activate()` via `api.settings.registerTab(id, Component)`. Tabs
 * without a renderer attached are hidden — a plugin that declares
 * settings tabs must activate on startup (or another trigger that
 * fires before the user opens settings) for the tab to appear.
 *
 * `group` places the tab in one of three rail sections:
 *   - `options` — bundled app surfaces (Appearance, Hotkeys, …).
 *   - `core-plugins` — in-tree nexus plugins with their own settings.
 *   - `community-plugins` — installed community plugins with settings.
 *
 * When `group` is omitted, community plugins default to
 * `community-plugins`, core plugins to `core-plugins`, and everything
 * else to `options`. `priority` orders within a group (lower first).
 */
export interface SettingsTabContribution {
  id: string;
  title: string;
  icon?: string;
  priority?: number;
  group?: 'options' | 'core-plugins' | 'community-plugins';
}

/**
 * Chrome-only slot identifiers (OI-04 — promoted from
 * `shell/src/registry/SlotRegistry.ts`). Slots are fixed-position
 * regions of the shell (title bar, activity bar, status bar, overlay
 * root) that host plugin-contributed components outside the movable
 * pane model. Movable panes use the Leaf / ViewRegistry surface
 * instead (see `docs/leaf-architecture.md`).
 *
 * This type lives in the extension-api package so native (Rust) and
 * community (JS) plugins see identical slot names at the contract
 * boundary. The shell-side `SlotRegistry` imports from here rather
 * than re-defining the union.
 */
export type SlotId =
  | 'overlay'
  | 'titleBar'
  | 'activityBar'
  | 'statusBarLeft'
  | 'statusBarRight'
  | 'paneMode';

/**
 * Plugin-contributed view registration (OI-04 — promoted from
 * `shell/src/types/plugin.ts`). `slot` picks one of the chrome slot
 * ids; `priority` orders entries within the slot (lower first).
 */
export interface ViewContribution {
  id: string;
  slot: SlotId;
  title: string;
  priority?: number;
}

// ─── Configuration (moved from shell/src/types/plugin.ts) ────────────────────

export interface ConfigSection {
  pluginId: string;
  title: string;
  order: number;
  schema: ConfigSchema[];
}

export interface ConfigSchema {
  key: string;
  title: string;
  description: string;
  type: 'boolean' | 'string' | 'number' | 'select' | 'keybinding';
  default: unknown;
  options?: string[];
  when?: string;
}

// ─── Kernel bridge envelope (moved from shell/src/types/plugin.ts) ───────────

export interface KernelEventEnvelope {
  subscriptionId: string;
  topic: string;
  payload: unknown;
}

// ─── Filesystem API surface (moved from shell/src/types/plugin.ts) ───────────

export interface FileEntry {
  name: string;
  path: string;
  isDirectory: boolean;
}

export interface FsEvent {
  kind: 'created' | 'modified' | 'deleted' | 'renamed';
  path: string;
}

// ─── Platform adapter surface (api.platform.*) ───────────────────────────────
//
// Plugins reach OS-level capabilities (filesystem, dialogs, window controls,
// open-in-default-app) through these typed adapters instead of importing
// `@tauri-apps/*` directly. The shell-side implementation in
// `shell/src/host/PluginAPI.ts` is the chokepoint — `shell/src/host/` is
// permitted to import Tauri primitives, while `shell/src/plugins/` is not
// (WI-23 guardrail).
//
// Naming: `platform` (not `shell`) because the term `shell` is overloaded —
// it already names the plugin host. These APIs wrap OS capabilities, which
// is what `platform` conveys; it also future-proofs if Tauri is ever
// swapped for a different native wrapper or a web shell.

export interface PlatformDirEntry {
  name: string;
  /** True when the entry is a directory; false for files. */
  isDirectory: boolean;
}

export interface PlatformOpenFileOptions {
  /** Optional dialog title shown by the OS picker. */
  title?: string;
  /** When true, the user can pick multiple files. */
  multiple?: boolean;
  /** Pre-fill the picker with this absolute path. */
  defaultPath?: string;
  /** Filter list, e.g. `[{ name: 'Markdown', extensions: ['md'] }]`. */
  filters?: ReadonlyArray<{ name: string; extensions: ReadonlyArray<string> }>;
}

export interface PlatformOpenDirectoryOptions {
  title?: string;
  defaultPath?: string;
  /** When true, allow picking multiple directories. */
  multiple?: boolean;
}

export interface PlatformSaveFileOptions {
  title?: string;
  defaultPath?: string;
  filters?: ReadonlyArray<{ name: string; extensions: ReadonlyArray<string> }>;
}

export interface PlatformFsAPI {
  /** Read the file at `path` as UTF-8 text. */
  readText(path: string): Promise<string>;
  /** Write UTF-8 `content` to the file at `path`, replacing any existing file. */
  writeText(path: string, content: string): Promise<void>;
  /** List the immediate entries (files + directories) inside `path`. */
  readDir(path: string): Promise<PlatformDirEntry[]>;
  /** Test whether a file or directory exists at `path`. */
  exists(path: string): Promise<boolean>;
  /** Create a directory; recursive by default. */
  mkdir(path: string, options?: { recursive?: boolean }): Promise<void>;
  /** Delete the file or empty directory at `path`. */
  remove(path: string): Promise<void>;
  /** Rename or move `from` → `to`. */
  rename(from: string, to: string): Promise<void>;
}

export interface PlatformDialogAPI {
  /**
   * Open a single file picker. Returns the selected absolute path, or null
   * if the user cancelled. Pass `{ multiple: true }` to allow multi-select
   * — the return type widens to `string[] | null`.
   */
  openFile(options?: PlatformOpenFileOptions & { multiple?: false }): Promise<string | null>;
  openFile(options: PlatformOpenFileOptions & { multiple: true }): Promise<string[] | null>;
  /** Open a directory picker. */
  openDirectory(options?: PlatformOpenDirectoryOptions & { multiple?: false }): Promise<string | null>;
  openDirectory(options: PlatformOpenDirectoryOptions & { multiple: true }): Promise<string[] | null>;
  /** Save-as picker. Returns the chosen absolute path, or null if cancelled. */
  saveFile(options?: PlatformSaveFileOptions): Promise<string | null>;
}

export interface PlatformWindowAPI {
  minimize(): Promise<void>;
  /** Toggle between maximized and restored. */
  toggleMaximize(): Promise<void>;
  close(): Promise<void>;
  isMaximized(): Promise<boolean>;
  /**
   * Subscribe to OS-level resize events. Returns an unsubscribe function;
   * also tracked via the plugin's subscription registry so deactivation
   * sweeps it.
   */
  onResize(handler: () => void): Promise<() => void>;
}

export interface PlatformShellAPI {
  /** Open a URL or filesystem path in the user's default handler. */
  openExternal(target: string): Promise<void>;
}

export interface PlatformAPI {
  fs: PlatformFsAPI;
  dialog: PlatformDialogAPI;
  window: PlatformWindowAPI;
  shell: PlatformShellAPI;
}

// ─── URI handler surface (api.uri.*) ─────────────────────────────────────────
//
// WI-13 / Phase 2 §5.3 — replaces the legacy `ctx.ui.registerUriHandler`
// (which exposed an `{ id, scheme, handle }` DTO) with a flat
// `register(scheme, handler)` form that matches the rest of the
// `api.*.register` shape and integrates with `PluginRegistry`'s
// auto-cleanup.

export interface UriAPI {
  /**
   * Register a handler for a custom URI scheme. The handler receives a
   * parsed `URL` when the user opens `<scheme>://...` or the OS routes
   * such a URL into the app via the deep-link bridge.
   *
   * Returns an idempotent unsubscribe; `PluginRegistry` sweeps it on
   * plugin deactivate. Two plugins may not register for the same
   * scheme — the second registration is rejected with a console
   * warning and the returned unsub is a no-op (first-match-wins,
   * matching legacy SI-2).
   */
  register(scheme: string, handler: (url: URL) => void | Promise<void>): () => void;
}

// ─── Sandboxed community plugin surface (WI-30) ───────────────────────
//
// Types for community plugins that run inside a null-origin iframe
// sandbox. The protocol types live here (not shell-side) so the host
// orchestrator (WI-30b) and the plugin bootstrap runtime consume the
// same declarations.
//
// WI-30e: `bootstrapSandboxedPlugin` is also re-exported from the
// barrel so plugin authors can write
//   `import { bootstrapSandboxedPlugin } from '@nexus/extension-api'`
// in their source file. The runtime code itself is only *executed*
// inside the iframe (the host side will never call it), but exporting
// the symbol from the public barrel keeps the author DX a single
// import. Tree-shaking removes it from any host bundle that doesn't
// reference it.

export * from './sandbox/context';
export * from './sandbox/plugin';
export * from './sandbox/protocol';
export { bootstrapSandboxedPlugin } from './sandbox/runtime';
