//! Stable event types: `NexusEvent`, `EventMetadata`, `EventFilter`, `StopReason`.

use serde::{Deserialize, Serialize};

use crate::capability::Capability;

/// All events the Nexus kernel knows about.
///
/// This is a closed enum for kernel-owned events plus a single `Custom`
/// variant for plugin-emitted signals. The kernel only defines events it
/// generates itself (plugin lifecycle and capability events). Domain events
/// (file changes, git commits, etc.) are published by core plugins as
/// `Custom` events with namespaced type IDs (e.g., `com.nexus.storage.*`).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
#[cfg_attr(feature = "ts-export", derive(ts_rs::TS))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/"
    )
)]
pub enum NexusEvent {
    // ---- Plugin lifecycle events ----
    /// A plugin has been loaded from disk and its manifest parsed.
    PluginLoaded {
        /// Plugin identifier (reverse-DNS).
        plugin_id: String,
        /// Plugin version from the manifest.
        version: String,
    },
    /// A plugin has started successfully.
    PluginStarted {
        /// Plugin identifier.
        plugin_id: String,
    },
    /// A plugin has been stopped.
    PluginStopped {
        /// Plugin identifier.
        plugin_id: String,
        /// Why the plugin was stopped.
        reason: StopReason,
    },
    /// A plugin crashed during execution.
    PluginCrashed {
        /// Plugin identifier.
        plugin_id: String,
        /// Description of what went wrong.
        error: String,
    },

    // ---- Capability lifecycle events ----
    /// A plugin was granted a capability.
    CapabilityGranted {
        /// Plugin identifier.
        plugin_id: String,
        /// Which capability was granted.
        capability: Capability,
    },
    /// A plugin's capability request was denied.
    CapabilityDenied {
        /// Plugin identifier.
        plugin_id: String,
        /// Which capability was denied.
        capability: Capability,
    },

    // ---- Plugin-emitted custom events ----
    /// A plugin-emitted signal. Anti-spoofing enforced at publish time:
    /// `type_id` must start with the emitting plugin's id, and
    /// `emitting_plugin` is set by the kernel (not the plugin).
    Custom {
        /// Namespaced event type (reverse-DNS).
        type_id: String,
        /// The plugin that emitted this event. Set by the kernel.
        emitting_plugin: String,
        /// Arbitrary payload. Plugins serialize/deserialize with their own types.
        #[cfg_attr(feature = "ts-export", ts(type = "unknown"))]
        payload: serde_json::Value,
    },
}

/// Why a plugin was stopped. Attached to `NexusEvent::PluginStopped`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(ts_rs::TS))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/"
    )
)]
pub enum StopReason {
    /// The user explicitly stopped the plugin via CLI.
    UserRequested,
    /// The plugin is being reloaded from disk (hot-reload).
    HotReload,
    /// The kernel is shutting down.
    Shutdown,
    /// The plugin crashed and is being stopped as part of recovery.
    CrashRecovery,
}

/// Filter applied to an event subscription. Events not matching the filter
/// are silently skipped inside the subscription's `recv()` call.
#[derive(Debug, Clone)]
#[cfg_attr(feature = "ts-export", derive(ts_rs::TS))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/"
    )
)]
pub enum EventFilter {
    /// Match every event on the bus. High-traffic; intended for debug/tracing.
    All,
    /// Match a single kernel-event variant by its name (e.g., `"PluginLoaded"`).
    Variant(String),
    /// Match `NexusEvent::Custom` events whose `type_id` starts with this prefix.
    CustomPrefix(String),
    /// Match exactly one `NexusEvent::Custom` `type_id`.
    CustomExact(String),
}

/// Metadata attached to every published event. Populated by the kernel's
/// `PluginContext` impl when a plugin calls `ctx.publish(...)` — plugins
/// cannot construct this directly.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(ts_rs::TS))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/"
    )
)]
pub struct EventMetadata {
    /// Unique event id, generated by the kernel at publish time.
    pub event_id: uuid::Uuid,
    /// UTC timestamp when the event was published.
    pub timestamp: chrono::DateTime<chrono::Utc>,
    /// Id of the plugin that emitted this event (or `"kernel"` for internal events).
    pub source_plugin_id: String,
    /// `tracing` span id at the time of publish, if a span was active.
    pub span_id: Option<String>,
}

/// An event as it flows through the bus: payload + metadata.
///
/// The bus transports `Arc<PublishedEvent>` to avoid cloning for each subscriber.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(ts_rs::TS))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/"
    )
)]
pub struct PublishedEvent {
    /// Kernel-populated metadata.
    pub metadata: EventMetadata,
    /// The event payload.
    pub event: NexusEvent,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stop_reason_variants_are_distinct() {
        assert_ne!(StopReason::UserRequested, StopReason::HotReload);
        assert_ne!(StopReason::HotReload, StopReason::Shutdown);
        assert_ne!(StopReason::Shutdown, StopReason::CrashRecovery);
    }

    #[test]
    fn stop_reason_serializes_as_variant_name() {
        let json = serde_json::to_string(&StopReason::HotReload).unwrap();
        assert_eq!(json, "\"HotReload\"");
    }

    #[test]
    fn event_filter_is_clone() {
        let f1 = EventFilter::Variant("PluginLoaded".to_string());
        let _f2 = f1.clone();
    }

    #[test]
    fn custom_prefix_stores_string() {
        let filter = EventFilter::CustomPrefix("com.example.".to_string());
        match filter {
            EventFilter::CustomPrefix(p) => assert_eq!(p, "com.example."),
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn plugin_loaded_event_serializes() {
        let event = NexusEvent::PluginLoaded {
            plugin_id: "com.test.plugin".to_string(),
            version: "1.0.0".to_string(),
        };
        let json = serde_json::to_string(&event).unwrap();
        assert!(json.contains("\"type\":\"PluginLoaded\""));
        assert!(json.contains("com.test.plugin"));
    }
}
