// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tab } from "./Tab";

/**
 * Bottom panel (terminal, process manager, diagnostics).
 */
export type BottomPanel = { 
/**
 * Height in pixels.
 */
height: number, 
/**
 * Whether the panel is hidden.
 */
collapsed: boolean, 
/**
 * Tabs inside the panel (terminal, logs, etc.).
 */
tabs: Array<Tab>, };
