// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Orientation of a split node — horizontal (`Row`) or vertical (`Column`).
 */
export type Direction = "row" | "column";
