// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RibbonAction } from "./RibbonAction";

/**
 * A single icon button in a side panel's footer (right-aligned area —
 * help, settings, plugin-contributed actions).
 */
export type FooterAction = { 
/**
 * Stable id (`"workspace.help"`, `"workspace.settings"`, …).
 */
id: string, 
/**
 * Icon id resolved by the UI.
 */
icon: string, 
/**
 * Hover tooltip and accessible label.
 */
tooltip: string, 
/**
 * What clicking the item does.
 */
action: RibbonAction, 
/**
 * Owning plugin id. `None` for core.
 */
plugin?: string | null, };
