// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direction } from "./Direction";
import type { PaneId } from "./PaneId";
import type { Tab } from "./Tab";
import type { TabId } from "./TabId";

/**
 * One node in the workspace layout tree.
 *
 * Serializes with a `"type"` discriminator matching the TypeScript union
 * in PRD §5.1 (`"split"` or `"leaf"`).
 */
export type LayoutNode = { "type": "split", 
/**
 * Stable id for this split.
 */
id: PaneId, 
/**
 * Orientation of the split.
 */
direction: Direction, 
/**
 * Child nodes, left-to-right or top-to-bottom.
 */
children: Array<LayoutNode>, 
/**
 * Proportional sizes; `sizes[i]` is `children[i]`'s share of the
 * parent axis. Sum normalised to ~1.0.
 */
sizes: Array<number>, } | { "type": "leaf", 
/**
 * Stable id for this leaf.
 */
id: PaneId, 
/**
 * Currently-focused tab within this leaf.
 */
activeTabId?: TabId | null, 
/**
 * Tabs in display order.
 */
tabs: Array<Tab>, 
/**
 * When true, the pane is hidden but its size in the layout is
 * preserved (see PRD §6.4).
 */
collapsed: boolean, 
/**
 * Minimum size in pixels along the parent axis.
 */
minSize?: number | null, };
