// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Discovery metadata for the layout file.
 */
export type LayoutMetadata = { 
/**
 * ISO 8601 creation timestamp.
 */
createdAt: string, 
/**
 * ISO 8601 last-modified timestamp; bumped on every mutation.
 */
lastModified: string, 
/**
 * Window width at last save.
 */
width: number, 
/**
 * Window height at last save.
 */
height: number, };
