// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RibbonAction } from "./RibbonAction";

/**
 * One action icon in a panel's local toolbar (sort, filter, search,
 * view-mode, …).
 *
 * Shape mirrors [`RibbonItem`]; the same [`RibbonAction`] variants apply
 * since clicking a toolbar icon is conceptually the same dispatch —
 * "toggle a sub-panel", "invoke a command", or "open a view".
 */
export type PanelToolbarItem = { 
/**
 * Stable id (`"outline.collapse-all"`, `"tags.sort-asc"`, …).
 */
id: string, 
/**
 * Icon id resolved by the UI.
 */
icon: string, 
/**
 * Hover tooltip and accessible label.
 */
tooltip: string, 
/**
 * What clicking the item does.
 */
action: RibbonAction, 
/**
 * Owning plugin id. `None` for core.
 */
plugin?: string | null, };
