// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Origin tag for a registered preset.
 */
export type PresetSourceKind = "embedded" | "user" | "plugin";
