// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresetSourceKind } from "./PresetSourceKind";

/**
 * Summary metadata for a registered preset; returned by
 * [`PresetRegistry::list`] so UIs can show a picker without parsing every
 * file.
 */
export type PresetInfo = { 
/**
 * Stable id for lookup.
 */
id: string, 
/**
 * User-visible name.
 */
name: string, 
/**
 * Description if provided by the preset.
 */
description: string | null, 
/**
 * Where this preset came from.
 */
source: PresetSourceKind, };
