// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a ribbon icon does when clicked.
 *
 * Ribbon items are references: `command` / `view_id` are resolved at runtime
 * through a UI contribution registry that core and plugins populate. The
 * data model never owns the *meaning* of an id — only the list of items to
 * show.
 */
export type RibbonAction = { "kind": "togglePanel", 
/**
 * Target panel id (matches [`SidebarPanel::id`]).
 */
panelId: string, } | { "kind": "invokeCommand", 
/**
 * Command id (`"workspace.new-note"`, `"git.commit"`, …).
 */
command: string, } | { "kind": "openView", 
/**
 * View id registered by core or a plugin.
 */
viewId: string, };
