// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RibbonAction } from "./RibbonAction";

/**
 * A single icon on the workspace's activity ribbon (the narrow icon rail
 * docked at the far-left edge of the window, independent of either side
 * panel).
 *
 * Ribbon items are just references — the icon to render, the tooltip to
 * show, and the action to dispatch. The actual implementation lives in the
 * UI contribution registry.
 */
export type RibbonItem = { 
/**
 * Stable id of this ribbon entry (`"explorer"`, `"git.status"`, …).
 */
id: string, 
/**
 * Icon id resolved by the UI.
 */
icon: string, 
/**
 * Hover tooltip and accessible label.
 */
tooltip: string, 
/**
 * What clicking the item does.
 */
action: RibbonAction, 
/**
 * Owning plugin id, if the item came from a plugin. `None` for core.
 */
plugin?: string | null, };
