// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Panel } from "./Panel";
import type { SidePanelFooter } from "./SidePanelFooter";
import type { SidePanelSide } from "./SidePanelSide";

/**
 * A docked side panel (left or right).
 *
 * A side panel has three stacked surfaces:
 *
 *   1. **Panel-selector toolbar** — derived from [`Self::panels`]; rendered
 *      horizontally at the top. Clicking a selector toggles that panel's
 *      [`Panel::visible`] flag.
 *   2. **Panel-local toolbar** — [`Panel::toolbar`] of the active panel.
 *   3. **Content** — [`Panel::content_type`] of the active panel.
 *
 * The activity ribbon is *not* part of the side panel — it lives on
 * [`WorkspaceLayout::ribbon`] as a workspace-level concern.
 */
export type SidePanel = { 
/**
 * Which side this side panel lives on.
 */
side: SidePanelSide, 
/**
 * Width in pixels when expanded.
 */
width: number, 
/**
 * Side panel is fully hidden.
 */
collapsed: boolean, 
/**
 * Show icons only (no titles).
 */
miniMode: boolean, 
/**
 * Registered panels. Each contributes one entry to the top selector
 * toolbar and, when active, its own [`Panel::toolbar`] + content.
 */
panels: Array<Panel>, 
/**
 * Panel ids in display order.
 */
panelOrder: Array<string>, 
/**
 * Optional footer pinned at the bottom (forge selector + actions).
 * Typically only set on the left side panel.
 */
footer?: SidePanelFooter | null, };
