// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PanelToolbarItem } from "./PanelToolbarItem";

/**
 * One panel within a sidebar (Explorer, Search, Outline, …).
 *
 * A panel has three surfaces (PRD §8, matching the Obsidian reference):
 *
 * 1. **Selector** in the ribbon — toggles visibility. Owned by the sidebar.
 * 2. **Toolbar** ([`Self::toolbar`]) — panel-local action icons rendered
 *    above the content. Owned by this panel's contributing plugin.
 * 3. **Content** ([`Self::content_type`]) — the React component registered
 *    under that id in the UI contribution registry. Owned by this panel's
 *    contributing plugin.
 *
 * The data model only carries references; the UI contribution registry
 * (landing with §8 / §13) resolves icons, toolbar actions, and content
 * components at runtime.
 */
export type SidebarPanel = { 
/**
 * Panel id (`"explorer"`, `"search"`, …).
 */
id: string, 
/**
 * Human-readable title.
 */
title: string, 
/**
 * Icon id.
 */
icon: string, 
/**
 * Owning plugin id, if the panel came from a plugin.
 */
plugin?: string | null, 
/**
 * Whether the panel is currently shown.
 */
visible: boolean, 
/**
 * Panel-local toolbar items rendered above the content area. Empty
 * for panels that don't need controls (Explorer, Bookmarks, …).
 */
toolbar: Array<PanelToolbarItem>, 
/**
 * Content-component id resolved by the UI contribution registry.
 * `None` for panels whose content is rendered by core (legacy) or
 * that only exist as placeholders.
 */
contentType?: string | null, };
