// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SidebarPanel } from "./SidebarPanel";
import type { SidebarSide } from "./SidebarSide";

/**
 * A docked sidebar (left or right).
 */
export type Sidebar = { 
/**
 * Which side this sidebar lives on.
 */
side: SidebarSide, 
/**
 * Width in pixels when expanded.
 */
width: number, 
/**
 * Sidebar is fully hidden.
 */
collapsed: boolean, 
/**
 * Show icons only (no titles).
 */
miniMode: boolean, 
/**
 * Registered panels.
 */
panels: Array<SidebarPanel>, 
/**
 * Panel ids in display order.
 */
panelOrder: Array<string>, };
