// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FooterAction } from "./FooterAction";

/**
 * Footer row pinned to the bottom of a side panel. Typically only the
 * left side panel carries one (forge switcher + help + settings).
 */
export type SidePanelFooter = { 
/**
 * Show the forge / workspace switcher on the left of the footer
 * row. The active forge name is filled in at runtime — the preset
 * just opts in.
 */
showForgeSelector: boolean, 
/**
 * Right-aligned action icons (core ships help + settings; plugins
 * can append more).
 */
actions: Array<FooterAction>, };
