// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RibbonItem } from "./RibbonItem";
import type { SidebarPanel } from "./SidebarPanel";
import type { SidebarSide } from "./SidebarSide";

/**
 * A docked sidebar (left or right).
 *
 * A sidebar has two independent surfaces (per PRD §8 and the Obsidian
 * reference): the narrow **ribbon** of icons at the docked edge, and the
 * wider **panel area** that shows the currently-selected panel's content.
 * Clicking a ribbon item typically toggles a panel, but plugins can also
 * register ribbon items that invoke commands or open views — see
 * [`RibbonAction`].
 */
export type Sidebar = { 
/**
 * Which side this sidebar lives on.
 */
side: SidebarSide, 
/**
 * Width in pixels when expanded.
 */
width: number, 
/**
 * Sidebar is fully hidden.
 */
collapsed: boolean, 
/**
 * Show icons only (no titles).
 */
miniMode: boolean, 
/**
 * Ribbon items (narrow icon rail at the docked edge). Contributed by
 * core or plugins; resolved through the UI contribution registry.
 */
ribbon: Array<RibbonItem>, 
/**
 * Registered panels shown in the wide panel area.
 */
panels: Array<SidebarPanel>, 
/**
 * Panel ids in display order.
 */
panelOrder: Array<string>, };
