// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One panel within a sidebar (Explorer, Search, Outline, …).
 */
export type SidebarPanel = { 
/**
 * Panel id (`"explorer"`, `"search"`, …).
 */
id: string, 
/**
 * Human-readable title.
 */
title: string, 
/**
 * Icon id.
 */
icon: string, 
/**
 * Owning plugin id, if the panel came from a plugin.
 */
plugin?: string | null, 
/**
 * Whether the panel is currently shown.
 */
visible: boolean, };
