// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RibbonAction } from "./RibbonAction";

/**
 * Floating status bar entry rendered at the bottom-right of the
 * workspace. Mixes counters (`text` only), icon-only actions (`icon` +
 * `action`), and combined items.
 */
export type StatusBarItem = { 
/**
 * Stable id (`"editor.word-count"`, `"sync.status"`, …).
 */
id: string, 
/**
 * Text shown to the right of the icon, if any (`"2,348 words"`).
 */
text?: string | null, 
/**
 * Icon id, if any.
 */
icon?: string | null, 
/**
 * Click action. `None` makes the item non-interactive (counter).
 */
action?: RibbonAction | null, 
/**
 * Owning plugin id. `None` for core.
 */
plugin?: string | null, };
