// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which kind of content a tab shows.
 */
export type Surface = "editor" | "preview" | "terminal" | "sidepanel" | "custom";
