// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Surface } from "./Surface";
import type { TabId } from "./TabId";

/**
 * A single tab inside a leaf pane or bottom panel.
 */
export type Tab = { 
/**
 * Stable tab id.
 */
id: TabId, 
/**
 * Display label (file name, "Terminal", …).
 */
label: string, 
/**
 * Optional icon id for the tab bar.
 */
icon?: string | null, 
/**
 * What kind of content this tab shows.
 */
surface: Surface, 
/**
 * Pinned tabs are non-closable and render before unpinned ones.
 */
pinned: boolean, 
/**
 * Content locator (e.g. `file:///…`, `terminal://0`).
 */
contentType: string, 
/**
 * Unsaved-changes indicator.
 */
isDirty: boolean, };
