// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Branded identifier for a tab. Serializes as a bare string.
 */
export type TabId = string;
