// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Broad category for a theme — used for filtering in the picker UI.
 */
export type ThemeCategory = "light" | "dark" | "sepia" | "high-contrast" | "custom";
