// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which light/dark mode the UI is in. The resolver may use this to decide
 * whether a [`crate::CssSnippet`] applies.
 */
export type ThemeMode = "light" | "dark" | "system";
