// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThemeCategory } from "./ThemeCategory";

/**
 * Compact theme description returned by listing APIs — matches PRD §10.1
 * `ThemeMetadata`.
 */
export type ThemeMetadata = { 
/**
 * Theme id (directory stem / built-in constant).
 */
id: string, 
/**
 * Display name.
 */
name: string, 
/**
 * Theme author.
 */
author: string, 
/**
 * Short description.
 */
description: string, 
/**
 * Category for filtering (light/dark/etc.).
 */
category: ThemeCategory, 
/**
 * Whether the theme is bundled with the engine.
 */
builtin: boolean, 
/**
 * Search keywords from `[tags]`.
 */
keywords: Array<string>, };
