// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BottomPanel } from "./BottomPanel";
import type { LayoutMetadata } from "./LayoutMetadata";
import type { LayoutNode } from "./LayoutNode";
import type { PaneId } from "./PaneId";
import type { RibbonItem } from "./RibbonItem";
import type { SidePanel } from "./SidePanel";
import type { StatusBarItem } from "./StatusBarItem";

/**
 * Top-level workspace layout: root tree + side panels + bottom panel + ribbon + metadata.
 */
export type WorkspaceLayout = { 
/**
 * Layout id (stable across saves).
 */
id: string, 
/**
 * User-visible name (e.g. "Coding", "Writing").
 */
name: string, 
/**
 * Schema version (currently `"1.0"`).
 */
version: string, 
/**
 * Root of the pane tree.
 */
root: LayoutNode, 
/**
 * Workspace activity ribbon (the far-left vertical rail). Contains
 * plugin/view shortcuts (graph, calendar, terminal, …), *not* side
 * panel selectors — those are derived from each side panel's own
 * [`Panel`] list.
 */
ribbon: Array<RibbonItem>, 
/**
 * Floating status-bar items rendered at the bottom-right of the
 * workspace. Counters, sync status, plugin-contributed badges, etc.
 */
statusBar: Array<StatusBarItem>, 
/**
 * Left dock.
 */
leftSidePanel: SidePanel, 
/**
 * Right dock.
 */
rightSidePanel: SidePanel, 
/**
 * Bottom panel.
 */
bottomPanel: BottomPanel, 
/**
 * Id of the pane receiving keyboard focus.
 */
focusedPaneId?: PaneId | null, 
/**
 * Discovery metadata.
 */
metadata: LayoutMetadata, };
