// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BottomPanel } from "./BottomPanel";
import type { LayoutMetadata } from "./LayoutMetadata";
import type { LayoutNode } from "./LayoutNode";
import type { PaneId } from "./PaneId";
import type { Sidebar } from "./Sidebar";

/**
 * Top-level workspace layout: root tree + sidebars + bottom panel + metadata.
 */
export type WorkspaceLayout = { 
/**
 * Layout id (stable across saves).
 */
id: string, 
/**
 * User-visible name (e.g. "Coding", "Writing").
 */
name: string, 
/**
 * Schema version (currently `"1.0"`).
 */
version: string, 
/**
 * Root of the pane tree.
 */
root: LayoutNode, 
/**
 * Left dock.
 */
leftSidebar: Sidebar, 
/**
 * Right dock.
 */
rightSidebar: Sidebar, 
/**
 * Bottom panel.
 */
bottomPanel: BottomPanel, 
/**
 * Id of the pane receiving keyboard focus.
 */
focusedPaneId?: PaneId | null, 
/**
 * Discovery metadata.
 */
metadata: LayoutMetadata, };
