// src/host/KernelIpcError.ts
// Typed wrapper around the Rust-side `IpcErrorEnvelope` returned by
// `kernel_invoke`. Plugins that want to react to specific failure modes
// (e.g. retrying on `kind === 'timeout'`) catch this class instead of
// string-sniffing `error.message`.

import type { IpcErrorEnvelope, IpcErrorKind } from '@nexus/extension-api'

/**
 * Thrown by `api.kernel.invoke` when the bridge returns an error envelope.
 * Wraps the Rust-side `IpcErrorEnvelope` so plugin code can branch on
 * `err.kind` instead of parsing strings.
 *
 * The envelope is generated by ts-rs from the Rust `IpcErrorEnvelope`
 * struct (see `crates/nexus-plugin-api/src/error.rs`); fields land on the
 * JS side in snake_case (`plugin_id`, `retryable`). This class normalizes
 * them to camelCase property names that match the rest of the host API.
 */
export class KernelIpcError extends Error {
  readonly kind: IpcErrorKind
  readonly pluginId: string
  readonly command: string
  readonly retryable: boolean

  constructor(envelope: IpcErrorEnvelope) {
    super(envelope.message)
    this.name = 'KernelIpcError'
    this.kind = envelope.kind
    this.pluginId = envelope.plugin_id
    this.command = envelope.command
    this.retryable = envelope.retryable
  }

  /**
   * Best-effort detection: returns true if `err` looks like a serialized
   * `IpcErrorEnvelope` from Tauri. Tauri serializes a Rust `Err(struct)`
   * into a plain JS object (snake_case fields preserved), so we duck-type
   * on the required envelope fields rather than relying on `instanceof`.
   */
  static isEnvelope(err: unknown): err is IpcErrorEnvelope {
    return (
      typeof err === 'object' &&
      err !== null &&
      'kind' in err &&
      'plugin_id' in err &&
      'command' in err &&
      'message' in err &&
      'retryable' in err
    )
  }
}
