//! Episodic memory — time-ordered agent event log.
//!
//! Episodic memory records specific past events: conversation turns,
//! tool calls, observations, and session boundaries. Each entry is
//! a timestamped, session-linked record stored in a bounded ring so
//! the in-process store does not grow unbounded across a long-lived
//! process.
//!
//! Phase 1 ships an in-memory bounded ring. Phase 5 wires persistence
//! to `<forge>/.forge/memory/episodic.db` so events survive across
//! process restarts and can be queried by sessions that predate the
//! current run.

use std::collections::VecDeque;
use std::sync::{Arc, Mutex};

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Default maximum entries retained in the in-memory ring.
pub const DEFAULT_EPISODIC_CAPACITY: usize = 4096;

/// Opaque identifier for an [`EpisodicEntry`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EpisodicId(Uuid);

impl EpisodicId {
    /// Allocate a fresh random episodic id.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }

    /// Inner UUID value.
    #[must_use]
    pub fn as_uuid(self) -> Uuid {
        self.0
    }
}

impl Default for EpisodicId {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Display for EpisodicId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}

/// Discriminant for an [`EpisodicEntry`]. Determines how the context
/// builder (Move 5) weights and selects entries when building the
/// model's context window.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EpisodicKind {
    /// A message sent by the user.
    UserMessage,
    /// A response generated by the model.
    AssistantMessage,
    /// A tool/capability call the model made.
    ToolCall,
    /// The result returned by a tool/capability call.
    ToolResult,
    /// An observation recorded by the session worker after an action.
    Observation,
    /// A session lifecycle event (session started).
    SessionStart,
    /// A session lifecycle event (session ended, with outcome).
    SessionEnd,
}

/// One time-stamped event in episodic memory.
///
/// The `content` field carries the event-specific payload as a
/// `serde_json::Value` so the store doesn't need to know the inner
/// shape of every event kind. Callers should document their payload
/// shapes in the variant they use.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EpisodicEntry {
    /// Unique identifier.
    pub id: EpisodicId,
    /// Session this event belongs to. `None` for process-global events.
    pub session_id: Option<Uuid>,
    /// What kind of event this is.
    pub kind: EpisodicKind,
    /// Event-specific payload.
    pub content: serde_json::Value,
    /// When the event occurred.
    pub occurred_at: DateTime<Utc>,
}

impl EpisodicEntry {
    /// Construct an entry for a specific session.
    #[must_use]
    pub fn for_session(session_id: Uuid, kind: EpisodicKind, content: serde_json::Value) -> Self {
        Self {
            id: EpisodicId::new(),
            session_id: Some(session_id),
            kind,
            content,
            occurred_at: Utc::now(),
        }
    }

    /// Construct a process-global entry (no session context).
    #[must_use]
    pub fn global(kind: EpisodicKind, content: serde_json::Value) -> Self {
        Self {
            id: EpisodicId::new(),
            session_id: None,
            kind,
            content,
            occurred_at: Utc::now(),
        }
    }
}

/// Bounded in-memory episodic event log.
///
/// Thread-safe and `Clone`-able (both clone the same backing `Arc`).
/// When `capacity` is reached, the oldest entry is dropped. Phase 5
/// wires a SQLite persistence layer beneath this so overflow entries
/// are archived rather than discarded.
#[derive(Clone, Debug)]
pub struct EpisodicStore {
    inner: Arc<Mutex<VecDeque<EpisodicEntry>>>,
    capacity: usize,
}

impl EpisodicStore {
    /// Create a store with the given capacity.
    #[must_use]
    pub fn new(capacity: usize) -> Self {
        Self {
            inner: Arc::new(Mutex::new(VecDeque::with_capacity(capacity.min(256)))),
            capacity,
        }
    }

    /// Record a new entry. Drops the oldest entry if at capacity.
    pub fn record(&self, entry: EpisodicEntry) {
        let mut g = self.inner.lock().expect("episodic store poisoned");
        if g.len() == self.capacity {
            g.pop_front();
        }
        g.push_back(entry);
    }

    /// All entries for `session_id` in chronological order.
    #[must_use]
    pub fn session_history(&self, session_id: Uuid) -> Vec<EpisodicEntry> {
        self.inner
            .lock()
            .expect("episodic store poisoned")
            .iter()
            .filter(|e| e.session_id == Some(session_id))
            .cloned()
            .collect()
    }

    /// Most recent `limit` entries across all sessions, newest last.
    #[must_use]
    pub fn recent(&self, limit: usize) -> Vec<EpisodicEntry> {
        let g = self.inner.lock().expect("episodic store poisoned");
        let skip = g.len().saturating_sub(limit);
        g.iter().skip(skip).cloned().collect()
    }

    /// Total entries currently retained.
    #[must_use]
    pub fn len(&self) -> usize {
        self.inner.lock().expect("episodic store poisoned").len()
    }

    /// `true` when no entries are stored.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

impl Default for EpisodicStore {
    fn default() -> Self {
        Self::new(DEFAULT_EPISODIC_CAPACITY)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn user_msg(sid: Uuid, text: &str) -> EpisodicEntry {
        EpisodicEntry::for_session(
            sid,
            EpisodicKind::UserMessage,
            serde_json::json!({ "text": text }),
        )
    }

    #[test]
    fn record_and_session_history_round_trips() {
        let store = EpisodicStore::new(16);
        let sid = Uuid::new_v4();
        store.record(user_msg(sid, "hello"));
        store.record(user_msg(sid, "world"));
        let hist = store.session_history(sid);
        assert_eq!(hist.len(), 2);
        assert_eq!(hist[0].content["text"], "hello");
        assert_eq!(hist[1].content["text"], "world");
    }

    #[test]
    fn session_history_isolates_sessions() {
        let store = EpisodicStore::new(16);
        let sid_a = Uuid::new_v4();
        let sid_b = Uuid::new_v4();
        store.record(user_msg(sid_a, "a"));
        store.record(user_msg(sid_b, "b"));
        assert_eq!(store.session_history(sid_a).len(), 1);
        assert_eq!(store.session_history(sid_b).len(), 1);
    }

    #[test]
    fn capacity_drops_oldest_entry() {
        let store = EpisodicStore::new(3);
        let sid = Uuid::new_v4();
        for i in 0..5u32 {
            store.record(user_msg(sid, &i.to_string()));
        }
        assert_eq!(store.len(), 3);
        let hist = store.session_history(sid);
        // Oldest two dropped; remaining are "2", "3", "4".
        assert_eq!(hist[0].content["text"], "2");
        assert_eq!(hist[2].content["text"], "4");
    }

    #[test]
    fn recent_returns_newest_n_entries() {
        let store = EpisodicStore::new(16);
        let sid = Uuid::new_v4();
        for i in 0..6u32 {
            store.record(user_msg(sid, &i.to_string()));
        }
        let recent = store.recent(3);
        assert_eq!(recent.len(), 3);
        assert_eq!(recent[0].content["text"], "3");
        assert_eq!(recent[2].content["text"], "5");
    }

    #[test]
    fn global_entry_has_no_session_id() {
        let store = EpisodicStore::new(16);
        let e = EpisodicEntry::global(EpisodicKind::SessionStart, serde_json::json!({}));
        assert!(e.session_id.is_none());
        store.record(e);
        assert_eq!(store.len(), 1);
        // Does not appear in any session history.
        assert_eq!(store.session_history(Uuid::new_v4()).len(), 0);
    }
}
