// BL-142 Phase 3 — Settings → REPL Kernels tab.
//
// A friendlier surface over the `nexus.editor.replKernels` config
// key (which is stored as a JSON string). Renders the map as a
// list of (language, command) rows with Add / Remove / Edit
// affordances; Save serialises the rows back through `configStore.set`.
//
// The Phase 2a JSON-string schema entry stays the source of truth —
// any other surface that already binds to `nexus.editor.replKernels`
// (the autogenerated Settings UI, raw `app.toml` edits, future
// per-plugin overrides) keeps working unchanged.

import { useEffect, useMemo, useState } from 'react'

import { configStore, useConfigValue } from '../../../stores/configStore'
import {
  CONFIG_REPL_KERNELS,
  REPL_KERNELS_DEFAULT_JSON,
} from './replKernels'
import {
  blankRow,
  jsonFromRows,
  rowIsValid,
  rowsAreSavable,
  rowsFromJson,
  type KernelRow,
} from './replKernelsTabModel'

/** Suggested kernel commands the user can pick from a datalist —
 *  doesn't lock anything in, just speeds up the common case. The
 *  Phase 2a docs recommend these three. */
const COMMAND_SUGGESTIONS: Record<string, string> = {
  python: 'python3 -i',
  node: 'node --interactive',
  ruby: 'irb',
  deno: 'deno repl',
  bash: 'bash -i',
}

export function ReplKernelsTab() {
  const persistedJson = useConfigValue<string>(
    CONFIG_REPL_KERNELS,
    REPL_KERNELS_DEFAULT_JSON,
  )

  // Local draft state. We hydrate from `persistedJson` on mount and
  // whenever the persisted value changes from underneath us (e.g. a
  // forge switch or a raw `app.toml` edit). Avoid clobbering an
  // in-progress edit: only re-hydrate when the persisted JSON's
  // canonical form differs from what we last saved.
  const [rows, setRows] = useState<KernelRow[]>(() =>
    rowsFromJson(persistedJson),
  )
  const [savedCanonical, setSavedCanonical] = useState<string>(() =>
    jsonFromRows(rowsFromJson(persistedJson)),
  )

  useEffect(() => {
    const incoming = jsonFromRows(rowsFromJson(persistedJson))
    if (incoming !== savedCanonical) {
      setRows(rowsFromJson(persistedJson))
      setSavedCanonical(incoming)
    }
  }, [persistedJson, savedCanonical])

  const currentCanonical = useMemo(() => jsonFromRows(rows), [rows])
  const dirty = currentCanonical !== savedCanonical
  const savable = rowsAreSavable(rows)

  // Surface duplicate-lang collisions so the user knows Save would
  // drop one of their entries. Computed independently of `savable`
  // so we can show the specific message.
  const duplicates = useMemo(() => {
    const seen = new Set<string>()
    const dupes = new Set<string>()
    for (const r of rows) {
      const lang = r.lang.trim()
      const cmd = r.command.trim()
      if (lang.length === 0 || cmd.length === 0) continue
      if (seen.has(lang)) dupes.add(lang)
      seen.add(lang)
    }
    return dupes
  }, [rows])

  const updateRow = (id: string, patch: Partial<KernelRow>) => {
    setRows((prev) => prev.map((r) => (r.id === id ? { ...r, ...patch } : r)))
  }

  const removeRow = (id: string) => {
    setRows((prev) => prev.filter((r) => r.id !== id))
  }

  const addRow = () => {
    setRows((prev) => [...prev, blankRow()])
  }

  const onSave = () => {
    if (!savable) return
    configStore.set(CONFIG_REPL_KERNELS, currentCanonical)
    setSavedCanonical(currentCanonical)
  }

  const onReset = () => {
    setRows(rowsFromJson(persistedJson))
    setSavedCanonical(jsonFromRows(rowsFromJson(persistedJson)))
  }

  return (
    <div className="repl-kernels-tab" data-testid="repl-kernels-tab">
      <h3 style={{ marginTop: 0 }}>REPL kernels</h3>
      <p className="settings-help" style={{ marginBottom: '1rem' }}>
        Map a language tag (e.g. <code>python</code>, <code>node</code>) to the
        shell command that launches its REPL. The mapping powers the Run
        gutter (<span aria-hidden>▶</span>) and the <code>Shift-Enter</code>{' '}
        keybinding on <code>```python repl</code>-style fenced code blocks.
      </p>

      {rows.length === 0 && (
        <p className="settings-empty" data-testid="repl-kernels-empty">
          No kernels configured. REPL execution is inert until at least one
          kernel is added.
        </p>
      )}

      {rows.length > 0 && (
        <table
          style={{ width: '100%', borderCollapse: 'collapse' }}
          data-testid="repl-kernels-table"
        >
          <thead>
            <tr
              style={{
                textAlign: 'left',
                borderBottom: '1px solid var(--nexus-color-border)',
              }}
            >
              <th style={{ padding: '0.4rem 0.5rem', width: '30%' }}>
                Language
              </th>
              <th style={{ padding: '0.4rem 0.5rem' }}>Kernel command</th>
              <th style={{ padding: '0.4rem 0.5rem', width: '3rem' }}></th>
            </tr>
          </thead>
          <tbody>
            {rows.map((row) => {
              const trimmedLang = row.lang.trim()
              const isDup = duplicates.has(trimmedLang)
              const valid = rowIsValid(row)
              return (
                <tr
                  key={row.id}
                  data-testid={`repl-kernel-row`}
                  style={{
                    borderBottom: '1px solid var(--nexus-color-border-subtle)',
                  }}
                >
                  <td style={{ padding: '0.3rem 0.5rem' }}>
                    <input
                      type="text"
                      value={row.lang}
                      placeholder="python"
                      aria-label="Language tag"
                      data-testid="repl-kernel-lang"
                      onChange={(e) => updateRow(row.id, { lang: e.target.value })}
                      style={{
                        width: '100%',
                        boxSizing: 'border-box',
                        borderColor: isDup
                          ? 'var(--nexus-color-danger)'
                          : undefined,
                      }}
                    />
                  </td>
                  <td style={{ padding: '0.3rem 0.5rem' }}>
                    <input
                      type="text"
                      value={row.command}
                      list={`repl-cmd-suggest-${row.id}`}
                      placeholder={
                        COMMAND_SUGGESTIONS[trimmedLang] ?? 'python3 -i'
                      }
                      aria-label="Kernel command"
                      data-testid="repl-kernel-command"
                      onChange={(e) =>
                        updateRow(row.id, { command: e.target.value })
                      }
                      style={{ width: '100%', boxSizing: 'border-box' }}
                    />
                    <datalist id={`repl-cmd-suggest-${row.id}`}>
                      {Object.values(COMMAND_SUGGESTIONS).map((cmd) => (
                        <option key={cmd} value={cmd} />
                      ))}
                    </datalist>
                  </td>
                  <td style={{ padding: '0.3rem 0.5rem', textAlign: 'right' }}>
                    <button
                      type="button"
                      aria-label={`Remove ${trimmedLang || 'row'}`}
                      data-testid="repl-kernel-remove"
                      onClick={() => removeRow(row.id)}
                      title="Remove this kernel"
                      style={{
                        background: 'transparent',
                        border: 'none',
                        cursor: 'pointer',
                        color: 'var(--nexus-color-muted)',
                        fontSize: '1.1rem',
                        padding: '0.1rem 0.4rem',
                      }}
                    >
                      ×
                    </button>
                    {!valid && (
                      <div
                        style={{
                          fontSize: '0.75rem',
                          color: 'var(--nexus-color-muted)',
                          marginTop: '0.15rem',
                        }}
                      >
                        incomplete
                      </div>
                    )}
                    {isDup && (
                      <div
                        style={{
                          fontSize: '0.75rem',
                          color: 'var(--nexus-color-danger)',
                          marginTop: '0.15rem',
                        }}
                      >
                        duplicate
                      </div>
                    )}
                  </td>
                </tr>
              )
            })}
          </tbody>
        </table>
      )}

      <div style={{ marginTop: '0.75rem' }}>
        <button
          type="button"
          onClick={addRow}
          data-testid="repl-kernel-add"
          style={{
            background: 'transparent',
            border: '1px dashed var(--nexus-color-border)',
            padding: '0.35rem 0.75rem',
            cursor: 'pointer',
          }}
        >
          + Add kernel
        </button>
      </div>

      <div
        style={{
          marginTop: '1rem',
          display: 'flex',
          gap: '0.5rem',
          alignItems: 'center',
        }}
      >
        <button
          type="button"
          onClick={onSave}
          disabled={!dirty || !savable}
          data-testid="repl-kernels-save"
        >
          Save
        </button>
        <button
          type="button"
          onClick={onReset}
          disabled={!dirty}
          data-testid="repl-kernels-reset"
        >
          Reset
        </button>
        {dirty && savable && (
          <span
            style={{ color: 'var(--nexus-color-warning)', fontSize: '0.85rem' }}
            data-testid="repl-kernels-dirty"
          >
            Unsaved changes
          </span>
        )}
        {dirty && !savable && duplicates.size > 0 && (
          <span
            style={{ color: 'var(--nexus-color-danger)', fontSize: '0.85rem' }}
            data-testid="repl-kernels-duplicate-warning"
          >
            Resolve duplicate language tags before saving
          </span>
        )}
      </div>
    </div>
  )
}
