// BL-067 Phase 2d — saved-layout → plugin exporter.
//
// Pure functions that turn a (name, WorkspaceJSON) pair into the four
// files a layout plugin needs:
//
//   <slug>/manifest.toml       — community-plugin descriptor
//   <slug>/index.ts            — first-party-style shell-plugin source
//   <slug>/<slug>.layout.json  — the saved layout (plugin's payload)
//   <slug>/README.md           — install / caveat notes
//
// The companion runtime helper (`writeExportedPlugin`) lays them out
// under `<forge>/.forge/exports/<slug>/` via the storage IPC. It lives
// here so the storage-coupled write path and the pure generator stay
// in one file.
//
// Export form: a *first-party* shell plugin source file that imports
// `workspace.applySnapshot`. Community-plugin distribution is gated
// on WI-44 (marketplace) so we deliberately don't try to make the
// emitted source loadable through that pipeline yet — the README
// explains both paths.

import type { KernelAPI } from '../../../types/plugin'
import type { WorkspaceJSON } from '../../../workspace/types'

const STORAGE_PLUGIN_ID = 'com.nexus.storage'
const EXPORT_DIR = '.forge/exports'

/** Slug a layout name into a directory-safe form. Lowercases, swaps
 *  whitespace for `-`, strips anything outside `[a-z0-9-_]`, collapses
 *  runs of `-`, and trims leading/trailing `-`. Returns `'layout'`
 *  for input that slugs to empty (e.g. all whitespace). */
export function slugify(name: string): string {
  const base = name
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9_-]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-+|-+$/g, '')
  return base.length === 0 ? 'layout' : base
}

/** camelCase a slug for use as a JS identifier. `focus-mode` becomes
 *  `focusMode`. Always returns a valid identifier (prefixes a leading
 *  underscore when the slug starts with a digit). */
export function camelize(slug: string): string {
  const parts = slug.split(/[-_]+/).filter(Boolean)
  if (parts.length === 0) return 'layout'
  const head = parts[0]!
  const tail = parts.slice(1).map((p) => p[0]!.toUpperCase() + p.slice(1))
  const ident = head + tail.join('')
  return /^[0-9]/.test(ident) ? `_${ident}` : ident
}

/** Set of files emitted for a single layout export. Every value is a
 *  string with a trailing newline so the storage write path can
 *  hand them straight to `write_file` without further normalisation. */
export interface ExportedFiles {
  /** File basename → file contents (UTF-8). */
  files: Record<string, string>
  /** The slug — used for the destination directory name. */
  slug: string
  /** The plugin id baked into manifest + index.ts. Stable for a given
   *  slug; useful for tests pinning the cross-file identifier. */
  pluginId: string
}

/** Build the four file contents for a saved layout. Pure — does not
 *  touch the filesystem. Returns the slug + plugin id alongside the
 *  files so the writer can name the destination directory and the
 *  caller's feedback can quote the plugin id. */
export function buildExportedFiles(
  name: string,
  layout: WorkspaceJSON,
): ExportedFiles {
  const slug = slugify(name)
  const ident = camelize(slug)
  const pluginId = `${slug}.layout`
  const layoutFilename = `${slug}.layout.json`

  const layoutJson = `${JSON.stringify(layout, null, 2)}\n`
  const manifest = renderManifestToml(name, slug, pluginId, layoutFilename)
  const indexTs = renderIndexTs(name, slug, ident, pluginId, layoutFilename)
  const readme = renderReadme(name, slug, pluginId, layoutFilename)

  return {
    files: {
      'manifest.toml': manifest,
      'index.ts': indexTs,
      [layoutFilename]: layoutJson,
      'README.md': readme,
    },
    slug,
    pluginId,
  }
}

function renderManifestToml(
  name: string,
  slug: string,
  pluginId: string,
  layoutFilename: string,
): string {
  // TOML-friendly escaping — the only chars we treat as interesting in
  // the metadata fields are `"` and `\`. Newlines are forbidden in
  // single-quoted basic strings, so we replace any with a space.
  const esc = (s: string) =>
    s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/[\r\n]+/g, ' ')
  return `# Auto-generated by Nexus View Builder.
# Source layout: "${esc(name)}"
# This manifest describes the layout-plugin form. The companion
# index.ts is a first-party shell-plugin source; see README.md
# for the two install paths.

id = "${esc(pluginId)}"
name = "${esc(name)} layout"
version = "0.1.0"
core = false
popout_compatible = false
activation_events = ["onStartup"]
depends_on = ["nexus.workspace", "nexus.viewBuilder"]

[contributes.commands]
"${esc(slug)}.apply" = { title = "Apply ${esc(name)} layout" }

[layout]
slug = "${esc(slug)}"
file = "${esc(layoutFilename)}"
`
}

function renderIndexTs(
  name: string,
  slug: string,
  ident: string,
  pluginId: string,
  layoutFilename: string,
): string {
  // The emitted source is a first-party shell-plugin module. To use it,
  // a developer drops the directory into `shell/src/plugins/nexus/`
  // and wires it into the catalog. The README spells this out.
  //
  // The `import layout from './<file>.layout.json'` line uses TS's
  // JSON-module support — the shell's tsconfig already has
  // resolveJsonModule + esModuleInterop. The `as WorkspaceJSON` cast
  // is intentional: the JSON shape matches WorkspaceJSON by
  // construction but the type system can't verify that across the
  // file boundary.
  const cmd = `${slug}.apply`
  return `// Auto-generated by Nexus View Builder.
// Layout: "${name}"
// Plugin id: "${pluginId}"
//
// Drop this directory into \`shell/src/plugins/nexus/\` and add the
// exported plugin to the shell's plugin catalog to bake the layout
// into the build. See README.md for the runtime / community-plugin
// path (gated on WI-44).

import type { Plugin, PluginAPI } from '../../../types/plugin'
import type { WorkspaceJSON } from '../../../workspace/types'

import layoutData from './${layoutFilename}'

const layout = layoutData as unknown as WorkspaceJSON

export const ${ident}LayoutPlugin: Plugin = {
  manifest: {
    id: '${pluginId}',
    name: '${escapeJsString(name)} layout',
    version: '0.1.0',
    core: false,
    activationEvents: ['onStartup'],
    popoutCompatible: false,
    dependsOn: ['nexus.workspace'],
  },

  async activate(api: PluginAPI) {
    api.commands.register('${cmd}', async () => {
      await api.workspace.applySnapshot(layout)
    })
  },
}
`
}

function renderReadme(
  name: string,
  slug: string,
  pluginId: string,
  layoutFilename: string,
): string {
  const cmd = `${slug}.apply`
  return `# ${name} layout

Auto-generated by Nexus View Builder.

This directory contains a Nexus shell-layout plugin. The plugin restores
the saved layout exactly as it was at export time.

## Files

- \`${layoutFilename}\` — the layout payload (a serialized
  \`WorkspaceJSON\`). This file alone is sufficient to import the
  layout via the View Builder UI: drop it into another forge's
  \`.forge/layouts/\` directory and apply it from the View Builder
  panel.
- \`manifest.toml\` — the plugin descriptor. Currently informational;
  full marketplace install lands with WI-44.
- \`index.ts\` — first-party shell-plugin source. Drop this directory
  into \`shell/src/plugins/nexus/\` and add the export to the shell
  plugin catalog to bake the layout into a custom build.
- \`README.md\` — this file.

## Install paths

### A. Layout-only (works today)

1. Copy \`${layoutFilename}\` into the destination forge's
   \`.forge/layouts/\` directory.
2. Open the View Builder panel and click **Apply** on the layout row.

### B. As a first-party shell plugin (developer build)

1. Copy this directory to \`shell/src/plugins/nexus/${slug}/\`.
2. Register the plugin in the shell's plugin catalog (next to the
   other entries under \`shell/src/plugins/nexus/index.ts\`).
3. Rebuild the shell. On startup the plugin registers a
   \`${cmd}\` command that calls
   \`api.workspace.applySnapshot(layout)\`. Bind it to a keybinding
   or invoke from the command palette.

### C. As a community plugin (deferred — WI-44)

The \`manifest.toml\` is shaped for the eventual community-plugin
pipeline. Until WI-44 (marketplace) ships, treat it as documentation.

## Plugin id

\`${pluginId}\`
`
}

/** Escape a string for embedding inside a single-quoted JS string
 *  literal. Handles the quote, the escape char, and CR/LF. */
function escapeJsString(s: string): string {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n')
}

const utf8Encoder = new TextEncoder()

/** Forge-relative directory path the export will be written to. */
export function exportDirRelpath(slug: string): string {
  return `${EXPORT_DIR}/${slug}`
}

/** Lay the four export files under `<forge>/.forge/exports/<slug>/`
 *  via the storage IPC. Returns the forge-relative directory path
 *  that was written.
 *
 *  Storage does not require explicit `create_dir` calls before
 *  `write_file` writes a nested path — the storage plugin auto-
 *  creates intermediate directories. We still try `create_dir` first
 *  for the export root because skipping it would silently succeed
 *  even when the storage plugin is in a degraded state, and the
 *  early failure mode is more actionable. */
export async function writeExportedPlugin(
  kernel: KernelAPI,
  files: ExportedFiles,
): Promise<string> {
  const dir = exportDirRelpath(files.slug)
  // Best-effort dir-create. The storage plugin's `AlreadyExists`
  // variant is the expected case on a re-export; any other error
  // bubbles through the first `write_file` below.
  try {
    await kernel.invoke<Record<string, never>>(STORAGE_PLUGIN_ID, 'create_dir', {
      relpath: dir,
    })
  } catch {
    /* fall through — write_file is the canonical error path */
  }
  for (const [filename, contents] of Object.entries(files.files)) {
    const path = `${dir}/${filename}`
    const bytes = Array.from(utf8Encoder.encode(contents))
    await kernel.invoke<unknown>(STORAGE_PLUGIN_ID, 'write_file', {
      path,
      bytes,
    })
  }
  return dir
}
