//! LLM-driven planner (PRD-15 §3.2).
//!
//! [`LlmAgent`] produces plans by asking an LLM to emit a structured
//! JSON document. The actual chat call is delegated to a
//! [`ChatDriver`] trait so the agent library stays kernel-free — a
//! concrete driver wraps `com.nexus.ai::stream_chat` and lives in
//! `nexus-bootstrap`.
//!
//! The expected response shape is a minimal subset:
//!
//! ```json
//! {
//!   "steps": [
//!     { "description": "…", "tool_call": null },
//!     {
//!       "description": "…",
//!       "tool_call": {
//!         "target_plugin_id": "com.nexus.storage",
//!         "command_id": "read_file",
//!         "args": { "path": "notes/today.md" }
//!       }
//!     }
//!   ]
//! }
//! ```
//!
//! Step ids are generated by the agent (`step-1`, `step-2`, …); LLM
//! output doesn't need to invent stable names. Any shape mismatch is
//! surfaced as [`AgentError::PlanningFailed`] with the raw text
//! truncated for diagnostics.

use async_trait::async_trait;
use serde::Deserialize;

use crate::{Agent, AgentError, Plan, Step, ToolCall};

/// Default instructions prepended to every [`LlmAgent`] planning
/// request. Describes the required JSON shape + lists a handful of
/// core plugins so the model knows what's callable. Consumers can
/// override with [`LlmAgent::with_system_prompt`].
pub const DEFAULT_SYSTEM_PROMPT: &str = "\
You are Nexus's planner. Given a user goal, produce a minimal JSON \
plan of atomic steps. Respond with JSON only — no prose, no code \
fences. Schema:\n\
  {\"steps\":[{\"description\":string,\"tool_call\":null | \
  {\"target_plugin_id\":string,\"command_id\":string,\"args\":object}}]}\n\
Available plugins: com.nexus.storage, com.nexus.database, \
com.nexus.git, com.nexus.terminal, com.nexus.ai. Prefer fewer, \
larger steps. Omit tool_call for informational updates.";

/// Minimal chat abstraction the planner calls. Concrete impls wrap
/// the AI plugin via IPC; tests can supply a canned driver.
#[async_trait]
pub trait ChatDriver: Send + Sync {
    /// Send `user_message` with the given `system` prompt, return the
    /// full assistant text. Streaming is handled inside the driver;
    /// callers only see the final string.
    ///
    /// # Errors
    /// Any transport / provider failure is surfaced as a string.
    async fn chat(&self, system: &str, user_message: &str) -> Result<String, String>;
}

/// LLM-driven agent. Wraps a [`ChatDriver`] and a system prompt.
pub struct LlmAgent<D: ChatDriver> {
    id: String,
    driver: D,
    system_prompt: String,
}

impl<D: ChatDriver> LlmAgent<D> {
    /// Construct with the default planner prompt.
    #[must_use]
    pub fn new(driver: D) -> Self {
        Self {
            id: "com.nexus.agent.llm".into(),
            driver,
            system_prompt: DEFAULT_SYSTEM_PROMPT.to_string(),
        }
    }

    /// Override the system prompt — useful for specialized archetypes
    /// (e.g. a Writer agent that biases toward markdown-authoring
    /// steps).
    #[must_use]
    pub fn with_system_prompt(mut self, prompt: impl Into<String>) -> Self {
        self.system_prompt = prompt.into();
        self
    }

    /// Override the agent id. Default `com.nexus.agent.llm`.
    #[must_use]
    pub fn with_id(mut self, id: impl Into<String>) -> Self {
        self.id = id.into();
        self
    }
}

#[async_trait]
impl<D: ChatDriver> Agent for LlmAgent<D> {
    fn id(&self) -> &str {
        &self.id
    }

    async fn plan(&self, goal: &str) -> Result<Plan, AgentError> {
        let goal = goal.trim();
        if goal.is_empty() {
            return Err(AgentError::PlanningFailed("empty goal".into()));
        }
        let raw = self
            .driver
            .chat(&self.system_prompt, goal)
            .await
            .map_err(AgentError::PlanningFailed)?;
        let doc = extract_json_object(&raw).ok_or_else(|| {
            AgentError::PlanningFailed(format!(
                "planner response did not contain a JSON object: {}",
                truncate(&raw, 200)
            ))
        })?;
        let parsed: PlanDoc = serde_json::from_str(doc).map_err(|e| {
            AgentError::PlanningFailed(format!(
                "planner JSON did not match schema: {e}; doc={}",
                truncate(doc, 200)
            ))
        })?;
        if parsed.steps.is_empty() {
            return Err(AgentError::PlanningFailed(
                "planner returned zero steps".into(),
            ));
        }
        let steps = parsed
            .steps
            .into_iter()
            .enumerate()
            .map(|(i, s)| Step {
                id: format!("step-{}", i + 1),
                description: s.description,
                tool_call: s.tool_call,
            })
            .collect();
        Ok(Plan::new(goal, steps))
    }
}

// ── JSON shape used only inside the planner ─────────────────────────────────

#[derive(Deserialize)]
struct PlanDoc {
    steps: Vec<StepDoc>,
}

#[derive(Deserialize)]
struct StepDoc {
    description: String,
    #[serde(default)]
    tool_call: Option<ToolCall>,
}

/// Find the first `{…}` block in `s`. Handles models that wrap JSON
/// in prose or code fences without needing to strip markdown first.
fn extract_json_object(s: &str) -> Option<&str> {
    let start = s.find('{')?;
    let mut depth = 0i32;
    let mut in_str = false;
    let mut escape = false;
    let bytes = s.as_bytes();
    for (i, &b) in bytes.iter().enumerate().skip(start) {
        if escape {
            escape = false;
            continue;
        }
        if in_str {
            if b == b'\\' {
                escape = true;
            } else if b == b'"' {
                in_str = false;
            }
            continue;
        }
        match b {
            b'"' => in_str = true,
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    return Some(&s[start..=i]);
                }
            }
            _ => {}
        }
    }
    None
}

fn truncate(s: &str, max: usize) -> String {
    if s.len() <= max {
        s.to_string()
    } else {
        let mut end = max;
        while !s.is_char_boundary(end) && end > 0 {
            end -= 1;
        }
        format!("{}…", &s[..end])
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    struct CannedDriver {
        reply: String,
    }
    impl CannedDriver {
        fn new(reply: impl Into<String>) -> Self {
            Self { reply: reply.into() }
        }
    }
    #[async_trait]
    impl ChatDriver for CannedDriver {
        async fn chat(&self, _system: &str, _user: &str) -> Result<String, String> {
            Ok(self.reply.clone())
        }
    }

    #[tokio::test]
    async fn llm_agent_parses_plain_json() {
        let driver = CannedDriver::new(
            r#"{"steps":[{"description":"read notes","tool_call":{"target_plugin_id":"com.nexus.storage","command_id":"read_file","args":{"path":"notes/a.md"}}},{"description":"summarise","tool_call":null}]}"#,
        );
        let agent = LlmAgent::new(driver);
        let plan = agent.plan("summarise today's notes").await.unwrap();
        assert_eq!(plan.goal, "summarise today's notes");
        assert_eq!(plan.steps.len(), 2);
        assert_eq!(plan.steps[0].id, "step-1");
        assert_eq!(plan.steps[0].description, "read notes");
        assert!(plan.steps[0].tool_call.is_some());
        assert!(plan.steps[1].tool_call.is_none());
    }

    #[tokio::test]
    async fn llm_agent_tolerates_prose_wrapper() {
        let driver = CannedDriver::new(
            "Sure, here's a plan:\n\n```json\n{\"steps\":[{\"description\":\"hello\"}]}\n```",
        );
        let agent = LlmAgent::new(driver);
        let plan = agent.plan("say hi").await.unwrap();
        assert_eq!(plan.steps.len(), 1);
        assert_eq!(plan.steps[0].description, "hello");
    }

    #[tokio::test]
    async fn llm_agent_rejects_non_json() {
        let driver = CannedDriver::new("I can't help with that.");
        let agent = LlmAgent::new(driver);
        let err = agent.plan("anything").await.unwrap_err();
        assert!(matches!(err, AgentError::PlanningFailed(_)));
    }

    #[tokio::test]
    async fn llm_agent_rejects_empty_steps() {
        let driver = CannedDriver::new(r#"{"steps":[]}"#);
        let agent = LlmAgent::new(driver);
        let err = agent.plan("whatever").await.unwrap_err();
        match err {
            AgentError::PlanningFailed(msg) => assert!(msg.contains("zero steps")),
            _ => panic!("unexpected error"),
        }
    }

    #[test]
    fn extract_json_object_handles_quoted_braces() {
        let s = r#"before {"key":"value with { }","n":1} trailing"#;
        let obj = extract_json_object(s).unwrap();
        assert_eq!(obj, r#"{"key":"value with { }","n":1}"#);
    }
}
