//! LLM-driven planner (PRD-15 §3.2).
//!
//! [`LlmAgent`] produces plans by asking an LLM to emit
//! provider-native tool-use blocks (Anthropic `tool_use` / OpenAI
//! `function_calls` / Ollama tool-calls), which the bootstrap-side
//! [`ChatDriver`] surfaces as a structured [`Proposal`]. Each
//! tool-use block becomes one [`Step`] in the resulting [`Plan`].
//! The agent crate stays kernel-free — the concrete driver wraps
//! `com.nexus.ai::propose_tool_calls` and lives in `nexus-bootstrap`.
//!
//! Per ADR 0023 (G7-1b) this replaces the pre-2026 free-form JSON
//! plan format. The model never sees a hand-written schema for the
//! plan envelope; the AI tool registry's per-tool schemas validate
//! arguments before dispatch.
//!
//! Step ids are generated by the agent (`step-1`, `step-2`, …) so
//! the model doesn't need to invent stable names. A turn that yields
//! no tool calls but nonzero text is recorded as a single
//! informational step carrying the model's narration.

use async_trait::async_trait;
use serde::{Deserialize, Serialize};

#[cfg(feature = "ts-export")]
use schemars::JsonSchema;
#[cfg(feature = "ts-export")]
use ts_rs::TS;

use crate::{Agent, AgentError, Plan, Step, ToolCall};

/// Default instructions prepended to every [`LlmAgent`] planning
/// request. Frames the agent's role and biases toward tool use; the
/// AI tool registry supplies the per-tool schemas, so this prompt
/// no longer enumerates plugin ids or describes argument shapes.
/// Consumers can override with [`LlmAgent::with_system_prompt`].
pub const DEFAULT_SYSTEM_PROMPT: &str = "\
You are Nexus's planner. Given a user goal, choose a minimal sequence \
of tool calls that accomplishes it. Use the tools you've been given \
rather than describing what you would do. Prefer fewer, broader tool \
calls over many tiny ones. If the goal is purely informational, \
respond with text and no tool calls.\n\
\n\
You see the running conversation, including your own earlier tool \
calls and their results. A tool result flagged as an error means that \
call failed — adjust your approach, and stop (responding with a short \
text summary, no tool calls) once the goal is complete or clearly \
unreachable.\n\
\n\
To change part of an existing file, prefer `edit` over `write_file`: \
read the file first (its reply carries a hashline `tag`), then send an \
`edit` patch whose `[path#TAG]` header uses that tag. Reserve \
`write_file` for creating a file or replacing it wholesale.\n\
\n\
When a goal involves running a shell command (build, test, dev \
server, lint), prefer the terminal tools: `terminal_run_saved` to \
launch the user's saved command by slug, `terminal_get_status` to \
poll for completion / read the exit code, and `terminal_send_signal` \
to send Ctrl-C / Ctrl-Z when a process needs to stop. A saved \
command's name typically encodes its purpose (\"dev-server\", \
\"unit-tests\"); pick the one whose slug matches the goal.";

/// One tool call the model proposed during a planning turn. Mirrors
/// the wire shape of [`crate::ToolCall`] — the bootstrap-side
/// driver runs the AI plugin's `dispatch_target` mapping before
/// surfacing the proposal here, so `target_plugin_id` and
/// `command_id` are already resolved.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-export", derive(TS, JsonSchema))]
#[cfg_attr(
    feature = "ts-export",
    ts(
        export,
        export_to = "../../../packages/nexus-extension-api/src/generated/ipc/"
    )
)]
#[serde(deny_unknown_fields)]
pub struct ProposedToolCall {
    /// Provider-issued id (used for diagnostics; not threaded into
    /// the executor today).
    pub id: String,
    /// Tool name as advertised in the AI registry (e.g.
    /// `read_file`, `mcp__notes__fetch`). Surfaced for log lines and
    /// the Step description.
    pub name: String,
    /// Resolved IPC dispatch target — ready to hand to
    /// [`crate::ToolDispatcher`].
    pub tool_call: ToolCall,
}

/// C27 (#380) — provider-reported token usage for one planning round.
/// Mirrors `nexus_ai::provider::TokenUsage`'s wire shape; kept as a
/// local copy since this crate stays kernel-free (ADR 0023) and can't
/// depend on `nexus-ai`.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct TokenUsage {
    /// Tokens the provider billed for the request side.
    pub input_tokens: u64,
    /// Tokens the provider billed for the response side.
    pub output_tokens: u64,
}

impl TokenUsage {
    /// Total tokens billed for this round.
    #[must_use]
    pub fn total(&self) -> u64 {
        self.input_tokens.saturating_add(self.output_tokens)
    }
}

/// What a [`ChatDriver`] returns from a planning turn.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Proposal {
    /// Aggregated narration the model emitted alongside (or instead
    /// of) tool calls. Surfaced as a single informational step when
    /// `tool_calls` is empty.
    pub text: String,
    /// Tool calls the model proposed, in order.
    pub tool_calls: Vec<ProposedToolCall>,
    /// C27 (#380) — token usage for this round, when the provider
    /// reported it. The session loop accumulates this across rounds
    /// to enforce [`crate::SessionConfig::max_tokens`].
    pub usage: Option<TokenUsage>,
}

/// Phase 5.5 (2c) — one tool call inside an [`AgentChatTurn::Assistant`]
/// turn. Serializes to the `com.nexus.ai::propose_tool_calls` `turns`
/// wire shape (`nexus_ai::ipc::AiTurnToolCall`) so the IPC-backed driver
/// can forward a full conversation with linkage intact.
#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct AgentTurnToolCall {
    /// Provider-issued tool-use id; the matching `tool_result` turn
    /// echoes it back.
    pub id: String,
    /// Tool name as advertised in the registry.
    pub name: String,
    /// Decoded tool arguments the model emitted.
    pub input: serde_json::Value,
}

/// Phase 5.5 (2c) — one conversation turn the agent loop replays to the
/// provider, preserving the assistant `tool_use` ↔ `tool_result`
/// linkage that the legacy single-string `propose` formulation dropped.
/// Serializes to the `nexus_ai::ipc::AiChatTurn` wire shape
/// (`tag = "kind"`); the agent crate stays kernel-/AI-free, so it owns
/// its own mirror rather than depending on `nexus-ai`.
#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum AgentChatTurn {
    /// A user message — the goal, a compacted-history preamble, or a
    /// resume follow-up.
    User {
        /// The user's text.
        content: String,
    },
    /// An assistant message: this round's narration plus the tool
    /// calls it proposed.
    Assistant {
        /// Assistant narration; empty when the round was tool-only.
        content: String,
        /// Tool calls proposed this round, in order.
        tool_calls: Vec<AgentTurnToolCall>,
    },
    /// One executed (or denied) tool call's result, keyed back to the
    /// originating [`AgentTurnToolCall::id`].
    ToolResult {
        /// The assistant tool-call id this answers.
        tool_use_id: String,
        /// Stringified result, or the error / denial reason when
        /// `is_error`.
        content: String,
        /// `true` for a failed or denied call.
        is_error: bool,
    },
}

/// Default projection of an [`AgentChatTurn`] conversation into a single
/// user prompt. Used by the [`ChatDriver::propose_turns`] fallback for
/// drivers that don't natively forward structured turns (the test
/// drivers and the single-shot planner driver); IPC-backed drivers
/// override `propose_turns` and never call this.
#[must_use]
pub fn flatten_turns_to_prompt(turns: &[AgentChatTurn]) -> String {
    let mut out = String::new();
    for turn in turns {
        match turn {
            AgentChatTurn::User { content } => {
                out.push_str(content);
                out.push('\n');
            }
            AgentChatTurn::Assistant {
                content,
                tool_calls,
            } => {
                if !content.is_empty() {
                    out.push_str(content);
                    out.push('\n');
                }
                for tc in tool_calls {
                    out.push_str("[tool_call ");
                    out.push_str(&tc.name);
                    out.push(' ');
                    out.push_str(&tc.input.to_string());
                    out.push_str("]\n");
                }
            }
            AgentChatTurn::ToolResult {
                content, is_error, ..
            } => {
                out.push_str(if *is_error {
                    "[tool error] "
                } else {
                    "[tool result] "
                });
                out.push_str(content);
                out.push('\n');
            }
        }
    }
    out
}

/// Planner-side chat abstraction. Concrete impls drive an AI
/// provider via IPC; tests supply canned drivers. Phase 1b of
/// ADR 0023 replaced the previous `chat(system, user) -> String`
/// surface so the planner can consume provider-native tool-use
/// blocks instead of guessing JSON shape from a free-form response.
#[async_trait]
pub trait ChatDriver: Send + Sync {
    /// Run one planning turn. Returns the model's narration plus
    /// every tool call it proposed (with dispatch targets already
    /// resolved). The driver does not execute tools — the agent's
    /// [`crate::PlanExecutor`] does that under approval policy.
    ///
    /// # Errors
    /// Any transport / provider / mapping failure is surfaced as a
    /// string.
    async fn propose(&self, system: &str, user_message: &str) -> Result<Proposal, String>;

    /// Phase 5.5 (2c) — run one planning turn against a full
    /// conversation rather than a single restated-goal string. The
    /// `turns` carry the assistant `tool_use` ↔ `tool_result` linkage,
    /// so a provider that understands function-calling sees a real
    /// multi-turn exchange (the model's own prior tool calls and their
    /// results) instead of a lossy bullet-point digest.
    ///
    /// The default flattens `turns` into one user message via
    /// [`flatten_turns_to_prompt`] and defers to [`propose`], so the
    /// many canned test drivers and the single-shot planner driver keep
    /// working unchanged. The IPC-backed driver overrides this to
    /// forward the structured turns to `com.nexus.ai::propose_tool_calls`.
    ///
    /// # Errors
    /// Any transport / provider / mapping failure is surfaced as a
    /// string.
    async fn propose_turns(
        &self,
        system: &str,
        turns: &[AgentChatTurn],
    ) -> Result<Proposal, String> {
        self.propose(system, &flatten_turns_to_prompt(turns)).await
    }
}

/// LLM-driven agent. Wraps a [`ChatDriver`] and a system prompt.
pub struct LlmAgent<D: ChatDriver> {
    id: String,
    driver: D,
    system_prompt: String,
}

impl<D: ChatDriver> LlmAgent<D> {
    /// Construct with the default planner prompt.
    #[must_use]
    pub fn new(driver: D) -> Self {
        Self {
            id: "com.nexus.agent.llm".into(),
            driver,
            system_prompt: DEFAULT_SYSTEM_PROMPT.to_string(),
        }
    }

    /// Override the system prompt — useful for specialized archetypes
    /// (e.g. a Writer agent that biases toward markdown-authoring
    /// steps).
    #[must_use]
    pub fn with_system_prompt(mut self, prompt: impl Into<String>) -> Self {
        self.system_prompt = prompt.into();
        self
    }

    /// Override the agent id. Default `com.nexus.agent.llm`.
    #[must_use]
    pub fn with_id(mut self, id: impl Into<String>) -> Self {
        self.id = id.into();
        self
    }
}

#[async_trait]
impl<D: ChatDriver> Agent for LlmAgent<D> {
    fn id(&self) -> &str {
        &self.id
    }

    async fn plan(&self, goal: &str) -> Result<Plan, AgentError> {
        let goal = goal.trim();
        if goal.is_empty() {
            return Err(AgentError::PlanningFailed("empty goal".into()));
        }
        let proposal = self
            .driver
            .propose(&self.system_prompt, goal)
            .await
            .map_err(AgentError::PlanningFailed)?;

        let steps = proposal_to_steps(proposal);
        if steps.is_empty() {
            return Err(AgentError::PlanningFailed(
                "planner returned no tool calls and no narration".into(),
            ));
        }
        Ok(Plan::new(goal, steps))
    }
}

/// Map a [`Proposal`] to the agent's [`Step`] list. Each tool call
/// becomes one step; if the model emitted only narration, that
/// becomes a single informational step (no `tool_call`). The empty
/// case (no calls, no text) is left to the caller — `LlmAgent::plan`
/// surfaces it as a planning failure.
fn proposal_to_steps(proposal: Proposal) -> Vec<Step> {
    if !proposal.tool_calls.is_empty() {
        return proposal
            .tool_calls
            .into_iter()
            .enumerate()
            .map(|(i, p)| Step {
                id: format!("step-{}", i + 1),
                description: format!("call {}", p.name),
                tool_call: Some(p.tool_call),
            })
            .collect();
    }
    let trimmed = proposal.text.trim();
    if trimmed.is_empty() {
        return Vec::new();
    }
    vec![Step {
        id: "step-1".into(),
        description: trimmed.to_string(),
        tool_call: None,
    }]
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Canned driver: returns a fixed [`Proposal`] regardless of
    /// inputs. Used by every llm-side test that needs deterministic
    /// planner output.
    pub(crate) struct CannedDriver {
        proposal: Proposal,
    }
    impl CannedDriver {
        pub(crate) fn new(proposal: Proposal) -> Self {
            Self { proposal }
        }
    }
    #[async_trait]
    impl ChatDriver for CannedDriver {
        async fn propose(&self, _system: &str, _user: &str) -> Result<Proposal, String> {
            Ok(self.proposal.clone())
        }
    }

    #[test]
    fn token_usage_total_sums_input_and_output() {
        let u = TokenUsage {
            input_tokens: 30,
            output_tokens: 12,
        };
        assert_eq!(u.total(), 42);
    }

    #[test]
    fn token_usage_total_saturates_instead_of_overflowing() {
        let u = TokenUsage {
            input_tokens: u64::MAX,
            output_tokens: 1,
        };
        assert_eq!(u.total(), u64::MAX);
    }

    fn read_file_call(path: &str) -> ToolCall {
        ToolCall {
            target_plugin_id: "com.nexus.storage".into(),
            command_id: "read_file".into(),
            args: serde_json::json!({ "path": path }),
        }
    }

    #[tokio::test]
    async fn llm_agent_maps_tool_calls_one_per_step() {
        let driver = CannedDriver::new(Proposal {
            text: String::new(),
            tool_calls: vec![
                ProposedToolCall {
                    id: "toolu_1".into(),
                    name: "read_file".into(),
                    tool_call: read_file_call("notes/a.md"),
                },
                ProposedToolCall {
                    id: "toolu_2".into(),
                    name: "read_file".into(),
                    tool_call: read_file_call("notes/b.md"),
                },
            ],
            usage: None,
        });
        let agent = LlmAgent::new(driver);
        let plan = agent.plan("summarise today's notes").await.unwrap();
        assert_eq!(plan.steps.len(), 2);
        assert_eq!(plan.steps[0].id, "step-1");
        assert_eq!(plan.steps[0].description, "call read_file");
        assert_eq!(
            plan.steps[0].tool_call.as_ref().unwrap().command_id,
            "read_file"
        );
        assert_eq!(plan.steps[1].id, "step-2");
    }

    #[tokio::test]
    async fn llm_agent_falls_back_to_text_when_no_tool_calls() {
        let driver = CannedDriver::new(Proposal {
            text: "Nothing to do — the goal is informational.".into(),
            tool_calls: vec![],
            usage: None,
        });
        let agent = LlmAgent::new(driver);
        let plan = agent.plan("say hi").await.unwrap();
        assert_eq!(plan.steps.len(), 1);
        assert!(plan.steps[0].tool_call.is_none());
        assert!(plan.steps[0].description.contains("informational"));
    }

    #[tokio::test]
    async fn llm_agent_rejects_empty_proposal() {
        let driver = CannedDriver::new(Proposal::default());
        let agent = LlmAgent::new(driver);
        let err = agent.plan("anything").await.unwrap_err();
        let AgentError::PlanningFailed(msg) = err;
        assert!(msg.contains("no tool calls"));
    }

    #[tokio::test]
    async fn llm_agent_rejects_empty_goal() {
        let driver = CannedDriver::new(Proposal {
            text: "x".into(),
            tool_calls: vec![],
            usage: None,
        });
        let agent = LlmAgent::new(driver);
        let err = agent.plan("   \n\t  ").await.unwrap_err();
        assert!(matches!(err, AgentError::PlanningFailed(_)));
    }
}
